### ISSUE TITLE
[SM] Wrong machinery working in the wrong season

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#10]
When you try to harvest during rain, a message appears that you cannot do it. I see a simple implementation similar to that. Detect what the player is doing and then prevent the action. A more complicated solution: allow the player to do it, and make crops fail. This will be heavily dependent on how we implement the crop cycle / growth length, so should be parked for now.

**Comment by joskuijpers** [comment]
Currently, when the game asks for the max speed, I return 0 when it is winter. I also set a flag in the vehicle, and if it is set I draw a blinking message that the soil is too hard.

Currently all vehicles with an active WorkArea are 'disabled', but with a lookup table we could re-enable certain implements, like mowers

**Comment by joskuijpers** [comment]
Now mowers are enabled and it is possible to enable individual types of machines.
I also show a message to the player that the ground is frozen and can't be worked on
