### ISSUE TITLE
Snow tracks are created by lifted implements

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#100]
Make sure the implements are lowered before applying stuff. When having a tedder lifed on the back, it still creates tracks.

**Comment by mrbear** [comment]
I believe there is a way to check if a wheel have ground contact. Think I have seen code for that. Or it might have been to check if an implement had ground contact.

**Comment by joskuijpers** [comment]
`wheel.hasGroundContact`

**Comment by reallogger** [comment]
Thanks for the tip mrbear. Yes every wheel has a 'hasGroundContact' flag. Will look into it
