### ISSUE TITLE
Snow icon on hud becomes waay too big sometimes

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#103]

**Comment by reallogger** [comment]
![image](https://cloud.githubusercontent.com/assets/15114342/21867880/7e06655a-d850-11e6-90a2-4ace00a1cb5c.png)

**Comment by theSeb1979** [comment]
Is this still an issue? I haven't seen it myself recently.

**Comment by joskuijpers** [comment]
Neither have I but i dont know if anything changed in the code

**Comment by reallogger** [comment]
I did try to fix it by doing some changes to WF, but saw it also after that. However, now it's been a long while since I saw it. Will close the issue for now.
