### ISSUE TITLE
[GM] Fertilizing only possible once

### ISSUE THREAD

**Issue by Laui51** [RealismusModding/FS17_seasons#105]
Hi there,

found this by accident and think it's a super project. One thing i wondered about is that now i can only fertilize my field once. The fertilizing "texture" does not dissapear with the growing cycle but only with harvest. Settings are set to fertilizing 3 times. 

Is it a bug or me?

**Comment by theSeb1979** [comment]
It is possibly a bug or you haven't waited until the next growth stage. Just like vanilla you need to wait for the next growth stage to occur

**Comment by Laui51** [comment]
Like i said, the darker texture doesn't dissapear with the growing cycle, only by havesting.

But thanks, for the quick answer.

**Comment by theSeb1979** [comment]
Needs to be investigated then.

**Comment by mrbear** [comment]
Since we don't use giants growth manager we have to replicate all functionality from it in our code instead... Are there more things that's done on growth state change in the vanilla game that will have the same problem?

**Comment by joskuijpers** [comment]
I don't think so, but the field mission NPCs are not aligned with our system. So we will be fixing that,

**Comment by joskuijpers** [comment]
We need to update the fertilization on every growth state. If it is only for actual growth (and thus not when already fully grown), then it has to be done per-crop. Otherwise it can be done map wide I guess.
Absorbing it every growth stage seems like the best and easiest.

**Comment by theSeb1979** [comment]
Solution found. Need to implement

**Comment by theSeb1979** [comment]
I hope to never see this again.
