### ISSUE TITLE
Seasons will not load

### ISSUE THREAD

**Issue by redrummed1** [RealismusModding/FS17_seasons#113]
Hey guys seasons will not load for me on latest master zip, log throws this error, it shows up on mod selection screen but no menu options ingame.  Keep up the amazing work

Error: C:/Users/Aidan/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/loader.lua:55: unexpected symbol near 'if'

**Comment by joskuijpers** [comment]
Hi reddrummed1,

Nice that you are interested in Seasons! However, this mod in still WIP. We are working hard to get everything to work.

Keep an eye on this repository and YouTube to get all the updates.
