### ISSUE TITLE
Multiplayer issue

### ISSUE THREAD

**Issue by Furius-Starfall** [RealismusModding/FS17_seasons#127]
Hi, today i found your's mod and it's epic. In singleplayer works fantastically but in MP i've got problem at the start game. This error is showing only on client site.
`C:/Users/corve/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons_master/src/ssWeatherManager.lua:119: attempt to index a nil value`

**Comment by joskuijpers** [comment]
Hi,

Thank you. We are aware that multiplayer does not work at the moment: I have to fix and implement all the stuff required to the new changes since 2 months. This will take a couple of weeks probably.

**Comment by Furius-Starfall** [comment]
I don't this so. I already try to fix that and next problem is on 559 line in the same script.

**Comment by joskuijpers** [comment]
As I said, making it work in Multiplayer is very complex and i will work on it coming weeks. Until then you will have to enjoy seasons in singleplayer

**Comment by Furius-Starfall** [comment]
Ok, thank you a lot.
