### ISSUE TITLE
Snow in tippers will never melt

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#135]
I suggest we inject into Fillable, and when airTemp > 0 we remove a percentage of the content (some formula?) with a minimum of C (100?) so it will be empty.
This might automatically work on shovels and such as well.

It will also be very cool to add snow in a trailer if it is snowing and there is no cover. And the tipper is empty, of course

**Comment by joskuijpers** [comment]
@reallogger 
Can you make 2 algorithms: a melting one with input (currentLiters, currentTemperature)
And one that adds snow inside a trailer given the snow information

Both formulas could use a tipper capacity to guesstimate the visible surface

**Comment by joskuijpers** [comment]
I made a ssSnowFillable specialization, currently added to every fillable vehicle. I also cached the current minute temperature for FPS reasons.
The updateTick code needs some tiny algorithm (nothing too heavy).

I think filling the trailer should depend on how much snow really falls and be not much more than what falls on the ground in the guesstimated same surface. With this, one will have actual reason to close a cover.

**Comment by reallogger** [comment]
Instead of using vehicle:allowFillFromAir() for checking whether it has a cover, there is a Cover specialization. 
https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=2587

Then you can check self.isCoverOpen == isOpen

**Comment by joskuijpers** [comment]
I do think my way is better. I know about the snow Cover. The allowFillFromAir is actually overridden by the Cover specialization to return false when the cover is on.
I thought it would also prevent some problems later on with odd fillables
I figured, if something is not fillable from air, snow would also not be able to fill it

**Comment by Dzi4d3k** [comment]
Indeed we don't need snow in slurry tank :P

**Comment by joskuijpers** [comment]
Both melting and filling works but needs an algorithm. The function vehicleInShed needs to be implemented with the snow mask.
The cover works.

**Comment by reallogger** [comment]
Fixed with fb3bf8d
