### ISSUE TITLE
Create console command ssStartSnow

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [RealismusModding/FS17_seasons#140]
For testing very convenient.

**Comment by joskuijpers** [comment]
I am not sure what this should do.
Place a new layer of snow on the ground?
Or add a snow event to the weather and make sure the temperature is cold enough that it will even snow?

The latter one might not be very possible without breaking stuff. The first one can be done.

**Comment by reallogger** [comment]
Go for add a layer of snow.

**Comment by theSeb1979** [comment]
yup, first one makes sense

**Comment by Dzi4d3k** [comment]
Agree, might be useful, as three continuous in game years didn't gave me 0,5 m of snow.

**Comment by joskuijpers** [comment]
Alright will look into it tomorrow.
You will probably never get 0.5 meters of snow. That is a LOT for sea level :P To have such snow a map should change the weather temperatures to fit a scandinavian climate.
