### ISSUE TITLE
Leasing cost not updated after the first hour

### ISSUE THREAD

**Issue by jaksoor** [RealismusModding/FS17_seasons#147]
Hi there 
I'm following this project from the begining, and i'm loving it.
I lowered the leasing cost per hour in ssEconomy to 0.02 after the first hour the cost goes up to the original (0.05).

**Comment by joskuijpers** [comment]
I am not sure what you mean. What did you change?

**Comment by jaksoor** [comment]
In ssEconomy Line 34 i changed EconomyManager.DEFAULT_RUNNING_LEASING_FACTOR = 0.04 to 0.02

**Comment by theSeb1979** [comment]
Is this a bug? Do we need to fix?

**Comment by jaksoor** [comment]
where i live (italy) there is no leasing cost per operating hour instead there is a monthly cost, and i play at 3 days per season, so being 1 day in game as a month, i intend to remove the leasing cost per hour(DEFAULT_RUNNING_LEASING_FACTOR) and keep the leasing deposit and make the PER_DAY_LEASING_FACTOR something like 0.1 (10% of the price). 
I tried this but the leasing cost is getting paid every hour after the first hour.
i hope i have explained as my english is not good enough

**Comment by jaksoor** [comment]
this is what i modified.
    EconomyManager.DEFAULT_LEASING_DEPOSIT_FACTOR = 0.05 -- factor of price (vanilla: 0.05)
    EconomyManager.DEFAULT_RUNNING_LEASING_FACTOR = 0 -- factor of price (vanilla: 0.05)
    EconomyManager.PER_DAY_LEASING_FACTOR = 0.1 -- factor of price (vanilla: 0.01)

**Comment by joskuijpers** [comment]
hi @jaksoor 
Thank you for playing with Seasons!
However, we can't give support on changes you make yourself :( That would be too much work. You will need to try to figure out yourself why this happens.

I can tell you that the hourly cost for leasing is calculated using the vehicle lease cost, not the DEFAULT_RUNNING_LEASING_FACTOR. So you will need to change your vehicles instead.
