### ISSUE TITLE
HUDs are not sharp

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#148]
The Huds, and mostly the current temp hud, is foggy and not sharp at all.
We should try to figure out how Giants did it and replicated that.

Also might want to move the current temp hud more to the right

![image](https://cloud.githubusercontent.com/assets/5017040/23000647/c0001436-f3e1-11e6-87f7-e7877b0901b8.png)

**Comment by joskuijpers** [comment]
We can draw the HUD in place without images, using the overlay:setColor

**Comment by joskuijpers** [comment]
The clock symbol really needs fixing.

**Comment by Gonimy-Vetrom** [comment]
https://drive.google.com/file/d/0B_zrlMUSl3roQU5xRUxNWmdITVk/view?usp=sharing

**Comment by joskuijpers** [comment]
I want to reference to the vanilla symbol instead

**Comment by joskuijpers** [comment]
Clock has been fixed. Later we should fix the overlays, the borders are not nice and sharp
![screen shot 2017-04-14 at 01 13 52](https://cloud.githubusercontent.com/assets/5017040/25027795/a38803e0-20af-11e7-8588-8ecf3fa2e037.png)

**Comment by baleBaron** [comment]
Is it possible to disable texture filtering for hud_day.dds? That would solve it. Looks like some linear pixel interpolation is the issue?

**Comment by joskuijpers** [comment]
Okay, will try that.

Wanted to draw the background like I draw the Overview GUI, but fixing the images works as well.

**Comment by heavenlypictures** [comment]
It's way easier to use an image than drawing it.
I know it will works, because I already had this issue with my mods. It takes me a very long time to solve it by not saving MIP maps.
Just check out Giants' store icons in the data folder. Open them, and try to load the MIP maps. There's no MIP maps. That's why they are so sharp.

**Comment by Dzi4d3k** [comment]
Indeed that's a general rule. Hud images shouldn't have mipmaps. I'm pissed, that I didn't checked that.

**Comment by joskuijpers** [comment]
@Dzi4d3k do you have access to a program to make them mipmap-less?

**Comment by Dzi4d3k** [comment]
Just not checking mipmap creation works fine. I suppose all programs have that option. For example in paint.net there is check box "generate mipmaps" when saving DDS, so it will work to just re-save mentioned files with that option unchecked.

**Comment by joskuijpers** [comment]
I know, but I don't have software that can save dds files :P And I can't run paint.net either.

@reallogger ?

**Comment by reallogger** [comment]
I'll do it

**Comment by reallogger** [comment]
Done with 549b2a3

**Comment by joskuijpers** [comment]
![screen shot 2017-06-18 at 21 57 17](https://user-images.githubusercontent.com/5017040/27263787-23619262-5471-11e7-8640-16f15bac347f.png)

**Comment by Dzi4d3k** [comment]
Sharp as razor :)

**Comment by joskuijpers** [comment]
So yes, it is sharper now. Still, drawing 2 rectangles would have been even sharper... with even coloring (now the coloring is not even) and better pixel alignment.

**Comment by Dzi4d3k** [comment]
But problem was with icons not with hud background.

**Comment by joskuijpers** [comment]
Oh, for me it was about the background

**Comment by Dzi4d3k** [comment]
Is scaling required for hud? Or will it scale with changing in game settings?

**Comment by joskuijpers** [comment]
It is not pixel perfect. Image-on-screen, due to different resolutions of game vs monitor vs gui size
