### ISSUE TITLE
When maple tree is placed, the replacement materialId is nil

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#150]
'Fixed' it by skipping all that are nil, but I don't know if the underlying problem is more severe. Should the default maple texture replacement work on placed maples?

**Comment by mrbear** [comment]
If I remember this correctly the normal replacement works on placed trees as well but only at the season change event. So when a tree is placed we have to do texture replacement to make it look right untill the next season change.

**Comment by joskuijpers** [comment]
A possible fix is to: when placeable tree is placed, first store default material before changing it.

**Comment by joskuijpers** [comment]
Fixed
