### ISSUE TITLE
Repairs do not work on GCV on new savegame

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#158]
When starting a new savegame, the Combine needs to be repaired according to the label (is this also true for breaking down? This code needs to be aligned!)
However it cant be fixed because the repair costs are 0.

**Comment by reallogger** [comment]
The following does not work: 
https://github.com/RealismusModding/FS17_seasons/blob/master/src/ssRepairable.lua#L23

ssYesterdayOperatingTime has to be set after operatingTime is loaded from the maps vehicle.xml.

**Comment by reallogger** [comment]
Temporarily fixed by a343c83
