### ISSUE TITLE
Lua Method Error : Baldeykino

### ISSUE THREAD

**Issue by striderhiryu26** [RealismusModding/FS17_seasons#162]
hello there, i`m trying to load this amazing mod on loads of maps and sseing if something pops up, it did on trying to load on this map

Error: Running LUA method 'LoadMapFinished'

src/ssAnimals.lua:47: attempt to index a nil value

after this, the map never finishes loading and no log is created

**Comment by theSeb1979** [comment]
I suspect this map does not have animals. I will take a look at this bug

**Comment by joskuijpers** [comment]
The code I committed should fix it.
