### ISSUE TITLE
What can be planted menu missing

### ISSUE THREAD

**Issue by jffouche** [RealismusModding/FS17_seasons#163]
Hi

The menu that tells you what can be planted and what not is missing after I downloaded the latest.

The / or ? just above Ctrl does not bring up that menu anymore, is there a new key combination?

Thanx

**Comment by theSeb1979** [comment]
The functionality is for debug purposes only and does not work in multiplayer so it has been disabled in the mod. A proper version of what can be planted will appear in the mod at some time in the future.
