### ISSUE TITLE
Melting snow should increase ground wetness

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#168]
Is nice for the ground realism mods

**Comment by reallogger** [comment]
This is not trivial. g_currentMission.environment.groundWetness will act globally. If the players has been mowing snow they would still suffer from low friction also where the snow is not melting. Keeping track of where snow is melting will be too demanding for such a feature.

**Comment by joskuijpers** [comment]
hmm right okay.
