### ISSUE TITLE
Fields turn from seeded to harvested

### ISSUE THREAD

**Issue by jffouche** [RealismusModding/FS17_seasons#169]
Hi

Here I have a pictures that you can check out.

When fields are seeded and goes to next growth stage it turns from seeded to harvested.

Is it something I'm doing wrong?
I am using game extension mod

![20170302_201432](https://cloud.githubusercontent.com/assets/14186722/23520631/88a23b0a-ff84-11e6-9e69-ecdeb317891f.jpg)
![20170302_201427](https://cloud.githubusercontent.com/assets/14186722/23520632/88a282f4-ff84-11e6-8aa8-bed979fdaee9.jpg)

**Comment by theSeb1979** [comment]
Looks like you planted in early summer and the plants died (we use the harvested / cut state to show that plants died). Working as intended from what I can see.

**Comment by jffouche** [comment]
Ok thanx

Can you please help with a list of what can be planted when?

Sorry for asking but have no idea when to plant what.

Thanks again!

**Comment by joskuijpers** [comment]
We shall release more information very soon! 😄
