### ISSUE TITLE
[GM] Growth help gui

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#171]
Need to implement the what crops can be planted at what time and when they can be harvested info.

**Comment by joskuijpers** [comment]
@theSeb1979 
I must approve your great insight in writing a thoughtful and elaborate explanation of this issue

**Comment by theSeb1979** [comment]
Thank you. Yes, I think it's pretty good as a requirement definition document goes. Certainly compliant with IEEE standards

**Comment by joskuijpers** [comment]
Just need two functions that say at what transitions what can be planted and harvested. Maybe also some data that tells where what plants will be killing? Is that hard?

All this data must be available on the client as well. I think it isn't random so it shouldn't be a problem?

**Comment by theSeb1979** [comment]
canBePlanted is implemented. canBeHarvested WIP

Killing is complex from a display point of view - will discuss in slack

**Comment by theSeb1979** [comment]
Implemented, however need to extend canHarvest to account for when the fruit will die beyond harvestable

**Comment by joskuijpers** [comment]
Also need to add a legend.
Do we need to add the full date somewhere?

**Comment by theSeb1979** [comment]
canHarvest extended

**Comment by theSeb1979** [comment]
This is implemented. Bug recorded separately, so can close this.
