### ISSUE TITLE
Adjust money stuff of placeables

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#174]
Barns
Sheds
Solar panels
Greenhouses

**Comment by joskuijpers** [comment]
Income for all placeables is adjusted: `originalIncom * (6 / seasonLength)`. This does mean the income for 3 day seasons is very high.
We might want to change the income alltogether: not use the vanilla values like this (maybe another factor).
If we base it on 3 day seasons instead, the ROI in years for beehouse is 4,4, greenhouse is 1,46 and wind is 4,18. Solar is 4,9. So that sounds kinda of realistic.
Income is then, per year, 4500, 17000, 287000, 26000.

![image](https://cloud.githubusercontent.com/assets/5017040/24022592/b91b11b6-0aa7-11e7-81f1-e11801d3c722.png)

I did change the current daily upkeep as well, using the same 6/length formula.

**Comment by joskuijpers** [comment]
@reallogger needs to look at the realism part. It might be necessary to use `3/length` instead. Gives better ROI figures and doesn't make the 3 day seasons excessive.

**Comment by reallogger** [comment]
Fixed with 38a3b98
