### ISSUE TITLE
Few bugs (i think)

### ISSUE THREAD

**Issue by jmj486** [RealismusModding/FS17_seasons#175]
I mid summer sheeps still produce wool, and pigs dont reproduce

**Comment by theSeb1979** [comment]
In summer sheep produce wool and pigs don't reproduce as per design

You can change the values in animals.xml if you feel that they need to be different.

` <summer>
            <properties type="cow">
                <straw>17.5</straw>
                <food>315</food>
                <water>52.5</water>
                <birthRate>0.08</birthRate>
                <milk>571.2</milk>
                <manure>180</manure>
                <liquidManure>300</liquidManure>
            </properties>

            <properties type="sheep">
                <food>27</food>
                <water>22.5</water>
                <birthRate>0</birthRate>
                **<wool>28.8</wool>**
            </properties>

            <properties type="pig">
                <straw>5</straw>
                <food>81</food>
                <water>15</water>
                **<birthRate>0</birthRate>**
                <manure>45</manure>
                <liquidManure>97.5</liquidManure>
            </properties>
        </summer>`
