### ISSUE TITLE
Cant find the mod

### ISSUE THREAD

**Issue by ingetsikte** [RealismusModding/FS17_seasons#177]
Hi! I just downloaded season mod and i cant find the mod where i select mods when i start new savegame... How do should i do to get it work?

**Comment by theSeb1979** [comment]
Hi. Thanks for the interest in our mod. Unfortunately, since this is a work in progress, we are unable to provide any support on how to install the mod.

**Comment by ingetsikte** [comment]
Ah okey! Do you have any idea when it will be released

**Comment by theSeb1979** [comment]
When we finish it :-)
