### ISSUE TITLE
FM breaks compatibility with 4real crop destruction

### ISSUE THREAD

**Issue by baleBaron** [RealismusModding/FS17_seasons#183]
minHarvestingGrowthState = maxHarvestingGrowthState makes FS17_ForRealModule01_CropDestruction detect all non `fruitsToExclude` as oilseed:

From FS17_ForRealModule01_CropDestruction 
`
            elseif desc.minHarvestingGrowthState == desc.maxHarvestingGrowthState then
                -- oilseed, no destruction
`

From ssFruitManager
`
            -- Minimize the time a crop can be harvested (1 stage, not ~3)
            FruitUtil.fruitIndexToDesc[index].minHarvestingGrowthState = FruitUtil.fruitIndexToDesc[index].maxHarvestingGrowthState
`

**Comment by theSeb1979** [comment]
Issue resolved by updating crop destruction. Need to understand if it's possible to release a modified version of a giants mod on mod hub.

**Comment by theSeb1979** [comment]
Issued fixed permanently. Seasons is now compatible with Crop Destruction. No need to use our own version of it anymore.
