### ISSUE TITLE
Traffic lights and other lights don't turn on early enough

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#184]
rahkiin [12:57 AM] 
Found a bug: the traffic lifgting and other lights dont turn on early enough

[12:57]  
So we forgot some value or did a value wrong in the daytime change

**Comment by joskuijpers** [comment]
Must know if all the lights have this behaviour or just the traffic.
If just the traffic, we can't fix it.

**Comment by reallogger** [comment]
https://gdn.giants-software.com/documentation_scripting.php?version=script&category=65&class=3354#weatherChanged45571

Not sure if we do anything with g_currentMission.environment.isSunOn? Maybe that would solve it?

**Comment by joskuijpers** [comment]
Okay I improved it. The morning might need a it more tweaking.
I have discovered however that the traffic system doesn't care about the settings we do so we can't fix that :( I guess they will turn on at 9PM and off at 5:30AM

**Comment by joskuijpers** [comment]
Fixed it by hacking the traffic system.
