### ISSUE TITLE
cropMoistureContent might need some tuning

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#185]
baron [12:54 PM] 
Maybe cropMoistureContent might need some tuning, for playability if not for realism.
After one shower in early autumn crop never dries before winter.
Playing with 3d/season, latitude 58, I'm having a deltaMoisture of ~2.0/day.

I added a small flat additional delta per hour to simulate wind/whatever extra factors not included to make my game playable again.
maybe problem might be equations does not scale with daysInSeason?
I ended up doing a simple deltaMoisture * 2, it increased my harvesting window from nothing to something.
Still has periods of wet crop in autumn.

rahkiin [2:29 PM] 
Hey
Hmm @reallogger should look at this
Maybe adding a wind factor helps

baron [2:32 PM] 
yeah or something. at 3d/season one day of sunshine will be a month of sunshine, crop should not stay wet

**Comment by reallogger** [comment]
Inital attempt will be to replace L842 in WM with:

local deltaMoisture = solarRadiation / 40 * (tmpMoisture - 10) * 9 / g_seasons.environment.daysInSeason

alternatively 

local deltaMoisture = solarRadiation / 40 * (tmpMoisture - 10) * math.sqrt( 9 / g_seasons.environment.daysInSeason)

Latter will lead to longer periods of moist crops than former.

**Comment by baleBaron** [comment]
Tried them both with 3d/season and my vote is on the latter.

**Comment by reallogger** [comment]
Thanks for testing baleBaron
