### ISSUE TITLE
When it rains at night, the sky it too light

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#190]
In vanilla it seems to never rain at night. The reason seems to be that the 'rain env setup' is too light for the night.
We can fix this by limiting to 'day' events as well.

![image](https://cloud.githubusercontent.com/assets/5017040/24173045/ca952dc8-0e8a-11e7-8ee8-37ebae95e6ec.png)

**Comment by Gonimy-Vetrom** [comment]
This is bad? I like the rain at night. Good incidental effect.

**Comment by Mike3650** [comment]
I think it should rain at night. I posted this picture on slack as I thought the sky should be darker considering it is early autumn, it's raining & the time is 23:43. 

The title of this issue is correct "When it rains at night, the sky it too light" maybe a typo in the description?

**Comment by joskuijpers** [comment]
Description is correct as well. As far as I know, the darkness when it rains is not determined by the darkness of the night.
The dayNight system works just fine :)

**Comment by Mike3650** [comment]
So in the picture it's too light because it's raining and by limiting rain to day time this won't happen, correct?

**Comment by Dzi4d3k** [comment]
If I may add my two cents, then I would prefer to leave rains during night over removing them to avoid such affect.

**Comment by joskuijpers** [comment]
I am fine with that as well. Later today I will see if we can change the rain darkness but I think not.

**Comment by reallogger** [comment]
I'm very reluctant in hard coding a requirement to not have rain at night.

**Comment by theSeb1979** [comment]
If the light during rain at night cannot be made darker, then we must live with it instead of stopping rains at night (as per others above)

**Comment by joskuijpers** [comment]
Yes that is what I meant to do. If we cant fix it then this is a WONTFIX

**Comment by joskuijpers** [comment]
Okay I improved it. The morning might need a it more tweaking.
I have discovered however that the traffic system doesn't care about the settings we do so we can't fix that :( I guess they will turn on at 9PM and off at 5:30AM

**Comment by joskuijpers** [comment]
Possible solution:
when night falls (same values used for trafficlights), switch the rainFadeCurve to one that is 2x darker. Do this only when it is not already raining.
Switch back in the morning.

(Also store whether it was switched in order to switch later)

**Comment by joskuijpers** [comment]
Possible solution:
change the partScale value of the sky shader to <1. It reduces all light. This should only be done when it rains at night, i guess.

**Comment by joskuijpers** [comment]
![image](https://user-images.githubusercontent.com/5017040/30004766-945274c8-90d5-11e7-8b52-397080d6da57.png)

Example. It just stopped raining and it fades to 'sun', but it is 12:45AM.

**Comment by joskuijpers** [comment]
This can't be fixed in FS17

**Comment by Dzi4d3k** [comment]
Can't Gaints help with this in upcoming 1.5 patch?

**Comment by joskuijpers** [comment]
Create a completely new sky system? No. And it is too late for 1.5 stuff now.
