### ISSUE TITLE
DDS files only

### ISSUE THREAD

**Issue by Dzi4d3k** [RealismusModding/FS17_seasons#192]
Just to note that dedicated server warn about any PNG files in mod, and there are still two files:
- hud_fill_snow.png
- hud_fill_snow_sml.png
Unfortunately I'm unable to create pull request or attach DDS files here in issue.
I uploaded them on Slack some time ago, but I think there were missed.

**Comment by joskuijpers** [comment]
Hey,

Sorry! Can you re-upload them, possibly on slack?

**Comment by Dzi4d3k** [comment]
Fastest one :D
