### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Mike3650** [RealismusModding/FS17_seasons#198]
A small typo I noticed in the README.md under Helpers:

Overtime, before 6AM and after 18AM or in the weekends, pays 150%

Shouldn't that be 6PM? Also 'on the' rather than 'in the' weekends.

Would this be better way?

Overtime rates are paid at 150% between the hours of 18:00 to 06:00 and at weekends.

**Comment by Dzi4d3k** [comment]
as well if 18 then not PM or 6 PM only

**Comment by Mike3650** [comment]
I meant to say 6PM not 18PM.

**Comment by joskuijpers** [comment]
You are right :) want to make a pull request?
You can open the readme and click on the editing icon (pencil). After you made the changes you can commit and make a pull request :D

**Comment by theSeb1979** [comment]
Fixed 7570b7c
