### ISSUE TITLE
Possible bug in the DensityScanner

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#202]
ssIterateOverTerrain is called on :update.
In that function is determined how many mapSegments there are and based on it the callback is run.
A bug can occur when during that update session the timescale is changed between >120 and <=120.
The number of segments have to be determined at a different moment. Probably inside the job.

**Comment by Dzi4d3k** [comment]
"is changed between >120 and <=120." that will mean that any change to time scale could cause bug during map update.

**Comment by joskuijpers** [comment]
It means if you, during a density update, change from 6000x to 1-120x or from 1-120x to 6000x, the savegame breaks

**Comment by Dzi4d3k** [comment]
ok, so going in or out 1-120x range could brake map layers, right?

**Comment by joskuijpers** [comment]
correct.

**Comment by Dzi4d3k** [comment]
Well, in this case it could be alleviated with appropriate readme warning, but it will be not stupidity safe, and most of user don't read before issues arise.

**Comment by joskuijpers** [comment]
I am actually just writing a fix 😉
