### ISSUE TITLE
Skip night

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#203]
Make it possible to skip to the next morning. Possibly by increasing game speed until few minutes before midnight, slowing down for all updates, then increasing speed after all updates have been done. Automatic stop at the start of day when it shuold be time to wake up and do some farming :)

**Comment by joskuijpers** [comment]
Hmm... this would be a separate class. Then with some event that says: go to next morning (X time).
The update method should then calculate the current minute himself (minute and hour listeners do not work).
Would also need some way to prevent interaction until complete.

**Comment by Gonimy-Vetrom** [comment]
Can do both in the ETS? A black screen and an inscription: "A farmer in a dream sees how the harvest is growing". :)

**Comment by Dzi4d3k** [comment]
Well, I would suggest to, if you decide to include such function, to make it switchable, as there be some who want to do night jobs

**Comment by Gonimy-Vetrom** [comment]
In manual mode

**Comment by reallogger** [comment]
Yes it should be voluntarily to when and if you want to go to bed. :)

**Comment by Gonimy-Vetrom** [comment]
Or as in the mod "FS15_Real_life". There you need to go into the trigger "Home" to rewind the night.

**Comment by Dzi4d3k** [comment]
@Gonimy-Vetrom 
Nice idea, but could be problematic on MP game with more than one player. Probably limited to administrators, yet how about more than one administrator?

**Comment by Gonimy-Vetrom** [comment]
After my post began to look for this mod. Also has found. The problem for the MP is solved. http://www.blackpanthergroup.de/forum/viewtopic.php?f=26&t=610
