### ISSUE TITLE
changed CZ translate

### ISSUE THREAD

**Issue by DrewCZ** [RealismusModding/FS17_seasons#206]
I was pollish CZ translate file to make better sense. Also few missing translations added.
Sorry, but I was unable to upload xml and zip file. Please remove '.txt' to restore xml.
bye, Dr.CZ
[translation_cz.xml.txt](https://github.com/RealismusModding/FS17_seasons/files/877181/translation_cz.xml.txt)

**Comment by joskuijpers** [comment]
Done, thank you!

**Comment by DrewCZ** [comment]
Hello, I'm glad to little help with this amazing mod :)
Dr.Cz
______________________________________________________________
> Od: Jos Kuijpers <notifications@github.com>
> Komu: RealismusModding/FS17_seasons <FS17_seasons@noreply.github.com>
> Datum: 28.03.2017 23:58
> Předmět: Re: [RealismusModding/FS17_seasons] changed CZ translate (#206)
>
Done, thank you!
