### ISSUE TITLE
Make the nights darker, generally

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#208]
Someone have me the suggestion to darken our nights (other darker-night mods don't work with seasons). It might be a good option for more realism, so that you can't realistically play at night. (Is this already the case?)
We will need to change the values in ssEnvironment (or move those daylight function to ssDaylight).

I wonder if this is really something we want, and then i need to figure out what values to  use.

**Comment by Mike3650** [comment]
Well when I played Coldborough Park Farm the nights are plenty dark enough. The only exception to this is when it rains! As in here - https://github.com/RealismusModding/FS17_seasons/issues/190

Compare the picture in that issue to these:
https://gallery.fs-uk.com/175941_17_12_16_9_30_39_2.png
https://gallery.fs-uk.com/175941_17_12_16_9_30_40_3.png

How does Seasons weather system work with what has been set-up by a map makers map01_environment.xml, does it override it?

**Comment by joskuijpers** [comment]
Yes we fully override the environment. There is an open issue for v2 to see if we can sometimes try to use their values. Could see if I can move it to v1: then the map will decide.
We can only use the map values if they did not change the amount of entries in the curves and the times.

**Comment by bnjgray87** [comment]
Hi guys, just came across this error and wondered if I have a problem

> dataS2/character/player/player01.i3d (219.64) ms
Error: Running LUA method 'update'.
C:/Users/ben/Documents/My Games/FarmingSimulator2017/mods/zzz_FS17seasons/src/environment/ssEnvironment.lua:121: attempt to call method 'seasonChanged' (a nil value)
[Seasons] ssGrowthManager: First time growth reset - this will only happen once in a new savegame

**Comment by joskuijpers** [comment]
@bnjgray87 please make a new issue, then we will look at it

**Comment by joskuijpers** [comment]
Possibly done in the new daylight system

**Comment by joskuijpers** [comment]
Not done in new system: needs more testing
Possibly not an issue. Moved to v2

**Comment by joskuijpers** [comment]
This is done with the new daylight data
