### ISSUE TITLE
ssEnvironment.lua:121

### ISSUE THREAD

**Issue by bnjgray87** [RealismusModding/FS17_seasons#209]
Upon testing my map after adding the snowmask, a new error has appeared. 
`Error: Running LUA method 'update'.
C:/Users/ben/Documents/My Games/FarmingSimulator2017/mods/zzz_FS17seasons/src/environment/ssEnvironment.lua:121: attempt to call method 'seasonChanged' (a nil value)
[Seasons] ssGrowthManager: First time growth reset - this will only happen once in a new savegame`

**Comment by joskuijpers** [comment]
Did you use the latest version of the mod? Because line 121 is empty currently

**Comment by bnjgray87** [comment]
Ah I was a few days behind, sorry about that. The issue has now been removed.
