### ISSUE TITLE
Unable to repair combine

### ISSUE THREAD

**Issue by bnjgray87** [RealismusModding/FS17_seasons#213]
FS17_Claas_Lexion_700_Stage_IV.zip    It has been cutting out and states it needs maintenance but the only option we get on the server is to configure it.

**Comment by joskuijpers** [comment]
Hi,

Have you tried going to the shop and pressing Alt+R when near the machine?

**Comment by bnjgray87** [comment]
Have indeed bud, the only option thats presented to us is 'customise' . Ive tried resetting the combine also but this does not fix the issue.

**Comment by joskuijpers** [comment]
Yea but you should not be activating the shop.
Instead, in your menu a new option should show up with the default keys `Alt+R`.

**Comment by bnjgray87** [comment]
I know, that doesnt appear, only the option to customise, I dont actually enter the shop. I press alt + r and nothing appears but occasionally 'r' will but that will be to customise. The rest of the fleet works when we enter the trigger box , the combine being the exception.

**Comment by joskuijpers** [comment]
Alright do you have a link to the mod for download?

**Comment by bnjgray87** [comment]
https://www.modhoster.com/mods/claas-lexion-700-stage-iv-pack

**Comment by joskuijpers** [comment]
can you also send me your vehicles.xml?

**Comment by bnjgray87** [comment]
https://www.dropbox.com/s/xkkgl33xo2ojhc8/vehicles.xml?dl=0

**Comment by joskuijpers** [comment]
Thanks. one more thing, what is the current day in your game? careerSavegame.xml, environment -> currentDay

**Comment by bnjgray87** [comment]
`      <dayTime>768.553467</dayTime>
        <timeSinceLastRain>4539.748047</timeSinceLastRain>
        <currentDay>88</currentDay>
        <realHourTimer>1939026</realHourTimer>`

**Comment by joskuijpers** [comment]
I tried it in my game and it does not say it needs maintenance. Can yous end me a screenshot when you are in the machine?
Also, send me a zip of your whole savegame.

**Comment by joskuijpers** [comment]
How long are your seasons?

**Comment by bnjgray87** [comment]
![ss 2017-03-30 at 03 51 16](https://cloud.githubusercontent.com/assets/25926406/24510374/ef556d58-1560-11e7-91e1-76333b51e350.png)
3 days currently. 
https://www.dropbox.com/s/byursj4olcqy2vb/savegame1.zip?dl=0

**Comment by reallogger** [comment]
This is on your dedi server right? Can you send me the current modlist? PM on fsuk is fine. Or contact us on slack.

**Comment by bnjgray87** [comment]
Update: After selling the combine and purchasing it again, I was able to repair it. Its worth noting that I have removed the combine add-on mod. I will update if the issue re-appears come next required maintenance.

**Comment by reallogger** [comment]
I am using the combine add-on also, but have not experienced any conflict with it in SP. Let us know how it goes when you are going to maintain it the next time.

**Comment by bnjgray87** [comment]
What I'll do is see if I can go another season and repair (without add-on) then add the combine mod again to the server to see if there's a conflict.

**Comment by joskuijpers** [comment]
Possible MP issue. Will review. If I can't find anything I'll close this. Won't be able to reproduce.

**Comment by joskuijpers** [comment]
Can't find any issue. I will increase the repair distance. Remember to go close the the machine to repair it.
