### ISSUE TITLE
Missing mipmaps for replacementTextures

### ISSUE THREAD

**Issue by baleBaron** [RealismusModding/FS17_seasons#216]
Spring textures are missing mipmaps making them look weird and grainy at distance.
This is true for some of the autumn textures as well. 

Another issue with all these replacement textures is they disappear when rendered at distance, this is not true for the default textures from GIANTS.
Since foliage textures are alpha-masked when rendered, mipmaps will require appropriate parameters when generated to get the best result.

I experimented using paint.net and generating mipmaps with "Error metric" set to "Uniform", "Weight Color By Alpha" ticked and the textures are looking much sharper and clearer even at distance.

**Comment by joskuijpers** [comment]
Fixed by @reallogger
