### ISSUE TITLE
Harvesting in autumn is almost impossible

### ISSUE THREAD

**Issue by TyKonKet** [RealismusModding/FS17_seasons#221]
Harvesting in autumn is almost impossible because after the first rain (and autumn is very rainy) the temperatures are too low (at least I think) and the crops never dry more.

**Comment by baleBaron** [comment]
#185 Tried to improve this, but yes I'm with you that it may still need to be adjusted.

**Comment by reallogger** [comment]
Latest commit should make it easier for shorter seasons especially. Guess you were playing with 3 day seasons.

**Comment by TyKonKet** [comment]
I'm playing with 12 days seasons but the problem exists anyway because, obviously, most of them are rainy or cloudy.
I think one good solution would be to make drying faster.

**Comment by reallogger** [comment]
Was thinking after I committed that "hope they are not playing with 12 day seasons" because then the change actually makes it even harder :) Will make another change.

**Comment by reallogger** [comment]
Then I suggest you disable teh crop moisture feature by using the ingame menu

**Comment by TyKonKet** [comment]
I tried even this but... #220 😄

**Comment by reallogger** [comment]
Should be better now with latest commit. Alternative if you want a dryer climate is also to reduce probability for rain in the autumn by reducing 0.5 to a lower number here: 
https://github.com/RealismusModding/FS17_seasons/blob/1a2d4904544328a65d72a5c2aa145c345a4f84dd/data/weather.xml#L84
A typical UK climate was modelled.

**Comment by reallogger** [comment]
Let me know how it works with a 12 day season. baleBaron has tested with 3 day season and it works well now.

**Comment by joskuijpers** [comment]
@TyKonKet have you tried it?

**Comment by TyKonKet** [comment]
Now it works better, and the "disable moisture" option works even in mp.

**Comment by theSeb1979** [comment]
Looks like this can be closed now. If not, then reopen.
