### ISSUE TITLE
Attempt to make the engine think we referenced the replacement i3d

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#222]
DediServers give a warning that there are too many 'store files'. We think this is 'unreferenced files'. Giants thinks that in general, mods with many of those files are bad...
Now, Seasons is so advanced that even the engine can't follow what we are doing. But getting rid of the warning might be a nice thing.

**Comment by baleBaron** [comment]
"The reason, namly the thresholds for certain file types arise from the count of files (and file types) in the default mod maps.
If there are files inside the map which are not normally used (png, jpeg, txt, ...) we can assume that the modder did not exactly know what he was doing.
I know that this is not always true, but in general it is ;) " - GIANTS Software

**Comment by joskuijpers** [comment]
Yeah they can't handle our advanced-ness

**Comment by joskuijpers** [comment]
Thinking of the following solution:

Create a store item with the i3d so it is referenced. The replacement textures is the most important one.
Use `StoreItemsUtil.removeStoreItem()` to remove the store item at load so it is never used

**Comment by joskuijpers** [comment]
Done :)
