### ISSUE TITLE
[visual] Time management

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#23]
Hi,

I am working on the Time class, that will update the day/night cycle according to the time of the year.
In winter there will be longer nights, and in summer longer days.

Will see if I can actually change the settings and make it have effect.

**Comment by theSeb1979** [comment]
One little comment. I got a pm from reallogger on this topic 

> I see you are considering to have longer nights in winter than in summer. Using longitude as input I can supply you will a simple function that determines the sunrise and sunset. This would enable players to have customary settings. Longer days in the north in summer and so on. 

I think that would be very interesting to see. But hopefully we can manipulate the day night cycle before getting too excited.

**Comment by joskuijpers** [comment]
Yeah not having much success currently…..

**Comment by joskuijpers** [comment]
Troubles.

I managed to change when the reddish sky starts and ends, but the actual lighting hasn’t changed :(
Maybe need something with sunColorCurve, skyCurve

**Comment by joskuijpers** [comment]
Oh my, I have tried so much :(

skyCurve: position of the sky texture
sunColorCurve: no clue on its effects.
ambientCurve: color of the ambient light, but turning it all to 0 (black) doesnt make the game black
sunRotCurve: rotation of sun/moon for shadows
nightStart / nightEnd: seems to be the logical night, used for the streetlights
skyDayTimeStart / skyDayTimeEnd: I thought it was for the reddish in the sky, it isn't.

**Comment by joskuijpers** [comment]
Okay, I made it eternal light (on the ground) using the sunColorCurve.

What we need to do is adjust all the curves to the input we give (mostly start of night - end of night).
I think it is a bezier...

**Comment by joskuijpers** [comment]
![20161108215651_1](https://cloud.githubusercontent.com/assets/5017040/20116957/a8119b28-a5fe-11e6-85be-1605307b1361.jpg)
Ambient all the way up (1,1,1)


![20161108215810_1](https://cloud.githubusercontent.com/assets/5017040/20116963/ae3c4aac-a5fe-11e6-83e6-e3ae7e032beb.jpg)
Ambient all the way down (0,0,0)

**Comment by ian898** [comment]
Your making good progress with this I only went to make misses a cuppa come back and you have kinda fixed the issues you were having haha

**Comment by joskuijpers** [comment]
No, it still doesn’t work :P

**Comment by joskuijpers** [comment]
![image](https://cloud.githubusercontent.com/assets/5017040/20118097/9097a9ce-a603-11e6-925a-52cf15732eee.png)
This are the default values of the 4 curves. Now, we need to think of an algorithm that can correctly transform the curve to change the length of the night.

Go!

**Comment by ian898** [comment]
Did you get them from the enviroment.xml that I was about to mention haha

**Comment by ian898** [comment]
have a look at the map01_enviroment.xml in were default maps are located I just had a look at it my self and in there it looks like you can disable rain and all sorts

**Comment by joskuijpers** [comment]
Yeah that is the data I have been typing in my sheet :P

Thing is, we need to adjust it dynamically because every day can be different.
So I need a function, that for:
(frame-1, frame, frame+1) and a wideningOfNight parameter can give me a newFrame.

**Comment by ian898** [comment]
I understand we could prob use a random function in there some were as well to give it a bit of a variety.

**Comment by joskuijpers** [comment]
Nah not random. Just a curve for winter-summer.

**Comment by ian898** [comment]
expanding to fast the possibilities its hard to keep on track haha, It will be just a matter of tweaking and testing I guess until we get something we are happy with.

**Comment by joskuijpers** [comment]
But seriously though, I don’t have such algorithm (yet)… I need to design one, and it is complicated. It also has to be fast…

**Comment by joskuijpers** [comment]
I have an idea, but it will probably only reliably work on maps with the default environment.

Instead of doing difficult, I could try to ‘detect’ the period between the end of the morning and begin of the evening (this is often a gap of 8+ hours).
Then the rest is the night.
Now, I can expand or compress the night. So if the night spans 16 hours (this includes a couple of hours going to dark/from dark), and it is winter, I could expand this to 20 hours by doing some multiplication magic on the timestamps of all the keyframes.

It is not perfect, but it might work.

**Comment by reallogger** [comment]
I can supply a simple function that determines the number of hours with daylight for you. Does it need to be exact hours in the end? Can decimal hours, or hours and minutes be used as input?

Suggest that one variable can be read from a xml file (maybe there are other input the user of the mod can change by editing a simple file in the savegame folder?? Like drivecontrol). This variable can be longitude so users can get the daylight of their own location. Here we can use whole degrees of latitude. 

For interested readers  this is the model that will be used (however I will simplify it):
https://www.ikhebeenvraag.be/mediastorage/FSDocument/171/Forsythe+-+A+model+comparison+for+daylength+as+a+function+of+latitude+and+day+of+year+-+1995.pdf

**Comment by joskuijpers** [comment]
If I can give you the day of the year (1-356) and longitude, and you can give me the start of the day and the end of the day, I can work with that.
I need to know whether 'start of day' is when it begins to get lighter of when it is almost totally light though.
Ill have to see what I would prefer.

**Comment by joskuijpers** [comment]
I can use decimal hours, btw. But I really want to know when the day starts as well. If you don't have such data I could just put it at 12AM center:
7 hours daylight = 12-(7/2)= 8:30 - 15:30 (this already seems wrong because in winter it might get light at 8:30 but it wont get dark till 4 or 4:30)

**Comment by reallogger** [comment]
I can give you whatever you want :)

On a more serious note: Start of the day and end of the day is fine. It would be nice if you can just check whether start of the day refers to early dusk or daylight. And I will adjust accordingly.

**Comment by joskuijpers** [comment]
@reallogger easiest, I think, would be at full daylight.
Current values see full daylight between 9AM and 5PM. I can then compress/extend that area (the night, 17-9).
However, the current code also has 'full night darkness' at 10PM, until 4:30AM

What do you think is best?

**Comment by reallogger** [comment]
So it is possible to supply four values? 
1. End of full darkness
2. Start of full daylight
3. End of full daylight
4. Start of full darkness

**Comment by joskuijpers** [comment]
No :p, well yes you can but I wont only use one pair, not sure which one yet.

**Comment by reallogger** [comment]
To me it does not matter. Full daylight is not a common term, but we could assume it occurs abt 1 hour after sunrise. If you worked with both pairs you could achieve longer dawns and dusks during winter. It is basically the same equations, only changing one constant.

**Comment by reallogger** [comment]
Here is a python code that should do the trick. Both pairs are included, but up to you on what to include. 

    # calculating sunrise and sunset from latitude and Julian day
    # reallogger
    # 2016 11 09
    
    import math
    
    def day(p,L_rad,eta,J):
    	gamma = (math.sin(p)+math.sin(L_rad)*math.sin(eta))/(math.cos(L_rad)*math.cos(eta))
    
    	#to account for polar day and polar night
    	if gamma < -1:
    		D = 0
    	elif gamma > 1:
    		D = 24
    	else:
    		D = 24-24/math.pi*math.acos(gamma)
    		
    	#daylight saving between 1 April and 31 October as an approximation	
    	if J < 91 or J > 304: 
    		time_start = 12-D/2
    		time_end = 12+D/2
    	elif (J >= 91 and J <= 304) and (gamma < -1 or gamma > 1):
    		time_start = 12-D/2
    		time_end = 12+D/2
    	else:
    		time_start = 12-D/2+1
    		time_end = 12+D/2+1
    	
    	return (time_start,time_end)
    
    J = 1		#Julian day
    L = 51.5	#Latitude
    L_rad = L*math.pi/180
    p_night = 6*math.pi/180 #suns inclination below the horizon for 'civil twilight'
    p_day = -1*math.pi/180 #suns inclination above the horizon for "daylight" assumed to be one degree above horizon
    
    theta = 0.216+2*math.atan(0.967*math.tan(0.0086*(J-186)))
    eta = math.asin(0.4*math.cos(theta))
    
    #setting time for daylight
    [time_startday,time_endday] = day(p_day,L_rad,eta,J)
    
    #setting time for full darkness
    [time_endnight,time_startnight] = day(p_night,L_rad,eta,J)

**Comment by joskuijpers** [comment]
Wow, this actually seems to work. Awesome!!

I’ll convert this to LUA later tonight, and work on the (de)compression of keyframes. If I then put it together, it _should_ work.

**Comment by joskuijpers** [comment]
Okayyyy an update.

It works. Kinda. I have tested the middle of summer, and the day is very very long :P
So calculating the begin and end time of a day using the above algorithm works.
Determining the split between morning and evening works
And compression works.

2 issues I have found so far:
- shadows do weird
- In high summer, the compression of the evening towards the night is dramatic (because an effect of 7 hours i compressed into 3 hours). So the red-sky stuff animates WAY too fast. At least, at 2400x speed.

So that is it. I’ll commit.

**Comment by joskuijpers** [comment]
I don’t think I can easily fix 2 though… it requires a change on how I transform the animations. I compress towards 12AM because that is where the animation begins and ends. I would need to move keyframes around… (can be done, is harder).

**Comment by joskuijpers** [comment]
Another problem, the winter mornings are too light :( The evening seems to work though.
Also some glitches...

So yeah, unfinished.

You can try it out yourself. You could also change line 67 in time.lua to use 15 (midsummer), 35 (midwinter) instead of the currentDayNumber.

**Comment by joskuijpers** [comment]
Okay, and I know how (I think) to fix the winter too-light problem. (And I 'fixed' the shadows by disabling scaling of the suns rotation, it is incorrect.)

I need to look at when full night appears (with the algorithm) and when night starts to end (same algorithm). Then I need to look at the length of the transition.
After that I need to find 2 more pivots in the keyframes so I can compress them, and make the length of the transition longer and shorter.

Another day.

**Comment by reallogger** [comment]
Good work Jos! 

If the transition to day and night occurs too quickly you can also try to change the "-1" when setting self.pDay in line 20. Having a lower number (like "-6") will extend the dawn and dusk. I was unsure what to use there as there is little info on what the inclination of the sun needs to be before there is full daylight. The "6" for self.pnight should be correct though. 

Another issue is in the period 1 April to 31 October there is Daylight Saving Time and the highest inclination of the sun occurs at 1 PM. Maybe this does not matter for the mod. 

When it comes to scaling of the suns rotation there might also be good info in seriousmods Realdaylightmod. 

I'll test later tonight.

**Comment by joskuijpers** [comment]
Posted update on the forums: http://fs-uk.com/forum/index.php?topic=187664.msg1245365#msg1245365

**Comment by reallogger** [comment]
Tested it now. There is something strange that happens at around 2200 and 0400 for both day 15 and 35 (and something at 0230 for day 15). And it seems that the sunrise is too early in the morning. How does these day numbers relate to Julian days?

**Comment by joskuijpers** [comment]
First season is spring, each season is 10 days now, so 15 is half of second season is mid summer. Thus half july.
35 is mid winter is thus 15 january.

Most strangeness is with the shadows: they are not scaled because they break when I do.
