### ISSUE TITLE
Trains do not start

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#231]
"I think there is a problem with the trains. I cannot get them to start or even move them if I have seasons activated, but I can get them to start just fine without seasons activated. I noticed this problem first with Germantown where I tried to start the trains with and without seasons. Then I replicated the problem successfully on GCV to double check myself." -- Leifege640

**Comment by joskuijpers** [comment]
Tried using, in motorFailure:
```lua
self.startMotor = SpecializationUtil.callSpecializationsFunction("ssStartMotor")
    self.stopMotor = SpecializationUtil.callSpecializationsFunction("ssStopMotor")
```
instead of the Motorized setters. Trains start, motor failure works, but unknown if now the problem with the lights does not occur.

**Comment by joskuijpers** [comment]
With help from Giants, this issue has been solved.

**Comment by laloe34** [comment]
What do you have to do to make the train work?

**Comment by joskuijpers** [comment]
Update to the latest version...

**Comment by laloe34** [comment]
Or thank you very much

**Comment by laloe34** [comment]
Hi, I do not want to update the file when I replace the files. The mod no longer appears the same way thanks for everything.

**Comment by joskuijpers** [comment]
@laloe34 Sorry but I don't understand what you are trying to say.

If you can't figure out how to install this mod, please wait until we release.

**Comment by laloe34** [comment]
![inkedfsscreen_2017_04_20_15_03_22_li](https://cloud.githubusercontent.com/assets/27028856/25250341/d51b576a-25da-11e7-9880-5f5c9558acc4.jpg)
