### ISSUE TITLE
Translation ready

### ISSUE THREAD

**Issue by Dzi4d3k** [RealismusModding/FS17_seasons#24]
Hi guys,

I know that you are working hard and this is very alpha progress but how about making it translation ready from beginning instead of hardcoding text.
I realize that this is low priority as English is wide know, but I just want to trow idea.

**Comment by theSeb1979** [comment]
Hello dzi212@£!@$%, I was actually about to add localisation as a feature. I do see it as low priority. Since we are being "agile" we want the code to the main functionality to be working before worrying about localisation, which we can do when we are refactoring the code.

**Comment by joskuijpers** [comment]
Sure, we will look into it :)

**Comment by Dzi4d3k** [comment]
Hi
I'm finding last text update little ambiguous:
"The soil is too hard to work on it!"
I know what is the purpose of it, but for not familiar players it would rise question: why? from what?
If it is desired to stop field works in winter, then I would suggest message like:
"The soil is frozen. You can't work on it!"
This may temperatures displayed, as them should be negative at least at nights, to make such message realistic.
Just an idea.

**Comment by joskuijpers** [comment]
Oh that is a good one! Haven't put too much energy into finding a good text :)
Currently we disallow it the whole winter, but we may look into changing it into negative temperatures only. Will see.

Feel free to update the files :)
