### ISSUE TITLE
Nil reference in ReplaceVisuals on foliage replacement

### ISSUE THREAD

**Issue by Hanksabutt** [RealismusModding/FS17_seasons#241]
Whenever the mod is installed and i join in, if i click w, i go forward and dont stop, or s, buttons like alt open the weather thing, i cant click esc, its very odd and i spent alll of today looking through my mods and noticed the mods werent affecting it, everytime i deleted this mod it stopped, but before the last 2 updates,  it was fine. Im confused.

I checked the log and this was spammed for lines and lines.

Error: Running LUA method 'update'.
C:/Users/Henry/Documents/My Games/FarmingSimulator2017/mods/FS17seasonsmaster/src/environment/ssReplaceVisual.lua:173: attempt to index a nil value

**Comment by joskuijpers** [comment]
What map are you using?

**Comment by Hanksabutt** [comment]
Its any map

**Comment by joskuijpers** [comment]
Any other mods you have loaded?

**Comment by Hanksabutt** [comment]
I have alot of mods, i spent a whole day putting some in to see what would happen with seasons, id put in 20, and noticed the issue would happen, got rid of them and it went away, but when i put those same mods back in 4 at a time, the problem was gone, even with the mods that were causing it.

**Comment by joskuijpers** [comment]
Not a bug.

Do not lot multiple mod maps. Only load the mod map that you are playing on.
