### ISSUE TITLE
Create hints

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [RealismusModding/FS17_seasons#243]
Your mod changes many of the game's functions. It would be helpful to create hints that were loaded before the game started. http://prntscr.com/ev9bqq

**Comment by joskuijpers** [comment]
Sadly we can't do this :( Our mod gets loaded after those texts are.
If we could change anything before that screen we would have some awesome things like choosing number of days or environment before creating the savegame.

**Comment by Gonimy-Vetrom** [comment]
I already saw this on one map.

**Comment by joskuijpers** [comment]
Yes, the engine loads the items from the Map modDesc.xml. That is before code is loaded. There are special xml tags for that.

**Comment by Gonimy-Vetrom** [comment]
So this should be make by the map-maker?

**Comment by joskuijpers** [comment]
Yeah

**Comment by Gonimy-Vetrom** [comment]
Can I make a blank for the map makers?
For a basis to take the information from README.

**Comment by joskuijpers** [comment]
Sure. But remember that maps can still load without Seasons
