### ISSUE TITLE
Prepare for v1 release

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#245]
- [x] Finalise naming

- [x] Double check birth rates - Reproduction rate with 285 sheep is 30 min. In a 3 day season that is 150 more animals which does seem a little bit high.

- [x] Remove support for the old snowmask SeasonsSnowMask

- [x] Change ssEnvironment lines 63 and 75
.environment.latestGrowthStage --> .environment.latestTransition

- [x]  Similar change in GM lines  - lines 38 and 56 - .growthManager.currentGrowthTransitionPeriod --> .growthManager.currentTransition (no longer relevant thanks to refactor to use density scanner parameter)

**Comment by joskuijpers** [comment]
- [ ] Remove support for the old snowmask SeasonsSnowMask

**Comment by joskuijpers** [comment]
What is the `finalize naming` about?

**Comment by joskuijpers** [comment]
Name of the mod for contest: `FS17Contest_Seasons`
Name of the mod after the contest: `FS17_RM_S0_Seasons`
Or lowercase S?

Also, what impact does this have on updating? Haven't got a clear answer about that.

**Comment by Gonimy-Vetrom** [comment]
The mod will have a name FS17Contest_Seasons.zip, after FS17_RM_S0_Seasons.zip? This will create difficulties. The name of the mod is stored in the list of necessary mods for the saved game. If the name is different, then it does not load. Will need to edit the careerSavegame.xml file.

**Comment by joskuijpers** [comment]
We know this.
You can actually just click OK and then re-select Seasons.

But we can't keep carrying the Contest name for 2 years, that is just nasty.

**Comment by Dzi4d3k** [comment]
Is it the "Contest" word required really?

**Comment by joskuijpers** [comment]
I sent Giants a message to see if we can get rid of it.

**Comment by Gonimy-Vetrom** [comment]
Now I understand. This is the condition of the contest Giants.

**Comment by joskuijpers** [comment]
Nope. We have to use FS17Contest_.

**Comment by joskuijpers** [comment]
And we also don't want to keep that name for 2 years. So we will use `FS17_RM_S0_Seasons` for 1.1. People will have to re-select the mod, I guess.
