### ISSUE TITLE
Additional crops not shown on GUI overview

### ISSUE THREAD

**Issue by TyKonKet** [RealismusModding/FS17_seasons#247]
![](https://puu.sh/vjgU5/c281b4dbc3.png)

**Comment by theSeb1979** [comment]
data for gui is only built during at loadMap. additional fruits are found after that. I forgot to update the data for the gui after new fruits are found.

**Comment by fcelsa** [comment]
I'm testing with TyKonKet, no errors in log file, maybe need a manual configuration in growth.xml ?

**Comment by theSeb1979** [comment]
There is no need for extra data in growth.xml for extra fruits, as long as they are correctly implemented in the map. Can you share the map with me? Come chat to me on slack so we can figure this out

**Comment by TyKonKet** [comment]
I'm coming!

**Comment by fcelsa** [comment]
A new savegame start on the same map in single mode it's ok, though with this info in log:

[Seasons] Fruit not found in default table: oat
[Seasons] Fruit not found in default table: rye
[Seasons] Fruit not found in default table: spelt
[Seasons] Fruit not found in default table: triticale
[Seasons] Fruit not found in default table: millet
[Seasons] [ssDensityMapScanner] Dequed job: ssReduceStrawHay ( 1 )

![fsscreen_2017_04_14_00_11_21](https://cloud.githubusercontent.com/assets/4340190/25026895/412132b8-20a9-11e7-91bd-6531e2990725.png)

**Comment by theSeb1979** [comment]
The log messages are ok. It's just the growth manager saying that it found new fruits.

**Comment by theSeb1979** [comment]
Issue analysed and reproduced. additional fruits will not show in the GUI correctly if a save game is loaded, until the next growth transition. Works fine on a new save game because the code looks for additional fruits on the reset growth transition. This does not happen if you reload a game until the next transition.
