### ISSUE TITLE
Make blank snowmask

### ISSUE THREAD

**Issue by Dzi4d3k** [RealismusModding/FS17_seasons#251]
TODO :)

**Comment by Dzi4d3k** [comment]
Done by @baleBaron on Slack:
https://files.slack.com/files-pri/T30U06SU8-F4ZVB7G3F/download/seasonssnowmask_density.gdm

**Comment by joskuijpers** [comment]
What is the difference between grle and gdm?

**Comment by Gonimy-Vetrom** [comment]
For the user it does not matter. If the file .png then after saving, the editor sets the resolution itself.
.gdm it is new format for FS17.

**Comment by joskuijpers** [comment]
Done. Replace the grle with a gdm

**Comment by Dzi4d3k** [comment]
Problem was not that it was grle not gdm, but that grle was not balnk.

**Comment by Gonimy-Vetrom** [comment]
https://drive.google.com/file/d/0B_zrlMUSl3roRUhJUGlPSUdnX1k/view?usp=sharing
Please add these files to the modders.
Clean. 
Different sizes. 
Extension .png

**Comment by theSeb1979** [comment]
I don't really understand this issue but will discuss the team

**Comment by joskuijpers** [comment]
I am pretty sure this will confuse more than it will explain. Map makers who make 4x, 8x or 16x maps already need to scale their files.
Additonally, they should scale up their tipcol, paint it, and copy that for a snow mask.
