### ISSUE TITLE
No show "Snow Tracks"

### ISSUE THREAD

**Issue by Vanquish081** [RealismusModding/FS17_seasons#256]
If I select Snow Tracks, no show tracks on the floor, test in Goldcrest Valley (original).

**Comment by reallogger** [comment]
If you're playing without snow mask, the snow depth is limited to one layer and then there will be no snow tracks. Closing comment. Reopen if you are playing with snow mask and have tested in deep snow.

**Comment by Vanquish081** [comment]
Ok, I checked, compacted the floor, yes, but I expected to see the marks of the wheels xD

**Comment by Anonymous-any** [comment]
Hi there yes! I try to see that me too is this option true don't must add wheels tracks on snow?

**Comment by joskuijpers** [comment]
Snow tracks only happen when snow depth is more than 1 layer

**Comment by Anonymous-any** [comment]
I have put snow mask does that mean The seasons do all what it must do for show that or is there another installation to do the job?

**Comment by Anonymous-any** [comment]
Ok understand now after more than 1 ssAddSnow command :)
Do you thing it's not possible to add (added to compression track) default track on snow?
Br
