### ISSUE TITLE
[GM] - Modify growth cycle duration for each crop to correspond with a season

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#26]
Analysis Thread:

https://github.com/theSeb1979/FS17_seasons/issues/3

**Comment by theSeb1979** [comment]
Implement xml configuration file to make season length customisable by the user 

- related to Add Settings class

https://github.com/theSeb1979/FS17_seasons/issues/25

**Comment by theSeb1979** [comment]
> Further thoughts on this. The simplest implementation and what has currently been started assumes that a season is x days (configurable) and then the growth cycles durations need to be adjusted to correspond with the season when the mod loads. Once the growth duration is set, the mod will not try to manipulate the growth in real time, apart from maybe withering crops in the winter that have not been harvested and were not planted in the autumn.

So I sat down to start prototyping this and quickly realised that the "simplest" is actually not that simple and requires rethought, because it is fraught with issues. If we were to simply change growth times so that a crop planted in autumn will be ready in summer,  then there is going to be the issue of when it was planted in the autumn. For example, I don't see how you could decouple such an algorithm from the day in the season that it was planted. So, if we plant on day 2 of autumn, then it will be ready around day 2 of summer. But if we plant on day 9 of autumn, then it will only be ready on day 9 of summer. I don't think that is a good solution. 

Therefore I think we need to go back to the other implementation idea of actually trying to actively control the growth as the seasons move and tie the crops into the season. I have no idea how to do that right now. I am guessing that we would need to recognise all fields, then all of the crops and see if it's possible to alter the growth stage as we see fit based on the season.  What was that mod that would show you the status of all fields in FS13/FS15? Field status or something? That could be a starting point to see how to get field and crop data that is currently in the map.

**Comment by joskuijpers** [comment]
Personally I think the problem you cite is not really a problem at all.

For one, you can change the speed of the game. You can harvest a lot in 24 hour game time playing on 1x.
So if you plant on day 1 and day 5 you get it on day 1 and day 5.

I know, it isn't really realistic, but it also is.. if you plant a batch in real life a month before another batch, it is finished earlier. If it need 9 months to grow (hehe a baby), and you are a month late with planting, well tough luck you will need to harvest in late autumn/early winter.

It is much easier I think.

**Comment by theSeb1979** [comment]
Hmmm.... all valid points and will make implementation a lot easier.

**Comment by reallogger** [comment]
I wonder if we can use timeSinceLastRain to add some variability with respect to harvesting crops. If we keep the growth duration constant (but different for each crop), would it be possible to implement a requirement that the timeSinceLastRain needs to be larger than a certain value before you are able to harvest? Simulating that the crop needs to dry before harvesting. Don't know enough about agriculture to know how universal this is though.  

This is related to #10 as well. MR had a crop damage if you harvested just after rain I remember.

**Comment by theSeb1979** [comment]
Implemented
