### ISSUE TITLE
Info animals

### ISSUE THREAD

**Issue by Vanquish081** [RealismusModding/FS17_seasons#260]
When animals die, you don't know which animals die:

![Example](http://i.imgur.com/58pmSUW.jpg)

If the animals are dead, you still pay for the maintenance:

![Example](http://i.imgur.com/IDUNT2x.jpg)

**Comment by Gonimy-Vetrom** [comment]
This is a payment to the veterinary service for the disposal of a dead animal. :(  maybe

**Comment by joskuijpers** [comment]
We cant fix the paying issue. See it as a price for getting rid of the dead animal indeed.
We decided to not show which animals died because it takes many translations :P Keep an eye on your statistics.

**Comment by Vanquish081** [comment]
many translations... bah... is new mod, need translation xD when this more worked, will not need so many translations.
