### ISSUE TITLE
no income from placeable buildings with seasons mod

### ISSUE THREAD

**Issue by smas01** [RealismusModding/FS17_seasons#261]
While playing on Sandy Bay with seasons mod I discovered that i didn't get any income from my wind turbines. I was able to replicate this issue on Goldcrest Valley  with only seasons mod and the Money Tool from ModHub enabled. When I disabled seasons mod in the GCV savegame, the money would come in as usual every ingame hour.

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/926335/log.txt)

**Comment by Vanquish081** [comment]
With snow you can't place placeable mods.

**Comment by joskuijpers** [comment]
> With snow you can't place placeable mods.
This is not a bug but a feature. You should first clear the area of snow

**Comment by Vanquish081** [comment]
I didn't mean to say it is a bug, just to inform.

**Comment by joskuijpers** [comment]
Bug confirmed

**Comment by joskuijpers** [comment]
Fixed
