### ISSUE TITLE
ssSwathManager - error if save during ssDensity scan and reload

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#265]
save when ssDensity is doing swath manager and reload

Error: Running LUA method 'update'.
C:/Users/SebastianP/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/misc/ssSwathManager.lua:57: attempt to perform arithmetic on local 'layers' (a nil value)

i had a similar problem with GM a while back and ended up saving a variable that I needed when the game would be reloaded and the density scan needed to finish

**Comment by joskuijpers** [comment]
This should be fixed now.

**Comment by theSeb1979** [comment]
fixed by 899e1f8
