### ISSUE TITLE
Stop snow from reducing every hour when there is no snow

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#267]
Currently, the hourly reduce snow keeps running, even in mid summer.

I suggest that there is a (saved) variable that is set to true when the -100 layers reduce is executed.
If the variable is true, no hourly reduces are done.
The variable is set back to false once the first snow is applied (first time targetSnowDepth > 0).

**Comment by mrbear** [comment]
That saved variable updateSnow  already Seams to be there. So if it's not working it must be a bug someware.

**Comment by joskuijpers** [comment]
I see the code, and indeed it should work.

Oh nvm, silly me. I thought it were snow events in the log, but they are straw/hay/growth events.
