### ISSUE TITLE
new version of snowmask

### ISSUE THREAD

**Issue by wieselflinked** [RealismusModding/FS17_seasons#281]
added the terrainlayer correctly. but the layer ssSnowMask seems to be invisible in the giants editor. (viewDistance="80")

when i try to add the "old" snowsystem(/SeasonsSnowMask_density.grle) , everything is fine. the terrainlayer appears like green straw :-)

can anybody help?

**Comment by wieselflinked** [comment]
found a wrong material-id in your wiki:

<FoliageSubLayer name="ssSnowMask"  densityMapChannelOffset="0" numDensityMapChannels="1" materialId="431" cellSize="8" viewDistance="80" objectMask="16711935" decalLayer="0" atlasSize="1" atlasOffsets="1 0" numBlocksPerUnitDefault="1.8" numBlocksPerUnitMin="1.8" numBlocksPerUnitMax="1.8" width="0.8" height="0.3" widthVariance="0.1" heightVariance="0.1" horizontalPositionVariance="0.3" blockShapeId="1"/>

materialId="421" => materialId="10610"

problem solved. bugfix by "DeutzFahrAustria"

**Comment by deutzfahraustria** [comment]
Yeah, I was wondering because the Material with the ID 100610  has not been used and deleted by the Giants Editor.

**Comment by joskuijpers** [comment]
Fixed this in the manual
