### ISSUE TITLE
Environment Error

### ISSUE THREAD

**Issue by Freppson** [RealismusModding/FS17_seasons#282]
There is a lua Error when u Delete it from a dedi server. It is something with the environment lua, 

Should i send a text of the error??

**Comment by bnjgray87** [comment]
Hi bud, delete the section <environment> </environment> and its content from your career save and it will resolve the issue

**Comment by theSeb1979** [comment]
No, do not delete the whole environment section. Just delete every line from rains where it says "snow". That is normally the problem. But it would be useful to see the log file @Freppson

**Comment by reallogger** [comment]
Can also just replace 'snow' with 'rain' in that section

**Comment by bnjgray87** [comment]
Well, this was my workaround when I deactivated seasons temporarily. I haven't ran into any issues myself, am I likely to now ?

**Comment by Freppson** [comment]
Thanks Guys, Awesome, shall be tested directly :D

**Comment by reallogger** [comment]
@bnjgray87 Issues might occur if you played past midnight and then saved without Seasons activated. Growth and weather are likely affected. To reset weather you should delete everything inside the `<forecast>` section and then load.
