### ISSUE TITLE
Errors if there are no animals on the map?

### ISSUE THREAD

**Issue by FoxJulian** [RealismusModding/FS17_seasons#286]
Hey guys,

first of all: Awesome job so far! I am really excited about that Season Mod, feeling a little bit enthusiastic like the time when more realistic mod was released for FS13 :)

Actually everything is working fine, there is just one thing. I am playing my own map, and as I am only working on the fields, i dont got any animals. Thats why i didnt even place animal husbandries on my map. I think (not sure) that the Season Mod causes issues if there are no animals. Every time a day ends and the season should jump further (like spring begining to mid spring) nothing happens. Wheather conditions change, but its still begining of spring (hope you understand what i mean). If i save the game then, and launch it again, season jumped further (so now its mid spring). You know what i mean?

There is one error in the log aswell, telling me something with the animals is going wrong.

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/950104/log.txt)

So maybe you got an idea if there is a way to solve my problem. If not, i am gonna place some animal husbandries on my map. Its not that difficult, but might be still interesting for you and your work.

Keep it real, and thanks a lot!

Julian

**Comment by joskuijpers** [comment]
Hi!

I just made an update to the code that should fix it. Please try again and let me know.

**Comment by FoxJulian** [comment]
Hey,

Jesus you were fast 👍 

Seems to work, no errors anymore. Thanks a lot!
