### ISSUE TITLE
Crop harvest and seeding times

### ISSUE THREAD

**Issue by FoxJulian** [RealismusModding/FS17_seasons#289]
Hey how,

I just looked around through a year with the season mod. In general I am pretty happy with it, but there are two things I dont like because they dont fit into the way of farming i am used to.

Dont know where you guys are from, but i guess its some northern areas? ;) I am from southern Germany, so i guess thats why i have some things that disturb me. First of all: We start harvesting winterbarley and wintercanola, sometimes even winterwheat, already in the middle of summer. With the season mod harvest only starts in the end of summer. Thats too late for me. Is there a way to change that? If you dont want to change it in general i can understand that, but maybe you could let me know how i can change it just for my own game.
Second is the way of seeding. Canola is seeded in the end of summer/beginning of fall. Barley comes next in beginning of fall, and after that we are used to seed wheat from middle of fall till end of fall. That works with the season mod, BUT: If I seed barley in the beginning of fall, it grows into stage 2 before winter already. So its pretty tall already and that looks a bit weird to me. So maybe there is a way so that crops can only go into winter in stage 1?

Its not really a bug, but something that disturbs myself a bit. 

Still love your work!

**Comment by joskuijpers** [comment]
You can make your own small mod that uses XML and a simple function (see the STMs) to overwrite the growth.xml file. Just copy our growth.xml, rename it to seasons_growth.xml and adjust it to your liking.

**Comment by FoxJulian** [comment]
I already had a look into the growth.xml. Can you tell me which values i have to change and adjust? I couldnt figure it out so far.

**Comment by joskuijpers** [comment]
I can't, but maybe @theSeb1979 can. We will probably write documentation on this, but it is quite complicated. Possibly too complicated to explain in a issue comment.

**Comment by theSeb1979** [comment]
Sorry, but I cannot explain this right now. You will have to wait until I get around to writing more documentation.Try to figure it out yourself by studying the growth.xml file. 

normalGrowth = increases growth by one during that transition and acts on that fruit (fruitName) and that growth state or between that growth state and max (if max is present)

extraGrowth = works much like the above, except that you can increment growth by more than one growth state by using extraGrowthFactor

setGrowth = allows you to set the state of a fruit to whatever you want based on setGrowth and SetGrowthMax
