### ISSUE TITLE
Verify soiltemp algorithm

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#292]
This just happened on my savegame:

The lowest air temp was -2 (midnight), and then the soiltemp jumped from -1 to -6

**Comment by joskuijpers** [comment]
In mid-sprint (3 day seasons) it jumped back from -4 to 5 overnight.

**Comment by reallogger** [comment]
Leave the issue open until the fix has been tested

**Comment by baleBaron** [comment]
Still bad, 3d season having -2 in mid spring, -1 in late spring and 0 in early summer. Air temps were normal.
