### ISSUE TITLE
Cleanup ssSnow

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#301]
could extract some common code into functions

like parts of `updatePlaceableOnCreation` and `updatePlaceablenOnDelete`

**Comment by joskuijpers** [comment]
Is there anything specific? Density maps dont lend themselves well to refactoring

**Comment by theSeb1979** [comment]
the only difference between the two functions mentioned above is the call to setDensityParallelogram (last parameter 1 or 0)

**Comment by joskuijpers** [comment]
Done
