### ISSUE TITLE
Temperature algorithm data

### ISSUE THREAD

**Issue by baleBaron** [RealismusModding/FS17_seasons#302]
Temperature algorithm is only using the period.mode data entry as input when calculating high and low temp.

period.min and period.max in weather.xml is never considered when calculating temperatures.

**Comment by joskuijpers** [comment]
The question is:
1) Should min/max be used?
2) Or will they be used in the future?
3) Or were they to be used and can they be removed now?

**Comment by joskuijpers** [comment]
It is option 2. Used in the future. Keeping them in.
