### ISSUE TITLE
Lua running problem

### ISSUE THREAD

**Issue by JD-Power** [RealismusModding/FS17_seasons#304]
hey,
ich habe ein LUA Running auf der map lossberg, ich habe jetzt ca. 1 woche nicht gespielt, heute wollte ich spielen und nach dem start drücken hatte ich diesen fehler drinne
`Error: Running LUA method 'update'.
C:/Users/tippm/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons_master/src/misc/ssSwathManager.lua:40: attempt to perform arithmetic on local 'layers' (a nil value)
`
letzte woche ging es noch und heute war der fehler da. habe nichts neues gekauft/mod hinzugefügt.
hoffe es wird der bug behoben, denn diesen mod will ich nicht missen

MFG
JD_Power 
ps. mein English ist nicht so gut deshalb leider nur per googl translate eventull, findes sich einer der das übersetzt.

Hey
I have a LUA running on the map lossberg, I have not played for about 1 week now, today I wanted to play and after the start press I had this error drinne
`Error: Running LUA method 'update'.
C: / Users / tippm / Documents / MyGames / FarmingSimulator2017 / mods / FS17_seasons_master / src / misc / ssSwathManager.lua:
`
Last week it was still and today was the mistake. Has not bought anything new / mod added.
Hope it is fixed the bug, because this mod I will not miss

MFG
JD_Power
Ps. My English is not so good therefore unfortunately only googl translate eventull, find oneself one of the translated.

**Comment by joskuijpers** [comment]
Hi.

Did you update to the latest version of Seasons?

Can you open your careerSavegame.xm file, and remove the part at the bottom named `densityScanner`? The whole block.

**Comment by JD-Power** [comment]
yeah, its away but, is the entry not important ? 
Thanks for your help

**Comment by joskuijpers** [comment]
It is but this solves it.

Does it work now?

**Comment by JD-Power** [comment]
Yes it Works with your solution
