### ISSUE TITLE
Improve ground wetness

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#306]
Include soil moisture dynamics model to include effects of frozen ground, melting snow, rain, evaporation, crop transpiration, drainage in order to update groundWetness. Code already made in python.

Account for snow that is ploughed into the ground?
What should groundWetness be when there is snow on the ground?

**Comment by reallogger** [comment]
Probably need MP fix..

**Comment by joskuijpers** [comment]
Current code:
stores the soil water content
on server only, every hour, updates that value

so client can have initial soil water content but doesnt get updates.

I don't see any randomness, so if we calculate the new soilwater on client as well, all we need is to sync the initial value from the savegame, right? @reallogger

**Comment by reallogger** [comment]
That seems correct :)

**Comment by joskuijpers** [comment]
Okay, not doing it. Instead i am sending the server value to the client with the existing hourly event. Makes sure it is sync and the server is boss.

**Comment by joskuijpers** [comment]
I have not actually tested it. I don't have the tools currently.
