### ISSUE TITLE
Localized wet crop / frozen ground icons

### ISSUE THREAD

**Issue by Dzi4d3k** [RealismusModding/FS17_seasons#340]
As mention on Slack - maybe something for v2 or later.

**Comment by joskuijpers** [comment]
It might be possible to get rid of the Frozen Ground icon. Possibly making the soiltemp icon blue/white. The temperature already indicates the ground is frozen.

**Comment by joskuijpers** [comment]
![screen shot 2017-06-19 at 18 13 38](https://user-images.githubusercontent.com/5017040/27294875-57fc72bc-551b-11e7-8d90-8180a973db6c.png)

New icons :D Without text.

**Comment by laloe34** [comment]
Is it for the next update?

**Comment by joskuijpers** [comment]
Yes, this is in 1.0.1
