### ISSUE TITLE
Error: Missing descVersion attribute in mod FS17_seasons

### ISSUE THREAD

**Issue by zed636** [RealismusModding/FS17_seasons#353]
I have just download the last version of Seasons and I find this error in my log: Error: Missing descVersion attribute in mod FS17_seasons
it's a simple fix

**Comment by joskuijpers** [comment]
I know, I did it on purpose. Even if you add it, the mod will crash. On Slack i will tell you more about it.

Problem is people uploading our mod without permission :(

**Comment by Bauertobi29** [comment]
FS17_seasons/src/loader.lua:124: unexpected symbol near 'if'

How can I fix this
