### ISSUE TITLE
problem with src/loader.lua error in line 124

### ISSUE THREAD

**Issue by marvetto** [RealismusModding/FS17_seasons#355]
there's an error on file src/loader.lua.the mod load but not work in game
error in the game log:
Error: C:/Users/Marco/Documents/My Games/FarmingSimulator2017/mods/seasonsmaster/src/loader.lua:124: unexpected symbol near 'if'

**Comment by theSeb1979** [comment]
Intentional. Please wait for the release of the mod on Giants modhub.

**Comment by marvetto** [comment]
ok!
