### ISSUE TITLE
loader.lua:124: unexpected symbol near 'if'

### ISSUE THREAD

**Issue by Laui51** [RealismusModding/FS17_seasons#358]
Hi there,

on start up i'm getting the mentioned error in the log and seasons mod won't load.

log:

GIANTS Engine Runtime 7.0.0 (14220) 64bit (Build Date: Feb 17 2017)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Memory: 8142 MB
  OS: Windows NT 10.0 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Logitech Extreme 3D
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 980
  Version: 22.21.13.8165 (31.3.2017)
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 1920 x 1080
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Farming Simulator 17
  Version: 1.4.4.0 1.4.4RC8
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2017-05-12 19:52:03
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load dlc: pdlc_kuhnPack (Version: 1.1.0.0)
Load mod: FS17_seasons
Error: C:/Users/Stefan Lau/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/translations/translation_de.xml. text. .
Warning: Only zip mods are supported in multiplayer. You need to zip the mod FS17_seasons to use it in multiplayer.
Warning: Missing l10n for button SEASONS_SKIP_NIGHT in FS17_seasons
  Register configuration 'wrappingColor'
  Register vehicle type: pdlc_kuhnPack.subsoiler
  Register vehicle type: pdlc_kuhnPack.sowingMachineCultivator
  Register vehicle type: pdlc_kuhnPack.turnOnCultivator
  Register vehicle type: pdlc_kuhnPack.windrower_workMode
  Register vehicle type: pdlc_kuhnPack.extendedBaleWrapper
  Register vehicle type: pdlc_kuhnPack.balerWrapper
  Register vehicle type: pdlc_kuhnPack.sowingMachineKuhnTF1500
Error: C:/Users/Stefan Lau/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/loader.lua:124: unexpected symbol near 'if'
dataS/cameraPath01.i3d (0.12) ms
dataS/cameraPath02.i3d (0.13) ms
dataS/cameraPath03.i3d (0.10) ms
data/sky/skyUS_day_night.i3d (10.81) ms
data/sky/rain.i3d (1.34) ms
data/sky/hail.i3d (0.92) ms
data/sky/dust.i3d (0.75) ms
data/maps/map01.i3d (1696.02) ms
data/objects/basketball/basketball.i3d (1.68) ms
Enabled withering
data/vehicles/steerable/caseIH/caseIH1660.i3d (59.87) ms
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (39.99) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (43.26) ms
data/vehicles/tools/kuhn/kuhnCultimerL300.i3d (20.98) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (59.62) ms
data/vehicles/tools/greatPlains/gp3P1006NT.i3d (23.94) ms
data/vehicles/trailers/metaltech/db8000.i3d (34.17) ms
data/vehicles/steerable/lizard/lizardPickupRodeo.i3d (33.69) ms
data/objects/pallets/fertilizerTank.i3d (2.74) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (4.27) ms
data/placeables/shelters/storageShelter01.i3d (6.78) ms
data/placeables/shelters/storageShelter02.i3d (2.52) ms
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (2.32) ms
data/placeables/shelters/vehicleShelter.i3d (1.60) ms
data/vehicles/train/locomotive.i3d (25.84) ms
data/vehicles/train/wagonTimber.i3d (12.28) ms
data/vehicles/train/wagonWoodChips.i3d (13.49) ms
data/vehicles/train/wagonGrain.i3d (13.49) ms
data/vehicles/train/wagonSugarbeets.i3d (13.04) ms
dataS2/character/player/player01.i3d (285.05) ms
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Logitech Extreme 3D
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 980
  Version: 22.21.13.8165 (31.3.2017)
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 1920 x 1080
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Farming Simulator 17
  Version: 1.4.4.0 1.4.4RC8
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2017-05-12 19:52:40
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load dlc: pdlc_kuhnPack (Version: 1.1.0.0)
Load mod: FS17_seasons
Error: C:/Users/Stefan Lau/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/translations/translation_de.xml. text. .
Warning: Only zip mods are supported in multiplayer. You need to zip the mod FS17_seasons to use it in multiplayer.
Warning: Missing l10n for button SEASONS_SKIP_NIGHT in FS17_seasons

**Comment by theSeb1979** [comment]
Intentional. Please wait for the released version on Giants modhub, which will be very soon.

**Comment by Laui51** [comment]
That's alright. Just thought it might be interisting for you guys and didn't want to hide this.

Love your work by the way! ;)

**Comment by theSeb1979** [comment]
Thank you. We have had to break the code intentionally temporarily due because some of the shady sites with no morals have tried to steal our work. The mod will be released soon via the Giants modhub.

**Comment by Laui51** [comment]
That's what i thought about the missing mod version, but wasn't shure about this point. 

Shame though. Be shure that there is still a huge amount of people just peacefully, thankfull but quiet using your mod and apreciate your work. Hope you have a good weekend ;)

**Comment by theSeb1979** [comment]
Thank you for your support.
