### ISSUE TITLE
Add option suggest

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#360]
Hello there, I'm just testing this mod and seem really cool and innovative :), I come to suggest and try to know a way to disable repair module that can override with other mods repair that I have as example.
It would be fine if we can have a disable/enable repair module in menu configuration you know.
Another thing, no linked hours life vehicle in F1 menu information seem not based on the real buy hours vehicles like the picture show same after saved game with seasons.
![1](https://cloud.githubusercontent.com/assets/25174503/26016588/f185dab4-3765-11e7-92e6-8eaeb5528e29.jpg)

Edit:
I see when Seasons loaded too some price to (grange) seller are to 0 like the pict dunno if is a normal process of Seasons but weird.
![2](https://cloud.githubusercontent.com/assets/25174503/26019984/1962b494-377a-11e7-89af-ae4e1aaca7d0.png)
Br Seasons

**Comment by theSeb1979** [comment]
In the F1 menu the hours are to repair, not the current operating hours, so the two numbers will not be the same. 

We set some prices of some things to 0, because they would not normally be sold in real life.

**Comment by Anonymous-any** [comment]
"We will not be disabling our maintenance module" thank you sad for this .

Br SS

**Comment by theSeb1979** [comment]
Sorry, but I don't understand your comment. What did you mean by "permit change switch" ?
