### ISSUE TITLE
Issue unload

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#362]
I have found an issue unload here function with FS17_lelyJuno150 (Version: 1.0.2.0) mod that the one I have where when Season is loaded lelyJuno150 cannot unload :/ animals can die °-^
Br Seasons

**Comment by theSeb1979** [comment]
Please provide more information. I am struggling to understand the problem.

**Comment by Anonymous-any** [comment]
I'm  sorry my english is limited as you can see, maybe the better you have to test lelyJuno150 tutorials and test yourself without Seasons loaded and with Season loaded lelyJuno150 is a device that used for clean and (auto-refill) animals area.
Br

**Comment by theSeb1979** [comment]
I think I understand now, but to confirm

1. What are the animals that you are having problems with? Is it sheep?
2. I assume that you have grass in the trough and it is winter when you saw this problem?

**Comment by Anonymous-any** [comment]
Hello noo triggers seem not interact in fact the problem is seem related directly with lelyJuno150 unload here function.
Best regard

Salut je crois que vous êtes français en fait le problème semble être lié directement avec lelyJuno150 qui ne peut plus décharger ici partout sur la carte peut importe si le trigger est la ou pas.
Il est ici si vous souhaitez completer le test:
[https://www.farming-simulator.com/mod.php?lang=fr&country=be&mod_id=58638](url)

**Comment by Anonymous-any** [comment]
"What are the animals that you are having problems with? Is it sheep?"
No it was everywhere.

   "I assume that you have grass in the trough and it is winter when you saw this problem?"
No it was middle seasons the spring.

**Comment by theSeb1979** [comment]
You might be using an old version of our mod. We tested the functionality with another cleaning mod and it works fine. The official release will be on giants mod hub in the next few weeks.

**Comment by Anonymous-any** [comment]
I use 0.9.0.0 seasons version what about you talk with another cleaning mod? I was just report what is wrong with this one, have you test this one like I purpose you? I never say you test with another lol.
Br

**Comment by theSeb1979** [comment]
I think you are missing the point. If the Lely Juno is doing something odd, then it is a problem with that mod and not our mod, since other cleaning equipment works. One of testers has used the Lely Juno before as well and it works fine. Perhaps you have an old version of the Lely Juno

**Comment by Anonymous-any** [comment]
Hi okay are you sure he is using the unload here function in it? I never say Lelyjuno not work it can store itself a bit storage but the real usage for it is unload here function like I try to explain then what version seasons do he use? what version of Lelyjuno he use? anyway the link I gave you is the last version of Lelyjuno right? where are his links of his seasons test and Lelyjuno test?

I try to report you a full test with what I do and link to the mod is official right?
Now are you going to say me to stop using Lelyjuno exchange to use seasons is a good mod too?
remember one thing Lelyjuno exist in real life too :/
Br

**Comment by theSeb1979** [comment]
I have tested the Lely Juno and it works perfectly fine in any season, except for when snow is on the ground. It is the same problem if you drive it too close to the manure heap. It fills up with materials that it should not, due to the fill types of the mod. The author is welcome to get in touch with us to discuss how to make the mod compatible with seasons

**Comment by Anonymous-any** [comment]
You are bounded eh but it does not matter, so you have understood that there is a problem when you are in the "shoveltriggercatcher" area where you can not unload while without Seasons it works.

I doubt also the author came here to look at this post :)
Br thank and sorry for disturb

**Comment by theSeb1979** [comment]
No disturbance at all. I have a hope that many mod makers will want to try and make their mods compatible with ours :)

**Comment by Anonymous-any** [comment]
Hope you right that completely modify how we play now :p added to a modded map like the new model by Arsenic is a pleasure:
https://www.youtube.com/watch?v=UTnSkq39AF4
Giant are tired noob comparative to lol
Br
