### ISSUE TITLE
Investigate why catching up screen does not go away sometimes

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#369]
Seems to be related to snow, but not 100% positive on this. 

 I always see the message x was reduced x (where x is the same) when this happens

![fsscreen_2017_05_16_09_58_54](https://cloud.githubusercontent.com/assets/23258759/26114430/25aeeb54-3a55-11e7-8836-b538ada65d26.png)

**Comment by joskuijpers** [comment]
It seems that the queue never empties when something with snow happened.
