### ISSUE TITLE
Rot wet grass in tippers

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#399]
Use the same technique used for SnowFillable to remove grass over time.

**Comment by Dzi4d3k** [comment]
But I'll suggest to reduce it to some point for example 50% (need to do research on that) and make manure from it on maps that don't have compost layer, but compost on prepared maps.

**Comment by joskuijpers** [comment]
Also:
when it rains, reduce tippers with hay and straw that are not under cover

**Comment by joskuijpers** [comment]
Done
