### ISSUE TITLE
Implement straw swaths for soybean and canola

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#4]
I’ve added a straw swath to canola and it’s dropping onto the ground from the harvester. I can pick it up. But the animation of it coming out of the harvester is missing. The swath just appears after the harvester, which looks quite disconcerting. Further investigation is required.

**Comment by joskuijpers** [comment]
Why do we want strawswath for these crops? Isn't there a reason they are missing in the main game?

**Comment by theSeb1979** [comment]
A lot of people want it in the game and you can get straw out of these crops. It's also pretty easy to do with code, apart from the small bug of the missing animation, which I am sure we can figure out. 

My aim is for this mod is to become almost like the "More realistic" mod, but for crops, so adding straw swaths is within the theme. Also, when it was just Akuenzi and I discussing it, I pictured that we would create separate mods as we go along, like weather forecast, modify growth based on settings, add swaths and modify swaths and so forth. Then we would put all of the knowledge that we gained and do the season thing. Obviously that approach has changed, but I still want to implement this functionality. 

Priority can be changed to low though.

**Comment by joskuijpers** [comment]
I suggest we dont do this anymore and let another mod do it

**Comment by theSeb1979** [comment]
Closed. Will not be implemented in the foreseeable future.
