### ISSUE TITLE
[WM] Weather Manager initial implementation

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#40]
What I see is in the weatherManager class we will have a day changed listener

g_currentMission.environment:addDayChangeListener(ssWeatherManager)
then we implement function ssWeatherManager:dayChanged()
in this function we check the day and get the season
and manipulate upcoming temperatures appropriately
in the deleteMap function we can save the weather state
in the loadMap function we create the initial weather appropriate to the season, if it’s a new save game that does not have our manipulated weather (edited)
otherwise we load our mainpulated weather into g_currentMission.weatherTemperatures tables and g_currentMission.environment.rains
dayChanged will be called automatically by the game because it is a call back function to an event that is triggered by the game engine
whenever the day changes

initially going to just use tables of temperatures appropriate for the season and use them randomly. You guys can then tell me how to implement your special temperatures 

But I want to create the initial implementation and test it because I am not entirely certain how the engine regenerates the weather so need to play around with it

it seems to add stuff to the weather tables at the end of each day

**Comment by joskuijpers** [comment]
Yeah I've used the day change listener in all my classes, it is super handy

**Comment by reallogger** [comment]
To be closed when joskuijpers enable save of the forecast

**Comment by reallogger** [comment]
Done
