### ISSUE TITLE
Mod in Moddata

### ISSUE THREAD

**Issue by SgtBruse** [RealismusModding/FS17_seasons#408]
Error: C:/Users/User/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/loader.lua:124: unexpected symbol near 'if'

Hello

I have an error as soon as I mod mod in the folder I have the moddesc number registered but troßdem comes that

**Comment by reallogger** [comment]
Intentional. Please wait for the release of the mod on Giants modhub.
