### ISSUE TITLE
Add support for non-standard environment configurations

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#41]
If a map has changed its environment, we completely ignore it.
There is two ways we could fix this:

1) Ask the map maker to make a script that works with Seasons to update the environment
2) Use the xyz values form the environment file while using the time values from our own system. Will only work if they only changed the xyz(w) values.

**Comment by joskuijpers** [comment]
Moving this to V2

**Comment by mpffh1** [comment]
hi again,
to 1.
Your code changes the enviroment in every map. so the mappers enviroment is overwritten. I tested it with the standard map and a mod mad wich has its own enviroment. your code works well.
so 2.
the values in your code overwrittes the maps values .That means to me ,I only change he xyz values and get the time from your formula
excuse me when i´m not rhight ,in my case it work´s

**Comment by joskuijpers** [comment]
In my code, the number of elements in the curve and the values of the elements is the same as Vanilla. I just changed the time.
So I could have read the custom map environment, checked if it had the same curve as vanilla, and use the xyz values of it.
With your system, we can't because the environment file cant be fit into the new curves.

It is not much of an issue really. If requested a lot, we can add a new seasons_environment.xml file with curve values.

**Comment by mpffh1** [comment]
ok sorry that i stolen your time
But a question:
in daylight.lua in 
function ssDaylight:adaptTime()
    local env = g_currentMission.environment
I thought you got the whole table from environment that is in game readed from environment.xml and overwrite it
some lines later with the curve return
env. ...
env. ...
.
.
.
my mistake :to do ->must learn more lua (english too)
thanks for yours time
maybe in Seasons V2.x

**Comment by joskuijpers** [comment]
Huh, no, you didn't steal our time. :P Your code is fine. This issue is unrelated.

**Comment by joskuijpers** [comment]
This has now been implemented in v1. Only allow the color values for some curves. Must be the same number of keys as vanilla.

Regarding moon-etc: we will re-look at that in V2 and see if we can do that and still have some proper values 😃
