### ISSUE TITLE
Animal area issue

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#410]
Hello I was posted closed issue to unload here at animal area with Lelyjuno function and Theseb return no problem ask author Lelyjuno etc to come here ok. Here https://github.com/RealismusModding/FS17_seasons/issues/362.

I try again with an other mod tool Frease like this:
![1](https://cloud.githubusercontent.com/assets/25174503/26456460/6b4ab142-416d-11e7-932f-340c4de1e67b.png)

 and the tool simply stop working inside area shovel animals meaning seasons block all tools to clean areas that I can understand. Is TheSeb going to say me all authors of cleaners mod must come he to change theirs or adapt mods for seasons? or is theses issue are going to be added as issue "bug" to try to be solve? I hope you don't think you go ask alls authors to mod adapt their own for seasons right?.
TheSeb never ask me what version Seasons is official and where to download seasons versions,  he say Lelyjuno it work with no issue.

I read lots of post you say seasons release soon on modhub it's ok but we have no information of the real official version already released you say only you say we have robbers on sites ok for that too. I want to mean a simple question what is the official version of season and where to download? (I don't talk about what you are to working on it i talk about the already released).
Br

**Comment by joskuijpers** [comment]
Hello @Anonymous-any 

Can you provide me:
A zip file with  your savegame
And the mods that cause issues (also in a big ZIP file)
Also add your version of Seasons to that ZIP file

Then I can look at it.


At this moment, there is no official version of Seasons, because we have not released yet. We will release with the ModContest. So it will be available in about 2 weeks, we think. You can then download in on the Giants Modhub.

**Comment by Anonymous-any** [comment]
Okay glad to hear that ! okay @theSeb1979 by the way Jos I going to wait for the official release then I'm not going to tired you with sad version robbed that mean and I don't understand too why there is so lots of versions different on internet :/ that for why I was thinking you have already released an official version while you never release anyone versions official that amazing.
If the issue I see continue after your real version then I came back to suggest again.
Sorry again regards
