### ISSUE TITLE
Longer seasons

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#412]
Add option to increase season length beyond 12

**Comment by joskuijpers** [comment]
For this, we need to verify our data.

I suggest we add 15, 18 and maybe 21. If we figured all our values hold up for any value of `n`, we could support more.

Until what time is it realistic though? Not realism, but playable. If you have 30 days per season, fermentation takes 10 ingame days. Everything else is slow. And your machines still plough at 10kmh

**Comment by theSeb1979** [comment]
Reopening to make sure everything else is still ok

**Comment by joskuijpers** [comment]
@reallogger do you have time to look at some of the algorithms you have, and verify, if needed? I will take a look at the files I have around, but I think only my daylight and economy are up to date.

**Comment by joskuijpers** [comment]
Economy is not bound to season length. Daylight should work just fine.

I just wonder about the maintenance stuff.

**Comment by joskuijpers** [comment]
Should work, according to @reallogger
