### ISSUE TITLE
Unable to exit game - `15cbbc0`

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#418]
Error: Running LUA method 'mouseEvent'.
C:/Users/sebastianp/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons_develop_15cbbc0/src/environment/ssEnvironment.lua:193: attempt to call field 'remove' (a nil value)
Warning (Script): Unknown entity id 64039 in method 'saveCropsGrowthStateToFile'.

**Comment by joskuijpers** [comment]
Fixed
