### ISSUE TITLE
Plowable snow

### ISSUE THREAD

**Issue by mrbear** [RealismusModding/FS17_seasons#42]
I'm trying to implement  snow using  terrainDetailHeight or tipAnyware in the Season Manager framework.

The idea is to add one layer of snow for each unique hale by usning an hourly listner. So every hour if it's snowing and was not snowing the hour before we add a layer. Do we have hales outside of the winter period that should not add snow?

When spring comes all snow is cleared.

The actual update will be done in the update function using a doAddSnow flag and X, Z coordinates doing 1/n x 1/n of the map at a time. Initialy I test with 1/10 of the mapsize. 

Snow will only be added where there is not already material tipped. Further I would suggest that we use a mask layer that the map maker can add to the map to keep show out of the sheds. If the mask layer is not present we add snow every ware, let pretend it have been blowing so it ended up in the sheds as well. I cant come up with a reasonable way to automatically mask the call to addDensityMaskedParallelogram depending on weather there is a building above or not.

**Comment by joskuijpers** [comment]
Whether it is snow vs hail is determined by the current temperature.

Melting snow is also by the current temperature: so if the winter starts cold and ends relatively warm it would have melted already.

Regarding sheds: how about placeables?

**Comment by joskuijpers** [comment]
We should see if there is some way to make it fall less suddenly, so start with less.
Would it be possible to say, do only every 4th meter? And then every 2 4th meters, etc? So that it is not suddently BOOM white?

Otherwise we could do it during the night (or when it is dark, which is very long in the winter)
