### ISSUE TITLE
tyre tracks and dust particles when there is snow

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [RealismusModding/FS17_seasons#426]
![fsscreen_2017_05_31_23_56_32](https://cloud.githubusercontent.com/assets/8200153/26654056/fe000628-465d-11e7-9b99-720db309bf3e.png)

**Comment by joskuijpers** [comment]
Can't make tiretracks on top of snow. Game just does not support it, and I dont think it is important enough.

What is possible is to color the tracks to white after driving in snow for a while

**Comment by Dzi4d3k** [comment]
Well, I think that it was all about that tire track were dirty brown when driving on snow, and making the white, when on snow would be enough. Not need to press tire patterns in snow, I think for such simulations we need to wait couple of years.
