### ISSUE TITLE
Allow a mod to overwrite the whole growth table

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#432]
Using overwrite="true", like with some other xml (textures)

Must also fix the issue where multiple geo mods could be loaded: #421

**Comment by theSeb1979** [comment]
does overwrite mean all fruits (easier in code, more complex custom growth file), or just the fruit in the file (more complex in code, easier to create custom file)

**Comment by theSeb1979** [comment]
Will overwrite all data

**Comment by theSeb1979** [comment]
Done
