### ISSUE TITLE
Impossible to start ingame

### ISSUE THREAD

**Issue by falconvini** [RealismusModding/FS17_seasons#437]
Hi,
First sorry for my english I'm frenchspeaker.
1. I installed mod in my mod folder.
2. Only 1 map activated and no other mod than season mod
3. I receive this error in my log:
Error: C:/Users/vince/OneDrive/Documenten/My Games/FarmingSimulator2017/mods/FS17_seasons_master/src/loader.lua:124: unexpected symbol near 'if'

4.Results: career well started but without seasonmod response (lalt+F and others does not work).

Best regards,

FalconVini

**Comment by theSeb1979** [comment]
Please wait to download the mod from Giants Modhub, which will be very soon. The development version cannot be used in the game. Thank you.

**Comment by falconvini** [comment]
Thank you for your answer and well received! Success for you!

**Comment by theSeb1979** [comment]
Thank you.
