### ISSUE TITLE
Snowmask isnt showing right in GE

### ISSUE THREAD

**Issue by BlaggyXD** [RealismusModding/FS17_seasons#443]
I tryed to get the snow mask in my map but some how it dosent looks like it should look , i tried to build it an other map there it worked like it should. The green stuff is not as small as it should be , it is like 2 big lines about 2-4m. If it is help full i can try to get Pictures of it. 

Greets,
Blaggy

**Comment by Dzi4d3k** [comment]
Screenshoot could be usefull, just drag@drop it here in text box, but are you sure that you didn't messed the `file id` number of `windrowFoliageShader`, which is required in place of `????` in pasted `<Materials>` section?

**Comment by BlaggyXD** [comment]
The ID is right , i builded in to an other map there it worked fine. Here are the two Pictures:
![sssnowmask_wrong](https://user-images.githubusercontent.com/20562677/27175564-d086e172-51bf-11e7-93d9-32bc33f79f6c.png)
![sssnowmask_right](https://user-images.githubusercontent.com/20562677/27175565-d098b5fa-51bf-11e7-8b1d-7698744fa24e.png)

**Comment by Gonimy-Vetrom** [comment]
Try setting the value of blockShapeId such as blockShapeId to forestGrassDark.

**Comment by BlaggyXD** [comment]
Thats it , the ID was on 80 but forestGrassDark is 79 , i changed it and now its right , Thanks a lot
