### ISSUE TITLE
Plowing snow from roads

### ISSUE THREAD

**Issue by phragmatic** [RealismusModding/FS17_seasons#449]
(My first post on GitHub, apologies in advance if this is the wrong forum for this)
First of all thank you for this awesome mod, nicely executed! 
My issue:
I did a snowmask on Lossberg that only masks the interior of the sheds. The snow that falls outside can be cleared with a plow or shovel from everywhere except the roads. Should that be possible or do I need to mask them aswell if I want the roads clear?

**Comment by joskuijpers** [comment]
Assuming the roads are those objects and not paintend, then it is intended. You can't move Tip Anywhere there.

Instead, the Seasons Mask should cover all of those roads so no snow falls there.

**Comment by joskuijpers** [comment]
Also, the newest version of Lossberg, today available on ModHub, already has a seasons mask :D

**Comment by phragmatic** [comment]
Thank you for the fast response. Atleast I got to play it a little earlier ;-)
