### ISSUE TITLE
Implement grass_silage

### ISSUE THREAD

**Issue by debejerry** [RealismusModding/FS17_seasons#456]
Maybe it might be possible to implement kind of grass_silage somehow as the improvedBunkerSilo Mod by upsidedown did in FS15. 
I think this might fit into a more realistic gameplay  as one would have for example an alternative to fresh grass to feed cows during the winter. 
Also other parts would be interesting i.e. if a Silo has chaff or grass filled in and it isn't covered for fermenting within a specified amount of time chaff/grass starts rotting and is converted to manure or compost. 

Thank you for your hard work and good luck at the contest!!

**Comment by joskuijpers** [comment]
Related: #399
