### ISSUE TITLE
Crop destruction

### ISSUE THREAD

**Issue by heavenlypictures** [RealismusModding/FS17_seasons#457]
The crop destruction doesn't work for me. I drived on a 1st grow state field, and nothing happened.
I see the following in the log:
[Seasons] ssCropDestruction: Crop Destruction mod found. Modifying...
Is this mod changes the Giants' desctruction mod?
How it works?

**Comment by baleBaron** [comment]
This is expected, the Crop Destruction from GIANTS update this a while ago.
Destruction for normal crops (wheat etc.) only happens from 2nd visible growth stage.

Yes, Seasons does small changes to CD by GIANTS. These changes are only technical for compatibility reasons and does not change anything for the player.
