### ISSUE TITLE
Bales disappeared

### ISSUE THREAD

**Issue by heavenlypictures** [RealismusModding/FS17_seasons#458]
I had some round grass bales in a shed. But they are disappeared. I don't know exactly when, but I think after a rain. The map has a snow mask, and it is painted under the shed.

**Comment by reallogger** [comment]
Grass bales will rot after 2 days no matter where they are placed.

**Comment by theSeb1979** [comment]
This is like real life. grass bales must be wrapped into silage bales, or they will rot.

**Comment by heavenlypictures** [comment]
Ohhhh. I'm not a farmer. I didn't know that.

**Comment by theSeb1979** [comment]
No worries. Check out the Esc menu --> Help.. and then scroll to the Seasons section. We've put in a manual there

**Comment by heavenlypictures** [comment]
Yes, I know. I already read it. But it speaks only about hay and straw bales, but not grass bales.
So how to store grass for sheeps?

**Comment by heavenlypictures** [comment]
Sorry. You already wrote it a few post ago. I have to wrap it. Thanks

**Comment by theSeb1979** [comment]
Just like in real life, you will have to adopt a "zero grazing system" and use a forage wagon to get them fresh grass every day, or use hay bales (dry grass baled) and lose a bit of productivity. This is also the only way to feed them during the winter. You lose a bit of productivity, but that is the life of a farmer. 

About your edit: if you wrap wet gras bales, it will become silage. You cannot feed them to sheep in vanilla or Seasons.

**Comment by heavenlypictures** [comment]
After playing FS for 3 years I thinked I know everything about farming. But Giants didn't tell me a lot of things. The whole farming is really different with 4 seasons. I have to learn a lot. Thanks for your help, and for your great work.

**Comment by theSeb1979** [comment]
No problem. You should join us on slack. Much easier to chat and ask and ask questions. 

https://slack.realismusmodding.com/

Thanks for your tips about the images.
