### ISSUE TITLE
Silage of bales lying on the field during winter trouble?

### ISSUE THREAD

**Issue by criss20ster** [RealismusModding/FS17_seasons#460]
And I have asked you why mulberry grass bales on the silage suddenly do not which bales are scattered on the ground what can be seen on the photo and additionally see from the mixer machine all TMR lies in the field under the snow

http://screenshot.sh/m1Sz2BPkSGDgK

**Comment by theSeb1979** [comment]
This is a limitation of the Giants engine. Only one fill type can be at the same place so snow falls everywhere where there isn't another fill type already.
