### ISSUE TITLE
Sorry for next post this winter TMR trouble 

### ISSUE THREAD

**Issue by criss20ster** [RealismusModding/FS17_seasons#461]
But I mean, with that TMR I had on the TRAILEDLINE DUO 1814 machine and suddenly when the snow fell the patrol was in the TMR field

**Comment by theSeb1979** [comment]
Prosze nie otwieraj nowe ticket na ten sam problem. 

Ja nie rozumiem twoj problem. Co to jest patrol? I co to jest TMR field? TMR = totally mixed ration. Potrzebuje wiecej informacji.

**Comment by criss20ster** [comment]
@theSeb1979 
Well. I did not know that in the closed topic you can write on. Sorry. The thing is that in the siloking this animal mixer a small loaded TMR feeder trailer. When the snow has fallen, the sudden fodder lies on the field as you saw in the picture. I hope now I explained what I mean

**Comment by theSeb1979** [comment]
Thank you. I think I understand the issue now. We will take a look.

**Comment by criss20ster** [comment]
@theSeb1979 ;)

**Comment by reallogger** [comment]
Tested with a mod feeding trailer on Lossberg. TMR stayed in the trailer, while snow accumulated in an empty tipper.

**Comment by reallogger** [comment]
Also tested on GCV with the Siloking Trailedline Duo 1814 and TMR stays in the feeder trailer when it snows. Cannot reproduce what was reported.

**Comment by theSeb1979** [comment]
Unable to reproduce. Closed.
