### ISSUE TITLE
Removal of grass around the edges of the field

### ISSUE THREAD

**Issue by ian898** [RealismusModding/FS17_seasons#466]
Hello Lads, I have been away for a while been testing seasons and its amazing it makes me laugh thinking back when everything started on this project of how many ideas we shared what if and I must say I love what you have done with all of it especially the animals it puts my livestock manager to shame now haha.

Now to the problem I have noticed that all the default cultivators destroy grass around the fields after one season has passed I find this troubling because I have set my dedicated server back up and I have been letting my kids take it in turns to cultivate and I know before long there will be no grass around the edges of fields with not an easy way to replant it and it will just look bare and ugly haha, I am not sure if it was intended or a bug so I thought I would ask also if it was intended could you possible point me in the right direction so I can stop it from happening myself, also you have my 5 stars on the contest good luck lads.

Many Thanks

Ian

**Comment by theSeb1979** [comment]
Hello. We are aware of this. Trying to figure out a fix.

**Comment by bnjgray87** [comment]
One suggestion, you could use the ground modification mod to repaint any areas lost in the short term. The only problem is finding a roller small enough to rescue these smaller more awkward areas.

**Comment by ian898** [comment]
Thanks for the quick response if you cant fix it its not a huge problem to me now I will follow ben's advice for now.

**Comment by theSeb1979** [comment]
Should be fixed now and will be available in 1.0.1.0 some time after the contest ends
