### ISSUE TITLE
Crop & soil request?/enhancment

### ISSUE THREAD

**Issue by MrTobbsta** [RealismusModding/FS17_seasons#468]
Just too have it said, good f'in work so far!! This is sort of a request but mainly a suggestion if it's even possible too do. Sparying against herbicide and pesticide during late spring and early summer. Maybe something to chech the Ph value of the soil. It don't have to be as complex as soilmod but just enough to make it a bit harder and more realistic.

Thanks for all your hard work!

**Comment by theSeb1979** [comment]
Thanks. We will see what soil mod brings to the game before making any decisions on such functionality.

**Comment by theSeb1979** [comment]
__
