### ISSUE TITLE
tireTypes for "chains" and "studded" are not correct

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#469]
tireType is still 1 for wheels with tireType "chains" and "studded" even though the new tireTypes are added to WheelsUtil.

**Comment by joskuijpers** [comment]
Moving this to 1.2. There are no vehicles being made with this and it might be completely difficult to do.

Might need to contact Giants about the possibilities.

**Comment by joskuijpers** [comment]
Need to see if this works...

**Comment by joskuijpers** [comment]
Need to test if this now works with 1.5.1

**Comment by reallogger** [comment]
Tested and works very nicely with 1.5.1

![image](https://user-images.githubusercontent.com/15114342/32755196-6cd2c7ea-c8d4-11e7-93d1-da94a2db2ba0.png)
