### ISSUE TITLE
Repair the first day or several times a day

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#470]
This is intentional, but some find it confusing that Alt + R does not work

Proposal from mrbear: proposed key works but displays a message that says no repair needed [OK].

**Comment by Dzi4d3k** [comment]
I would agree, that is is good idea, because I also see complains that repair isn't working.

**Comment by joskuijpers** [comment]
So should i always show the repair cost, it sometimes being 0?

And then the button works but insetad shows a blinking warning?

Or just step 2, and not 1?

**Comment by Dzi4d3k** [comment]
Hmm. I my opinion 2nd only would be sufficient.
