### ISSUE TITLE
DMS has overlaps

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#473]

**Comment by baleBaron** [comment]
DMS map subdivision does overlap in certain spots resulting in density map pixels being affect twice by growth.
This is also true for heightMapId when applying snow. 

Only happens on corners where 4 patches meets and always at the same spots.

Current algorithm uses magic values found through trial and error, we need to be smarter.

![dms](https://user-images.githubusercontent.com/26336561/27533777-2195edda-5a65-11e7-80d0-c2831e8ce4d9.png)

**Comment by joskuijpers** [comment]
Hmm. Is this on vanilla maps as well?

**Comment by baleBaron** [comment]
Not tried to reproduce this much on vanilla maps so far.
But it should be no different as they use same resolution for densitymaps.

Will try to find a case for GCV

**Comment by joskuijpers** [comment]
Reproduced on GCV. never spotted this before.

**Comment by joskuijpers** [comment]
I got the feeling that maybe we have some kind of 'anti-aliased' regions, and that only at the corners the 'opacity' of every region becomes enough to .... wait that is bullshit.

We need to verify the regions used.

**Comment by joskuijpers** [comment]
Anything new on this?

**Comment by joskuijpers** [comment]
@baleBaron ping 🔨

**Comment by joskuijpers** [comment]
I think it can be merged.
Only support issue we could get is people who saved during a transition.
