### ISSUE TITLE
DMS folding has issues.

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#474]
@baleBaron can you elaborate?

**Comment by baleBaron** [comment]
The issue I'm having is that no folding takes place while game speed is >120, it is only done when going from >x120 -> <=x120.

If you set a game speed that is >120 but not super fast (like x600, x1200), we miss out on an optimization opportunity. DMS will be removing 1 layer of snow after 1 layer of snow when it could be doing more important stuff.

I suggest let folding happen each time a new task is appended to the queue. That way the queue can never be larger than number of unique tasks.

**Comment by joskuijpers** [comment]
@baleBaron where has this gone?

**Comment by joskuijpers** [comment]
Do we need to change this for 1.1?

I can do this, but it needs some serious stability testing.

**Comment by joskuijpers** [comment]
Fixed
