### ISSUE TITLE
Snow below bales, pallets and cars is not removed

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#476]
![screen shot 2017-06-27 at 00 02 06](https://user-images.githubusercontent.com/5017040/27562220-e17c900c-5acb-11e7-94f8-0af7c2328bd8.png)

Is the finalizer called?

**Comment by reallogger** [comment]
ssSnow.removeSnowUnderObjects is never executed by DMS

**Comment by joskuijpers** [comment]
Oh found it. broke it when i rewrote the dms. forgot to rename the finalizer.
