### ISSUE TITLE
Normalize rotting of straw and hay bales

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#480]

**Comment by reallogger** [comment]
Initial try with 7dc5559

Hours in rain before square bale rots
3 day season - 18 hours
6 day season - 21 hours
9 day season - 25 hours
12 day season - 29 hours

Doing linear scaling will not make sense

**Comment by reallogger** [comment]
Currently round bales last longer in rain than square bales as both vanilla round and square bales have fillVolume 4000. This means that the compression factor for the vanilla balers is 1.5 for square bales and 2.7 round bales, which is somewhat odd

**Comment by joskuijpers** [comment]
round bales lasting longer than square bales is a feature.

**Comment by reallogger** [comment]
Yes it's fine. 

Hours in rain until a vanilla round bale disappears:
3 day season - 40 hours
6 day season - 47 hours
9 day season - 56 hours
12 day season - 66 hours

**Comment by joskuijpers** [comment]
Is this done then?
