### ISSUE TITLE
Belts cannot be driven.

### ISSUE THREAD

**Issue by 2korda2** [RealismusModding/FS17_seasons#484]
Can jump in. Can turn wheels. Cannot move.
Tested on:
Belts:
S-710
TC 80-16
SL 80-22 Quantum
Maps:
Dusty Cove
Coldborough V3

**Comment by joskuijpers** [comment]
Did you turn them on,

And what is the current maintenance state?

**Comment by 2korda2** [comment]
Duh, my mistake - didn't turn the "engine" on :)
