### ISSUE TITLE
Snow too slippery

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#485]
Snow might feel like ice. We could increase the traction on snow.

**Comment by joskuijpers** [comment]
Can we see if we need to increase snow traction?

**Comment by reallogger** [comment]
There are not many users who have reported fricton to be too low. It is less than what you would expect, but it gives an incentive to clear snow. I feel it is fine as it is.

**Comment by joskuijpers** [comment]
Alright. If nobody else has a comment, this can be closed.
