### ISSUE TITLE
Cannot pick up snow in some area

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#488]
![fsscreen](https://user-images.githubusercontent.com/25174503/27812136-d20b7b78-606c-11e7-8bc6-aca127a6156f.png)
I show you a screen where (lots area not only this one in marker circle) I cannot pick up the snow with shovels, lelyjuno or all I tried or the frease showed I use in screen do you know is this normal?
Br

**Comment by joskuijpers** [comment]
What map is this?

I think it is a tipcol area not masked in the seasons mask

**Comment by Anonymous-any** [comment]
MMmmmm here the link map:
http://www.frabel-lsmodding.com/t65728-DL-Un-petit-coin-de-campagne.htm
I must say you I have made myself the snowmask cause I read the author seem not go update his map to snow officially and purpose. Mean I think don't lose your time with that I was just ask a question why, then many thanks (also there a bug if you try it to "coopérative viticole" where you have to correct in map01.i3d Index: 8>116|12|5|1 MainPlate Attributes width is 5 to 4) if not at a moment when pallets come you crash hang game of course if you don't use coop viticole that must not happen (I think).
Another screen seem happen all around buildings is there always tipcol? I go see...
If it's that how must I do for solve that, tipcol area not masked in the seasons mask?
![2](https://user-images.githubusercontent.com/25174503/27835687-53e107f2-60dc-11e7-8e6a-90fd4643fe81.jpg)
Br

**Comment by Anonymous-any** [comment]
Hey you look good Maestro :p
![3](https://user-images.githubusercontent.com/25174503/27837175-1cd6cdc6-60e3-11e7-8cf0-a507a295b70e.jpg)
If I understand good there is no way when tipcol to pickup the snow or have you a fix please?
Br

**Comment by joskuijpers** [comment]
no, can't be done. When there is tipcol you cant pick up snow.

**Comment by Anonymous-any** [comment]
Ye been think of that it's ok but true the map author don't know what or how to use tipcol :/
I rebuild it sorry for disturb, Hey now you have milliàooooOOOnnn's do you invite me on the boat :p :p lol ^^
Br ;)
