### ISSUE TITLE
seasons_filler.lua only works with ice plane

### ISSUE THREAD

**Issue by KITT3000** [RealismusModding/FS17_seasons#491]
I added to this map the script (mentioned in the title) and it only works with "icePlane", on "seasonAdmirer"  and "snowAdmirer" objects does not change the collision mask to 0 is only the default. Anything else I need to change??

**Comment by joskuijpers** [comment]
Sure it should work.
The code is the same for ssIcePlane, ssSeasonAdmirer and ssSnowAdmirer, (as you can see inside the script)

**Comment by KITT3000** [comment]
I guess I found a cause. For testing, I disabled the visibility of the entire group, and from what I see by the code, it must be on every object.

**Comment by joskuijpers** [comment]
Yes, can't help that. Otherwise i need to walk the whole scene tree and that is a bit too expensive for this, I think. (I could...)

**Comment by KITT3000** [comment]
I understand, then I'm going to fix it, and a thread can be closed.

**Comment by joskuijpers** [comment]
What you can do is adjust the code, and walk over all the parents:

```lua
local cur = id
local invisible = false
while cur ~= 0 do
    if not getVisibility(cur) then
        invisible = true
        break
    end

    cur = getParent(cur)
end

if invisible then
    setCollisionMask(id, 0)
end
```

**Comment by KITT3000** [comment]
Ok, thanks for the help.
