### ISSUE TITLE
Change textures of objects

### ISSUE THREAD

**Issue by KITT3000** [RealismusModding/FS17_seasons#492]
Will it be possible to change texture on objects? For example, I would like the roofs of homes to snow in the winter, now I have to add a snow model on the roof which takes a lot of time and it would be easier if I could define the texture for the object in winter and for the rest of the seasons. It is possible??

**Comment by joskuijpers** [comment]
Sure you can, like trees or anything else.
Make sure the object as a good name and then to the same thing maps do for adding new textures.

However, we currently have no support for 'snow' textures :( We will be adding this later.

**Comment by KITT3000** [comment]
Ok, thank for answer.
