### ISSUE TITLE
Help requiered for custom trees

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#493]
Hi again me, I would want to know if you have some way to follow a (video tutorial) like you teach in your manual map maker (section how to add custom trees or or other object :/), but textures FS usage are very special if I'm not mistaken and I'm hang to that sure other peoples too, especially for transparencies and / or light transparencies, soiling. Can we wait for a way like this request?
Thanks

**Comment by Dzi4d3k** [comment]
@Anonymous-any 
Please be advised that Seasons issues section is not for general help on FS related matters. To avoid unnecessary time consumption by Seasons author please post only confirmed issues with Seasons mod and not unrelated questions.

**Comment by Anonymous-any** [comment]
It's ok where I can suggest that request have you another way?

**Comment by Dzi4d3k** [comment]
Well, you can ask on Modding Help section on FS-UK forum:
https://www.fs-uk.com/forum/index.php?board=8.0

**Comment by theSeb1979** [comment]
Or join our slack.

**Comment by Anonymous-any** [comment]
Thanks for answer guys I have the language barrier well it is not serious I had thought that its could have served to other so much worse I will not do anything then or when the time will come (after other in other words).

**Comment by Dzi4d3k** [comment]
Well, but there're also French modding forums, aren't they? Personally, I didn't know any, but there is plenty of French mods, so I assume that there are also forums.

**Comment by Anonymous-any** [comment]
Maybe yes maybe not French are not really share information's. I was just thinking it will be fine if there a complete full tutorial like video linked to the manual how to custom textures tree/objects that all. Like I already say maybe one day I found a related teach video seasons textures...
Br
