### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by criss20ster** [RealismusModding/FS17_seasons#494]
I have this trouble for my game in my log

Error: Running LUA method 'loadMapFinished'.
D:/ModyFS17/mods/FS17_seasons_develop/src/environment/ssDaylight.lua:166: bad argument #1 to 'sin' (number expected, got nil)

**Comment by joskuijpers** [comment]
When did you download seasons from GitHub?

If you want to play and not test, make sure you use the ModHub download

**Comment by criss20ster** [comment]
I downloaded from some 2 weeks ago. So the version of mod hub is the most

**Comment by joskuijpers** [comment]
Please use the version from ModHub
