### ISSUE TITLE
Update textures and daylight from BB

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#497]

**Comment by joskuijpers** [comment]
- [ ] Update textures
- [ ] Update daylight data
- [ ] Test FPS with winter trees (LOD as well)

**Comment by joskuijpers** [comment]
Hahahahaha. Thinking that would be quick.

A lot of new textures optimized for looking great.

- [ ] Remove all existing textures except treeBranch
- [ ] Remove existing i3d config
- [ ] Start from the beginning

**Comment by joskuijpers** [comment]
Next:
- fix winter normals
- daylight

**Comment by joskuijpers** [comment]
It is all in now.

Map makers should update their shrub textures.

**Comment by joskuijpers** [comment]
Error: Can't load resource '(obfuscated)/mods/FS17_seasons/resources/replacementTextures/winter/birch6LOD_normal.dds'.
Error: Can't load resource '(obfuscated)/mods/FS17_seasons/resources/replacementTextures/winter/oakBranch_normal.dds'.

**Comment by joskuijpers** [comment]
Errors have been fixed.

I think it can be merged. @theSeb1979

**Comment by theSeb1979** [comment]
Ok. Go for it.
