### ISSUE TITLE
Modify straw swaths output for barley and wheat to match real life

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#5]
Looks pretty easy to do, but need some real life info on this.

**Comment by joskuijpers** [comment]
Don't forget to incorporate the different 'costs of living' in the game, and that one would want to buy machines far more often than a farmer would in real life.

**Comment by joskuijpers** [comment]
I suggest we dont do this anymore and let another mod do it. I think it is quite correct already?

**Comment by theSeb1979** [comment]
Closed. Will not be implemented in the foreseeable future.
