### ISSUE TITLE
Cuts of Hay

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#500]
How many cuts of hay per season are there?  Is there a way to set up so we can get at least 3 cuts of hay per season because of now it seems there is only one.  Perhaps not for the 3 day season but for the longer seasons it would be nice to have grass grow faster for 3-4 cuts.

**Comment by joskuijpers** [comment]
You have 3 to 4 cuts per _year_, which is akin to real life.
Don't forget your can fertilize grass fields.
