### ISSUE TITLE
Unofficial download?

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#501]
I see this website purpose your mod on 2 host.
http://www.fs17.co/mods/useful-things/scripts/contest-seasons
I report you maybe normal idk Br

**Comment by joskuijpers** [comment]
Those sites can't be stopped.

**Comment by Anonymous-any** [comment]
You have copyright you win as complaint

**Comment by theSeb1979** [comment]
Yes, but it's a pointless game using DMCA take downs unfortunately

**Comment by Anonymous-any** [comment]
If I do what you do then Court trial plus you win money easy !
