### ISSUE TITLE
FrozenLake object

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#502]
Is there a working map or GE exam with this feature of frozen lake.  I duplicated my water planes, assigned them to material ssIcePlane_mt.  Should they be visible in GE?  Should the actual shapes be named ssIcePlane?  As of now only the material is named ssIcePlane_mt.

Thanks

**Comment by joskuijpers** [comment]
You have to add a user attribute of type script with value `ssIcePlane`.

**Comment by Anonymous-any** [comment]
is this like this?
`
      <Attribute name="script" type="scriptCallback" value="ssIcePlane"/>`

**Comment by joskuijpers** [comment]
`ssIcePlane.onCreate` actually. sorry for the misinformation

**Comment by lindbejb** [comment]
thanks
