### ISSUE TITLE
Multiple materials object problem

### ISSUE THREAD

**Issue by Anonymous-any** [RealismusModding/FS17_seasons#503]
A house have materialIds="196,197,198,195,199" as example more than one as you can see, well at start I've put only the good number of material I would want to texture change but it appear (mean good settings) not on the roof of the house (snow roof) but on the side no good :/, after I've added all materials in replacementTexturesMaterialHolder of course and linked the needed textures to the maps was ok but the texture snow roof not appear what i'm wrong or is there a some restrictions with multiple materials in same object? I tried that because of https://github.com/RealismusModding/FS17_seasons/issues/492

EDIT: ok after I see inside the original replacementTexturesMaterialHolder it seem there is no way to manage multiple materials sad cause that mean the house must go in a 3d program for split the roof at time and lots works in GE depending maps :/ I give up
Br ;)

**Comment by joskuijpers** [comment]
Sure there is a way to do multiple materials.
Just put multiple materials in the material holder, and add multiple materials to the replacement shape at the bottom.

**Comment by Anonymous-any** [comment]
I do what you ask "after I've added all materials in replacementTexturesMaterialHolder of course and linked the needed textures to the maps was ok but the texture snow roof not appear" you ask to do all that in the replacementTexturesMaterialHolder.i3d right?

**Comment by joskuijpers** [comment]
What season do you put this in?

Just do it like we do the trees. Not much more I can say, really.
I think we have info on the website.

**Comment by Anonymous-any** [comment]
winter sure what bothered me was the fact of having several materials on the house and the texture is not displayed in the right place and can not manage to change its place either what makes me think having no Example that may be several materials do not work I do not know.

**Comment by Anonymous-any** [comment]
I have done Maestro ! I was not add position, rotations, etc !! sad of me so sorry for disturb...
Br
