### ISSUE TITLE
Warning: Compatibility

### ISSUE THREAD

**Issue by sootysax** [RealismusModding/FS17_seasons#505]
found this in the log:

Warning (compatibility): Texture C:/Users/ScottM/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/resources/gui/dev.dds width or height doesn't equal 2^n.
 
https://gist.github.com/sootysax/d45729c8ea93d7227eb1a01e0f440a8c

**Comment by theSeb1979** [comment]
This will happen in the GitHub version. Not a problem.

**Comment by Dzi4d3k** [comment]
I've uploaded to Slack 512x128 version, so there will be no more warning, but ssMain.lua need adjustment to no to squeeze image to previous 384 pixels wide.
