### ISSUE TITLE
Editing planting/harvesting times

### ISSUE THREAD

**Issue by jcuts33** [RealismusModding/FS17_seasons#506]
This is the mod that I have waiting for! Very excited about it! Great Job!

I am trying to figure out how to change some of the planting and harvesting time frames. I'm from the Great Lakes region and in our area we are able to cut wheat in mid summer and plant beans for a double crop that year. I have messed around a little with the mod trying to figure out how to do this and have found I don't have quite enough knowledge to be able to successfully do this.

**Comment by joskuijpers** [comment]
Hello! Thanks!

We are working on a MidWest USA GEO mod. That might fit your experience.

**Comment by jcuts33** [comment]
Awesome! Thanks you

**Comment by joskuijpers** [comment]
It is not finished though but will be released soon.
