### ISSUE TITLE
Trouble season a SVPA-AGRO

### ISSUE THREAD

**Issue by criss20ster** [RealismusModding/FS17_seasons#508]
For some time now I have a problem. Namely, I have all the SVPA agro mods, including the modem season on the norgecreast valley 2.0 map. Whenever he does all the fashion and svpa without meat, the game starts. However, as in all games it stops and nothing happens.

Pleas help me

**Comment by joskuijpers** [comment]
Yeah, that is not how this works. As in, Focus is wrong.

I have seen this before on other maps. Do you have a link to the map?

**Comment by criss20ster** [comment]
http://norgeholm.bplaced.net/

**Comment by criss20ster** [comment]
And how does someone know the solution?

**Comment by theSeb1979** [comment]
Do you have the latest CD mod from Giants modhub? Otherwise there is a problem with the map or this svpa Agro mod.

**Comment by criss20ster** [comment]
Yes a i have new version in mod hub site but a i have founded mod  error fix but i don't have a fixed

**Comment by theSeb1979** [comment]
I do not see how this is related to Seasons so closing this.

**Comment by criss20ster** [comment]
And I would have a hot request to you, could you brush this mod under the map of Norge Creast valley?
Because how to disable this mod season is playing load without error and save about which I posted with the problem it loads normally
