### ISSUE TITLE
Suggestions: Variable night fast forward & AI pay rates

### ISSUE THREAD

**Issue by pops64** [RealismusModding/FS17_seasons#519]
Sorry if this isn't a great place for suggestions. As the title says having to wait until 2000 to use the mod's function to fast forward isn't very fun if it is dark at 7. Yes, I could use 120 speed but it would be nice to have the option to fast-forward starting at sunset and go until sunrise instead of hard coded to 2000 and 0600. And the other suggestion is to have a setting to adjust or turn on/off the AI pay rates or if you have the game extensions mod for it to be able to over write what seasons set the wages too. I use primarily CP for the AI but the conveyors which charge you AI rates just to rotate doesn't really make sense to me. So having an option to turn this off would be nice. Sorry that this turned into a book. A very interesting mod you have here. Thanks for the hard work.

**Comment by joskuijpers** [comment]
You can start skipping night from 20:00 or when the sun is down, if that is later.
It will skip to sunrise, unless sunrise is after 6AM. Then it will skip until 6AM.
There are good reasons for this: a farmer wouldn't wake up at 10AM for the sun. Sleeping before 20:00 was deemed unnecessary, as you still have to put the time in the day. (And so you don't accidentally skip night at 5PM)

Removing AI rates for conveyors seems to me as an issue for a separate mod as this is vanilla behaviour.

**Comment by theSeb1979** [comment]
Conveyor belts charging ai rates makes perfect sense. You would have a person standing next to it to operate.

**Comment by joskuijpers** [comment]
The AI rate changes is working as intended. If GE wants, it can just override it, but our values are gameplay related.
