### ISSUE TITLE
GUI dialog - warning is not appropriate for what is being changed

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#526]
For example, if snow layers is changed, then a message warning about changing season length comes up. This message should only show if season length is changed. The warning must not show if other settings are changed by the user.

**Comment by joskuijpers** [comment]
when chsanging season length or snow mode, the warning is shown. We did this by design.

Do we want to disable the message for changing snow height?
It is there for snow because 48cm snow inside buildings where you store stuff is a mess. It is non-destructive though, in the end
