### ISSUE TITLE
FJM does not adhere to the planting calendar

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#531]
Use GM canPlant and canHarvest.

**Comment by baleBaron** [comment]
Using canPlant and canHarvest data will not be easy.

If the planting window for crop C1 and C2 is different, one of those crops will never be planted.
Imagine crop C1 will be planted in GTx and C2 in GTx+1, in GTx FJM will simply put in a different crops when it can't plant C2, so C2 will never be planted.
The only way to fix this is to control what fruitType will be planted in what fieldIndex, and this adds a lot of complexity when I don't think it's needed. 

I suggest a simpler fix:
Allow the planting and harvesting windows to be specified in the growth.xml and let this data be used for every fruitType.

An example FJM configuration that behaves like the current hard coded one:
```
<fieldJobManager>
    <NPC>
        <cultivate minGT="1" maxGT="3">
        <plant minGT="3" maxGT="3">
        <harvest minGT="9" maxGT="9">
    <NPC>
    <missions>
        <plant minGT="1" maxGT="3">
        <harvest minGT="1" maxGT="9">
    </missions>
</fieldJobManager>
```
Non specified jobTypes (like fertilization or player cultivating missions) must be allowed whenever possible.

I think this suggested fix has a light implementation and it does not change our tried and tested behavior of the current FJM.

**Comment by joskuijpers** [comment]
I don't see how this does not have the exact same issue you describe

**Comment by baleBaron** [comment]
Because when NPC harvest minGT = maxGT every crop will be planted at the same time.

**Comment by theSeb1979** [comment]
I can work out maxgt for each fruit from canPlant and canHarvest. Will that not do the same thing?

**Comment by baleBaron** [comment]
Sure, do that then. I still think this will be much more complex.
Just have the AMT in mind with possible special fruitTypes that may mess this up.

I'm worried about cases where no single GT exists for every fruit type to be planted, but we still need to pick the one that makes most sense.
I suppose if you consider the frut.useForFieldJob it's easier to reject grasses and such.

**Comment by joskuijpers** [comment]
Just find the one with the most fruits. Maybe one fruit is not in the missions, oh well...
