### ISSUE TITLE
stripes in the fields

### ISSUE THREAD

**Issue by s1100** [RealismusModding/FS17_seasons#538]
Hello,
you build a great mod, thanks for this!!

But, i have a problem with the stripes on the field, you can see it on the pictures.

This is the 4x SüdThüringen Map, where i have the problem.
Is this a "seasons" problem or a problem of the Map? when it is a map problem i must live with it.

Kind regards!!

![fsscreen_2017_08_02_13_14_08](https://user-images.githubusercontent.com/30638928/28871456-e1aec3e4-7784-11e7-98c6-9df54e3929ac.png)
![fsscreen_2017_08_02_13_15_09](https://user-images.githubusercontent.com/30638928/28871455-e1ae94b4-7784-11e7-8bc0-a4818edde756.png)

**Comment by theSeb1979** [comment]
It is a problem with the map and how it is set up. We will look at if we can do something about it because this is my favourite map from FS15 and I have spent about 400 hours in it.

**Comment by s1100** [comment]
thanks, i do love this map and play it many hours.
i hope you have an idea for changing this problem.

Thanks

**Comment by theSeb1979** [comment]
Are you using version 1.1 of Seasons (update on modhub) or the contest version. Can you attach your log file please.

**Comment by s1100** [comment]
Yes, i have V1.1

i don´t test the V1

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1193665/log.txt)

**Comment by theSeb1979** [comment]
In that case you can fix this issue yourself.

\fruit_density.grle and terrainDetailHeight_density.grle need to be the same size

Use Giants grle exporter, rescale and reload and save in editor

@Dzi4d3k (one of our testers and translators) might be able to give you better help. Or join our slack. 

slack.realismusmodding.com

**Comment by s1100** [comment]
Thanks,
i am not a good modder or mapper.
i don´t find the files.
it´s better when a person wright to me in german.

**Comment by Dzi4d3k** [comment]
@s1100 
Unfortunately I can't write with you in German, but problem is caused exactly by what @theSeb1979 wrote you.
Both files (ended with .gdm extension in FS17 not .grle) are in \maps\map01 folder inside you map zip archive. However it may be not so easy to rescale terrainDetailHeight_density file as in my case it was auto resized back to wrong dimensions by Giants Editor. Unfortunately I didn't manage yet to find what have to be done to prevent that. Workaround was to use vanilla map Gold Crest Valley files to and move all map scenery.

**Comment by s1100** [comment]
Ok, it is to high for me, i live with the stripes :-)

Thanks to everyone

**Comment by Dzi4d3k** [comment]
Well, I think, that's is wrong way, and the problem is no so hard to fix. I would be great with author of map would go and fix it, however this map seems to be one of great ones left by their authors in beta for die :(

**Comment by s1100** [comment]
Yes, many people play this map, and nobody convert this map correctly for fs17. 

It´s much work to generate the ".gdm" files new?

**Comment by Dzi4d3k** [comment]
Well, resizing .gdm files is not a thought work, just use GRLE Converter 7x from Giants GDN site to make png files, resize them to correct size, for 4x map all density files should be 8192x8192 I think, and replace them in map folder (remove gdm and leave png there) run Giants Editor and save map. Should work, but as I wrote my colleague had problems with this.
I'll test myself in free time, unfortunately I don't have much of it now :(

**Comment by s1100** [comment]
Ok, i test it tomorrow and give you a answer

Thanks

**Comment by s1100** [comment]
Hello again,

good news, i changed all "density" files to 8192x8192 pixel and it works greatful

I seeded one row and i have no stripes :-)

A great THANKYOU for your help

![fsscreen_2017_08_03_12_19_34](https://user-images.githubusercontent.com/30638928/28917608-825b7c30-7846-11e7-9c66-ea06891053c5.png)

**Comment by theSeb1979** [comment]
Great news.
