### ISSUE TITLE
throw an error if all densitymaps do not have the same size

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#539]

**Comment by Dzi4d3k** [comment]
I suggest something like SoilMod has in FS15 :)

**Comment by joskuijpers** [comment]
@Dzi4d3k what has SoilMod in FS15?

**Comment by Dzi4d3k** [comment]
Starting from line 140:
https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/blob/71715529d52de6fc2e44c48d7cd9f05f78be05df/SoilManagement/soilMod/fmcSoilModPlugins.lua#L140

**Comment by joskuijpers** [comment]
Not sure i need to check more density maps
