### ISSUE TITLE
[GM] Impact on normal trees

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#54]
Need to investigate what to do with trees since GM switches growth off.

**Comment by Dzi4d3k** [comment]
Just an idea:
Trees have longer growth times and in temperate climate they don't grow in autumn and winter.
How about grow them one stage by "Seasons year"? Or two stages (for impatient players - a settings?) - one in late spring and one in late summer?

**Comment by theSeb1979** [comment]
I am currently not even sure what impacts the growth settings have on trees, if any, since they are not a normal fruit.

**Comment by theSeb1979** [comment]
@joskuijpers has tested this in the game and the growth setting does not impact the trees, so they grow independently. Maybe in the future we can look at trying to change it.
