### ISSUE TITLE
Adding frozen lakes and waters / Adding season-based

### ISSUE THREAD

**Issue by MrHeector** [RealismusModding/FS17_seasons#541]
Hi. I want to ask if you guys, can make a little guide or just help me how to make frozen plane for water/rivers to work and adding season-based objects as well. I did not found any guide for this and in Info for Map Makers there is just said, it is possible to add season based object... But how? I have on my map objects like tomatoes or lettuce... in gardens and i want them to disappere them during winter and add frozen river, but do not know what to do exactly from the Info for Map Makers. (Make it a ssIcePlane object) should the object have name: ssIcePlane? Or it have to be something in user attributes i suppose?

**Comment by theSeb1979** [comment]
Please join our slack (link is on our website) and you can get help on this there.
