### ISSUE TITLE
Sugar Beet growth/harvest times not shown on chart

### ISSUE THREAD

**Issue by dieselfuelonly** [RealismusModding/FS17_seasons#542]
Am I missing something here?

Singleplayer world on Goldcrest

Mods:
Seasons 1.1.0.0
US Midwest GEO
More Realistic
Kuhn Pack
Drive Control
GPS
Fast Forward (modified for max speed of 6000)

Here is a screenshot of the growth chart
http://i.imgur.com/7j9oDQ9.jpg

**Comment by reallogger** [comment]
We based the Midwest GEO on Missouri where beets are not grown. Therefore we left beets out. So the mod works as intended. We understand beets are grown further north in the Midwest, especially in Minnesota, but this is not what we based the mod on.
