### ISSUE TITLE
ssGrowthManager.lua:534

### ISSUE THREAD

**Issue by ChillyUK** [RealismusModding/FS17_seasons#543]
Sorry if this isn't the right place to report.

Plain server only, mods are seasons and Parkers Prairie (my map)
Error in log:
C:/Users/Ian/Documents/my games/FarmingSimulator2017/mods/FS17_RM_Seasons/src/growth/ssGrowthManager.lua:534: attempt to index a nil value

Works fine on single player with no errors 
Error appears using seasons 1.1 and development version.

**Comment by theSeb1979** [comment]
I suspect that you added a fruit to your map, but didn't actually add it properly, That's the only way to get this error. Please fix your map.
