### ISSUE TITLE
Release notes v1.2

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#546]
New features
- Added a measurement tool to get information on trees, bales, crops and more.
- Added economy information in the Seasons menu, with historic data for a year.
- Added a ground wetness model.
- Animal production is made dependent on the average productivity over time.
- Skip Night can skip to either morning or dawn.
- Skip Night works in multiplayer now too.
- Machinery does not become dirty when the ground is frozen.

Fixes
- Fixed Esc GUI showing the repair interval wrongly.
- Vehicle demo did not account for configurations in sell price.
- Fixed growth debug console commands which stopped working in 1.1.
- Updated text in manual about grass bales.
- Fixed edge case bugs when dealing with new fruits.
- Fixed economy factors on fruits and animals, now correct.
- Fixed bug in repair cost for old machinery.

Improvements
- General code refactor and improvements.
- Increased performance when loading game.
- Better handling of fruits in growth file that aren't in the map.
- Forecast and day information is now sharper and better aligned.
- Added check for density map sizes.
- Loan cap is now 80% of equity instead of 30%.
- Better model for snow melting.
- Upkeep of pigs has been reduced and birthrate has been increased (i.e. improved profitability).
- Game difficulty no longer affects crop moisture.
- Repair factors for conveyors and front loaders added.
- Sell price decrease of machinery made more consistent with increase in repair cost (functions of age and operatingTime).
- Straw and hay bale prices are brought back to vanilla level, while silage bale prices are lowered to be more in line with the hay bale price.
- Potatoes and sugar beets can be harvested when crop is wet.

Notes
- The 4Real Module Crop Destruction patch has been removed, as Giants fixed the mod.
- Added warning about fruit density layers not being same size as terrain.
- Alpha Blending of tree billboard is now turned off by default.

**Comment by joskuijpers** [comment]
Huh? Update in GUI? we decided that a toggle will be made?

**Comment by theSeb1979** [comment]
Not sure what you mean but there was a bug in the GUI for the repair interval after the repair interval was changed to once a year

**Comment by joskuijpers** [comment]
Ooh

**Comment by joskuijpers** [comment]
Sent to giants. Notes can be seen at https://www.realismusmodding.com/mods/seasons/manual/release_notes.html#version-120
