### ISSUE TITLE
Add Skip Night in multiplayer

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#549]
Complicated to get it working right, but this might work:

1) client sends event to server, to skip night, available if admin
2) server checks if not already skipping
3) server sends event to all clients and starts skipping night
4) all clients show the skipping nigt display and skip night themselves (for visuals). Clients also close the skipnight dialog if open
5) when server is done skipping night, an event it sent to all clients indicating it is done (possibly force sending of TimeSyncEvent)
6) clients get the event, then wait for a TimeSync event. When received, dismiss dialog

**Comment by joskuijpers** [comment]
Don't forget about local multiplayer

**Comment by joskuijpers** [comment]
Implemented

**Comment by Dzi4d3k** [comment]
Marvelously!
