### ISSUE TITLE
Vehicles with a 'free worker' cost money with Seasons enabled

### ISSUE THREAD

**Issue by Timmiej93** [RealismusModding/FS17_seasons#553]
Vehicles that have a 'free worker' (XML file's ai.costPerHour = 0), simulating an autonomous vehicle, like a conveyor belt or the [Lely Juno 150](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=58638), do cost money with Seasons enabled. 
I tested this on a mod map and GCV, no other mods enabled. Looking at the code seems to confirm my findings.

**Comment by joskuijpers** [comment]
Are you sure this is AI cost and not just cost of maintenance?

**Comment by Timmiej93** [comment]
Well, I'm not 100% sure how maintenance cost works with seasons, but the costs only occur while the hired help is running, not when the machine is turned on without hired help, so I don't think it would be maintenance.

To test this, I started a new save, cheated in money, bought 5 Lely Juno's. Then I waited around a bit with nothing running, checking my money. No changes. I started a helper in each Juno, and the money started to drop, quite rapidly. I did the test yesterday, so I can't be exact, but it was a drop of more than 1 dollar per second.

**Comment by joskuijpers** [comment]
Interesting. I heard lechatnoircynique about it. He said what he did was set a negative hourly cost equal to the cost of a hired worker. Something like that, so that the end result was 0.
But we change the hourly cost of workers (we lower them though…, during weekdays between 6-18).

So no, still no idea what is going on.

**Comment by Timmiej93** [comment]
I've been looking at the code a bit, but haven't seen anything like the negative hourly cost you mentioned. The only thing regarding AI cost I could find was [this function](https://github.com/RealismusModding/FS17_seasons/blob/b78d40e0897f5003dde78aadb39abe1711407dba/src/misc/ssEconomy.lua#L221). I'm not at all familiar with the organisation of the files in the mod, so it could simply be that I'm missing something, or that lechatnoircynique mentioned it as a possible fix for this issue.

My personal suggestion would be to simply obtain the self.pricePerMS value from the vehicle as-is [(line 122 in the load function of AIVehicle)](https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=3407#load46146), and apply a multiplier to that when in overWorkHours. That would probably be the easiest and most fool-proof way to do it. Zero times a modifier remains zero, any other value is correctly scaled. Maybe check for negative values though, so that a vehicle with a negative AI worker cost doesn't produce extra money in overWorkHours (whatever the reason for a negative worker cost may be).

**Comment by joskuijpers** [comment]
I think that might be it. Can you try my latest commit on develop?

**Comment by joskuijpers** [comment]
I fixed it now by just checking if it is 0.  I could check if it is the vanilla value, but I don't feel like doing that, currently. It is late, also. If you prefer it fixed that way, you can even submit a pull request 😄
