### ISSUE TITLE
Adding Extra Fert States

### ISSUE THREAD

**Issue by Willykeen** [RealismusModding/FS17_seasons#557]
Hi Realismus Team! 
I have an idea for a new feature. 
the ability to change from 1 right through to 6 fert states.
it is quiet unrealistic to only fertilise or spray 3 times. some farmers fertilise up to 6-7 times a season.

**Comment by joskuijpers** [comment]
We will not be doing this, for a couple of reasons:

1) This means we need to overwrite the vanilla system
2) We think 3 states is enough for most. In some areas they might spray 2 times, or just once.
3) This is not SoilMod.

We have a bunch of other features planned to keep you busy ;)
