### ISSUE TITLE
Bugliste Seasons-Mod Version 1.1.0.0

### ISSUE THREAD

**Issue by Pandahma** [RealismusModding/FS17_seasons#558]
1)	Die Kombination Zunhammer SKE 18.5 PUD und AMAZONE Catros 6002-2 funktioniert nicht, es wird keine Gülle auf das Feld aufgetragen. (SP, MP und Dedi).
2)	Bei den Missionen gibt es keinen Zeitbonus mehr.
3)	Error: Running LUA method 'update'. C:/Users/Pandahma/Documents/My Games/FarmingSimulator2017/mods/FS17_RM_Seasons/src/growth/ssGrowthManager.lua:534: attempt to index a nil value. (nur auf dem Dedi)
4)	Seit dem Update von 4Real Module 03 - Ground Response auf die Version 1.0.2.0 gibt es folgende Fehlermeldung (nur auf dem Dedi):
Physics: wheel shape not found, object caseIH1455XL wheelShapeIndex 0
Physics: wheel shape not found, object frontAxis wheelShapeIndex 0
Physics: wheel shape not found, object newHolland8340 wheelShapeIndex 0
Physics: wheel shape not found, object frontAxis wheelShapeIndex 0

Viele Grüße
Pandahma

**Comment by joskuijpers** [comment]
1) not a problem with seasons
2) is by design, we did that on purpose
3) that should be fixed soon
4) i don't see how this is a problem with Seasons either

**Comment by theSeb1979** [comment]
Fixed in develop. Will be released in 1.1.1
