### ISSUE TITLE
Include weeds

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#561]
Include weeds in the existing 2 bit layer that we have not used

weedLayer:
State 3: Good weed protection, no visible weeds
State 2: Some weed protection, no visible weeds
State 1: No weed protection, no visible weeds
State 0: Visible weeds

Every growthTransitionChange decrease layer by 1 unless it is winter (maybe use soilTemp > 5)
If state 0 at growthTransitionChange, randomly place weeds
If state 0 at growthTransitionChange and at spots where weed is present, decrease fertilization layer by 1
Remove weeds when soil freezes

Use existing townDecoGrass as foliage for weed. If map does not have townDecoGrass installed, disable weed feature

Specs:
Mower: Remove weeds, output nothing (make sure the mower outputs grass if that is present)
Cutter: Remove weeds, reduce yield
Cultivator and plough: Remove weeds and reset weedState to 3
Sprayer: Increase weedState by 2 (restrict spraying if too much wind)
Weeder: Increase weedState by 1 (can only be used in the first crop states, same as vanilla)

**Comment by Willykeen** [comment]
idea: 
would it be possible to cut, say a wheat or barley crop at the last two growth stages that has a WeedLayer state of "0" and have an output of Wet Grass? this would simulate a farmer with a "failed" crop cutting wheaten or "oaten" hay.

**Comment by reallogger** [comment]
@Willykeen This is similar to the MultiMowing mod for FS15. It has nothing to do with this new feature (weeds) and is not something we are planning to implement. In vanilla you can also do whole crop so there are possibilities for "failed" crops already,

**Comment by reallogger** [comment]
No need to implement this anymore :)
