### ISSUE TITLE
Ingame notifications are underneath the weather forecast. 

### ISSUE THREAD

**Issue by Timmiej93** [RealismusModding/FS17_seasons#562]
The ingame notifications seem to be below the weather forecast window, like can be seen in the screenshots below. Strangely, I know that the message should show below the forecast window properly, and that it does for others (seen it happen on YouTube videos), and looking at the code that handles the location of those messages, it should work just fine. I thought it would be caused by my uiScale being at 70%, but it happens with it at 100% as well.

![fsscreen_2017_08_14_16_50_08](https://user-images.githubusercontent.com/16491748/29282196-30bfcfe0-8122-11e7-80cc-200f398bfe87.png)
![fsscreen_2017_08_14_16_50_18](https://user-images.githubusercontent.com/16491748/29282195-30ba4570-8122-11e7-9258-e9e91e84f2d4.png)
As you can see in the above two images (same notifications, I only hid the UI when I noticed this), the height of the notification does change (mostly noticeable when quickly switching between both images), it just doesn't seem to move downwards enough.

![fsscreen_2017_08_14_18_49_59](https://user-images.githubusercontent.com/16491748/29282194-30b9b2e0-8122-11e7-9461-7b5c0e07fc69.png)
This screenshot is taken on a test map, confirming that the issue also occurs on 100% uiScale.

**Comment by theSeb1979** [comment]
Looks like you have another mod which also adds notifications?

**Comment by Timmiej93** [comment]
Yes, one of my own WIP mods. These are shown with `g_currentMission:addIngameNotification()`, as normal. As you can see in the top two screenshots though, it also happens with only default notifications. I'll check without my WIP mod though, might still cause it.

**Comment by theSeb1979** [comment]
We tested it with only default notifications and didn't see this. What resolution are you using?

**Comment by Timmiej93** [comment]
Yeah, I know it should be working, since I've seen it work for other people. I'm on 1920x1080. The log doesn't show any errors at all.

**Comment by theSeb1979** [comment]
That is odd. We will have to try and reproduce and fix since it is not an unusual resolution. I also use a scaled GUI and have not noticed this.

**Comment by Timmiej93** [comment]
Let me know if you require any information, or need me to try something out. I'm happy to help where possible.

**Comment by Timmiej93** [comment]
It seems like updating to the latest dev build resolved the issue. Don't know how though, my previous build is from about 24 hours ago, so unless something regarding these messages changed in this time span, I guess this is a mystery.

**Comment by joskuijpers** [comment]
I fixed this last night, at like... 10PM

**Comment by joskuijpers** [comment]
So yes, stuff happens here all the time :p

**Comment by Timmiej93** [comment]
I should really learn to update to the most recent version before submitting an issue, even though my running build is still very recent. It's pretty clear that you guys fix stuff continuously. Sorry for the unneeded report!

**Comment by theSeb1979** [comment]
It's really not that huge a mystery. It used to work perfectly, then Jos broke it (and you have a broken build) and then Jos fixed it again last night 👍
