### ISSUE TITLE
dev.dds gui file missing, resulting in an error

### ISSUE THREAD

**Issue by Timmiej93** [RealismusModding/FS17_seasons#563]
A very minor error, but since I noticed it, I thought I'd report it.
> Error: Can't load resource 'D:/Data/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/resources/gui/dev.dds'.

**Comment by reallogger** [comment]
I believe this was fixed in ad301af

**Comment by Timmiej93** [comment]
Definitely looks like it. I forgot to update my dev version before reporting, sorry about that.

**Comment by Timmiej93** [comment]
For future reference, is there an easy way to search through commits etc.? I searched for 'dev image', but didn't find anything, which lead to the assumption that it had gone unnoticed.

**Comment by theSeb1979** [comment]
You use the git hub search and select commits, but in this case the commit text was not as informative as it could have been

https://github.com/RealismusModding/FS17_seasons/search?q=dev.dds&type=Commits&utf8=%E2%9C%93
