### ISSUE TITLE
Seasons "Farmers hand"

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#567]
### Possible features:
Always shown (print value from g_seasons.environment):
- Crop moisture

Additional when in field (by getDensity func):
- Crop type
- Crop maturity, growth stage, anticipated time of being harvestable?
- Field compaction (average over field or in nearby area)
- Crop yield (only shown when harvestable)
- Whether field will absorb fertilizer (ty OlavEmil for the idea :) )

Additional when near object (by raycast):
- Bale fermenting status or time left to ferment
- Tree growth stage and whether the tree is still growing or has stopped

**Comment by Dzi4d3k** [comment]
Extension to Game Extension? :)

**Comment by joskuijpers** [comment]
No, Xentro quit, many times

**Comment by Willykeen** [comment]
this will be a brilliant feature!

**Comment by joskuijpers** [comment]
@reallogger any suggestion on how you want this to work?

**Comment by reallogger** [comment]
Have not come that far. Just felt a need to get it written down. :)
Idea: A key combination for toggling on/off. The information displayed will depend (see updated first post).

**Comment by joskuijpers** [comment]
Hmm, I might feel more for either:

- A ‘fancy looking’ handtool, to prevent adding another key. When clicking on something with the hand tool, it might be displayed with some GUI element still. (Think http://www.flir.com/uploadedImages/Instruments/Products/Test-and-Measurement/FLIR-Test-Measurement-Electrical-Tools.png <http://www.flir.com/uploadedImages/Instruments/Products/Test-and-Measurement/FLIR-Test-Measurement-Electrical-Tools.png>)
- A single key, that when you hold shows the info. So not a toggle.

Both feel more natural and less like a cheat to me, I think.

**Comment by Willykeen** [comment]
why not something along the lines of the "farming tablet"
here in aus farms have everything electronic, moisture meters for example that all get sent back to a tablet or computer system. i think this will be more "concentrated" for whatever a word.
everything in one place so to speak.

**Comment by joskuijpers** [comment]
I hate tablets. Not going to happen.
Also, there needs to be an interaction with the screen-pointer, for bales and such, and that is annoying with such a 'tablet'.

Aren't there enough tablets yet?

**Comment by Amadeo01** [comment]
I'm with you @Rahkiin. 
The feature should be activated by interacting directly via screen-pointer in the game and not via the detour of a Farming tablet. :-)

**Comment by joskuijpers** [comment]
Think ![](http://www.flir.com/uploadedImages/Instruments/Products/Test-and-Measurement/FLIR-Test-Measurement-Electrical-Tools.png)

and

![image](https://user-images.githubusercontent.com/5017040/29426241-4e9dd2b2-8386-11e7-88d9-51b3377ce16f.png)

**Comment by HansJDen** [comment]
I like the idea of a single key pressed to show the value.

**Comment by joskuijpers** [comment]
We got a model from Wopster, and it is now a handtool called the `Wopstr 420`. It has been integrated into the store with its own brand.
The handtool code is coming along. Measuring works, objects and terrain and trees are found and data is available.

Next step is implementing a nice GUI system for the info, and then showing the data for each measurement-target.

**Comment by joskuijpers** [comment]
- [ ] Add moisture
  - [ ] Add symbol to texture
  - [ ] Add to terrain measurement

**Comment by joskuijpers** [comment]
![image](https://user-images.githubusercontent.com/5017040/30284576-90fce5fa-971b-11e7-9f80-4ede0e667b9a.png)
![image](https://user-images.githubusercontent.com/5017040/30284588-a0a9edd6-971b-11e7-8e0c-44eb073fe4ca.png)
![image](https://user-images.githubusercontent.com/5017040/30284596-a54ab942-971b-11e7-880f-c926f60fc32a.png)
![image](https://user-images.githubusercontent.com/5017040/30284599-ab12c6bc-971b-11e7-84c4-5d9ab1b40b16.png)
![image](https://user-images.githubusercontent.com/5017040/30284603-b14da9c0-971b-11e7-845a-436f34246c59.png)

**Comment by joskuijpers** [comment]
Disabled moisture again: it is too confusing at the moment.
There is:
- crop moisture
- soil moisture
The crop moisture will affect quality in 2.0
Soil moisture will affect compaction in 2.0

It must be made clear that water is not required for growth. So display of a 0% next to a water icon is no good.

So I am leaving it out of 1.2, so we can also make better icons.

**Comment by Dzi4d3k** [comment]
I suggest changing X and Z name of axis to something meaningful for ordinary user. I suppose that these unfamiliar with Giants Editor will not know how coordinate works.
I suggest instead go with W/E - West/East and N/S - North/South, so basing on current situation where 0X , 0Z is in center of map I suggest change to something like this:
--- 15 X, -15 Z ---> 15 E, 15 N (example from screenshoot)
--- -10X, 20Z ---> 10W, 20S
And so on.

**Comment by joskuijpers** [comment]
It does not need to be, as it is fictional. It is not a reference to the XZ coordinate system.
We discussed this, and we did not want to use NE because it is not a polar coordinate system, and it is not realistic either. So if you have the Lossberg map: the coordinates won’t be the actual Lossberg coordinates. So that is something we wanted to avoid.

**Comment by joskuijpers** [comment]
![image](https://user-images.githubusercontent.com/5017040/30291581-a9db0c1a-9733-11e7-85ae-f8c09171f411.png)


I liked how it was before, but my opinion got overwhelmed by those of others. So now the coordinates in the Wopstr are the same as the coordinates in the minimap except `cm` precision instead of `meter` (x100)

**Comment by joskuijpers** [comment]
I added a measurement beep sample as well, and the device now slightly moves when holding it.

I think it is ready to merge, unless someone can create a removing-from-pocket sound.

**Comment by Dzi4d3k** [comment]
Do you mean something like this:
https://www.youtube.com/watch?v=I8MsOJf0svk

**Comment by joskuijpers** [comment]
Merged. Have not added a 'pocket' sound.
