### ISSUE TITLE
issue with kuhn dlc

### ISSUE THREAD

**Issue by Willykeen** [RealismusModding/FS17_seasons#568]
Hi, just started on oregon springs, i added the code for a snow mask (didnt paint it in GE) 
only issue i am having is when i wrap square bales they ferment instantly, im playing on hard and have kuhn dlc, latest dev version of seasons, and the map in their own mods folder.

**Comment by reallogger** [comment]
Just tested with the Kuhn DLC and it works as it should. Can you post your log?

**Comment by Willykeen** [comment]
all good, was a conflict with another growth script i didnt realise i had active.
