### ISSUE TITLE
Snow Heaps 

### ISSUE THREAD

**Issue by Friendlyx** [RealismusModding/FS17_seasons#573]
I used a silage shield to plow away the snow on my farm. The heaps I created are melting too slow for my opinion. its 7 deg in mid spring first day, leaves got green and still snow heaps are present.

**Comment by reallogger** [comment]
What season length do you use and how high did you pile the the snow? Screenshot?

**Comment by Friendlyx** [comment]
season lenght is 9 days. in winter piled the snow as high as possible with the sweeping tire. screenshot comming

**Comment by reallogger** [comment]
Now if the piles are 4 m high (maximum possible in FS), then it should take a while before snow melts. 

But I also found a bug that can explain some of the slow melting. Thanks for making me aware of this. Will have to make a small improvement for the next version. :)

**Comment by Friendlyx** [comment]
![3](https://user-images.githubusercontent.com/6493968/29977883-3d3a8988-8f3f-11e7-8a6f-eb7d6c5b9423.jpg)
![1](https://user-images.githubusercontent.com/6493968/29977881-3d32725c-8f3f-11e7-825a-1efc1c0f8d6e.jpg)
![2](https://user-images.githubusercontent.com/6493968/29977882-3d34fdec-8f3f-11e7-8fb5-74928ff79957.jpg)

maybe its possible to implement that the snow is melting in the night before the first leaves appaer

**Comment by reallogger** [comment]
> maybe its possible to implement that the snow is melting in the night before the first leaves appaer

No that is not how we do things. Snow melting rate is dependent on air temperature and solar radiation (and soon wind). I just forgot to add some melting effect after the sun sets. Will make snow melt faster. 

That being said, IRL where I live there are many large snow heaps that have not melted when trees are getting green. So nothing unrealistic about this.
