### ISSUE TITLE
All crops turned to cut

### ISSUE THREAD

**Issue by davidhunt135** [RealismusModding/FS17_seasons#585]
I was playing and completed seeding my crops in mid summer (season length of 3 days). I then skipped the night to the next day and all of the crops on the map changed from seeded to a cut state. I think this is a bug as it happened to all fields whether I owned them or not. I am using the latest developer version. 

Also, I tried making some changes to the script to force a growth state on the next transition to reverse the issue and then undo my changes to restore the seasons mod to normal. I couldn't quite figure it out as I don't have script reference for the game. Would this be possible and if so then how? (I am a developer so I can do lua changes.)

Thanks

**Comment by reallogger** [comment]
Assuming you are not using a GEO with changed growth, no crops will grow if you plant in mid summer. Please consult the planting calendar (Alt + S).

**Comment by davidhunt135** [comment]
I thought I had followed the calendar but then I also thought it was mid summer so I have one or the other wrong. Is "CUT" the expected state if something is planted at the wrong time?

**Comment by reallogger** [comment]
Correct

**Comment by davidhunt135** [comment]
Ok, thanks for your help. Suppose I'll go reseed everything then
