### ISSUE TITLE
Strips on fields - 4-fold Maps

### ISSUE THREAD

**Issue by Sheldon311** [RealismusModding/FS17_seasons#587]
Hallo,
the fields still do not work properly. Also with the current develop version, it makes strips at the fields, on 4-fold maps. The grain strips have become wider, but you can still see thin strips without grain.
In the version 1.0 everything still worked.

I hope you can fix it for the next version.
Thank you!

**Comment by Dzi4d3k** [comment]
Hi @Sheldon311 
Nope, this is problem with your map. Please read:
https://github.com/RealismusModding/FS17_seasons/issues/538

**Comment by Sheldon311** [comment]
Thanks, I have read the article.

The fruit_density already had 8192x8192. The terrainDetailHeight_density was smaller. Now she is also 8192x8192.

And now I have again very thin grain strips.

What now?

**Comment by Dzi4d3k** [comment]
Did you started new savegame?

**Comment by Sheldon311** [comment]
yes

**Comment by Dzi4d3k** [comment]
Please verify .gdm files dimensions now in your new savegame (after you confirmed issue still exist), as this maybe the issue where Giants Editor (and probably also Game Engine) is changing dimensions for one of these files back to previous one.

**Comment by Sheldon311** [comment]
Yes in the new savegame the terrainDetailHeight_density.gdm is changed back to 4096x4096.

**Comment by Dzi4d3k** [comment]
So that's the cause, why problem still exists, but unfortunately I don't know why it happens. In may case (or rather my colleague) solution was to start making map on fresh 4x map, where density map files are prepared from beginning )with the same dimensions) and then move object (building, trees etc.) to it. Now I dunno any other solution yet.
What is the map you playing? Is it publicly available or it is a map you made?

**Comment by Sheldon311** [comment]
It is the "Südharz Map", made by me. A older version of this map ist publicly available, but now I´m working on a new Version. 


I have increased now all the other densitys to 8196x8196.
And now the fields work without Errors.

But now I get other graphics problems, shadows which do not belong there and other black things on the sky.
![fsscreen_2017_09_05_22_38_23](https://user-images.githubusercontent.com/20086741/30083131-a032b2ee-928d-11e7-8664-973ae3074b96.png)
![fsscreen_2017_09_05_22_41_45](https://user-images.githubusercontent.com/20086741/30083130-a02ed2a0-928d-11e7-98c4-21b84d450c5b.png)
![fsscreen_2017_09_05_22_41_51](https://user-images.githubusercontent.com/20086741/30083132-a035b764-928d-11e7-9be4-76ab03f44317.png)
![fsscreen_2017_09_05_22_41_53](https://user-images.githubusercontent.com/20086741/30083133-a04f1768-928d-11e7-977d-edab17eeaa82.png)

What could that be?

**Comment by Dzi4d3k** [comment]
Did you cleared shader_cache folder located in ...\My Games\FarmingSimulator2017?

**Comment by Sheldon311** [comment]
yes I have just done, has brought nothing :(

**Comment by Sheldon311** [comment]
with the FS17Contest_Seasons version makes it no problems, hmm

**Comment by Dzi4d3k** [comment]
But no problem regarding fields stripes or strange shadows?
It you writing about stripes with version 1.1, then that's true because Seasons no longer assumes that density maps resolution is 0,5 meters (when comparing to world size), now it compute this size, but require all density maps (at least these used by Seasons) to be the same size).
Now regarding strange shadows, unfortunately I have now idea what else in your map can cause it. I newer saw similar issue.

**Comment by Sheldon311** [comment]
Yes, i have all densitys on the same size 8196x8196. And now no Problems with stripes in 1.1.
But in 1.1 and following develop, i have this strange shadows. With 1.0 no Problems with strange shadows!
hmm

**Comment by Dzi4d3k** [comment]
Do you still in FS17 has this invisible brier on the map? I know that it was not in this place, but one of screenshots is so similar to it. This maybe wrong guess but maybe it is somehow related to it's material.

**Comment by Sheldon311** [comment]
I don´t know what you mean with invisible brier.

But I've found out when I delete the file "seasons_textures" makes it no problems.
I have tried out with only very few entries in the file, does not work.

Has since the 1.0 something changed ("seasons_textures.xml" or "replacementTexturesMaterialHolder.i3d"), which I have something else to make?

I can not explain it with the 1.0 works and at 1.1 no more.

The log I have already searched, no error, no warning, nothing

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1286426/log.txt)

**Comment by Sheldon311** [comment]
Has already someone reported in the forums?
I do not understand where the error is.

Without a texture in the seasons_textures.xml it does not even work, because it loads theIt just makes no mistake when the file is deleted.

**Comment by Dzi4d3k** [comment]
Problem is that no one reported such issue before you (at least form these how I know). I encourage you to join Giants discord:
https://discord.gg/M7rrqee
and ask on German channel #modding_de, there is many talented modders, maybe someone will be more helpful.

**Comment by joskuijpers** [comment]
@baleBaron is working on a fix
