### ISSUE TITLE
Question: Krone Ultima Erweiterung (addon)

### ISSUE THREAD

**Issue by Friendlyx** [RealismusModding/FS17_seasons#589]
Do you know this extension? 

> https://www.modding-welt.com/downloads/entry/2090-krone-ultima-erweiterung/#description

it adds some HUD extensions but also makes it possible to wrap Straw Bales. 

-Would these bales resist rotting? 
-would the bales stay straw?

**Comment by baleBaron** [comment]
I just had a quick look at that mod and it appears those wrapped straw bales should be protected.
Let us know how it works out for you.

When using the Ultima with Seasons, I recommend using this fix as well: 
http://www.farming-simulator.com/mod.php?mod_id=84338
