### ISSUE TITLE
Conveyors and maintenance 

### ISSUE THREAD

**Issue by dieselfuelonly** [RealismusModding/FS17_seasons#590]
If possible, conveyors shouldn't require manual maintenance like tractors and trucks.  Moving each and every conveyor to a shop to have them maintained is unrealistic, and letting them go unmaintained is a nightmare if you have to move them or your CoursePlay driver misses the bunker silo by 20 feet and mows down your entire row of them.  Even with the addition of a mod like Working Toolbox, it is still very easy to forget to maintain them and then your $12,000 580 day old conveyor ends up needing something like $169,000 worth of maintenance just to move it 10 feet even though its sell value is only around $1,800.

Recap:

If possible- 
Remove the requirement for conveyors to be maintained like regular vehicles
Maintenance should be automatic, like implements

If not possible-
Manual maintenance fees should have a cap regardless of how long it goes unmaintained - A 12k piece of equipment shouldn't rack up $170k in fees
Seasons should include a toolbox of its own, preferably a tool like the chainsaw that can be kept in the players inventory and not a buggy toolbox that gets thrown 40 feet away when the player turns his body too fast while holding it.

**Comment by reallogger** [comment]
Agree this sounds excessive. For now it will be fixed by making custom repair factors (i.e. reduced repair cost) and capping repair cost to cost of a brand new one.

**Comment by reallogger** [comment]
Fixed with 3fdea1c and 8dfc761
