### ISSUE TITLE
store max soil temp in GT

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#591]
Due to variability in weather the soil temp can drop in spring in some odd cases . Players planting for instance corn or soybeans that require 10 deg C for germination have experienced that even if they plant when the soil temp is 11 deg, the crop does not germinate as the soil temp drops to for instance 9 deg C the last day in the GT. And it is the soilTemp at the time growth happens that is checked for germination.

Solution: store maximum soil temp in the GT for the germination check

**Comment by joskuijpers** [comment]
Great. I suggest to do this in the function calling calcSoilTemp:

- calc the new soil temp
- if today is a new GT: set curMax to -math.huge
- curMax = math.max(curMax, newSoilTemp)

Then in the canSow function, use curMax instead.
Don’t forget to save and load curMax in the save game. You can default the loaded value to currentSoiltemp which is already available.

**Comment by joskuijpers** [comment]
Don't forget multiplayer tho: this can all be on server only.

**Comment by reallogger** [comment]
Done in f17c970
Not sure if I got MP right

**Comment by joskuijpers** [comment]
Alright, I guess it works. However, why sync it to the client at all? Growth is completely on the server side?

We can keep it like this, or we just don't sync it to the client and compare to the current soiltemp on the client. Or return nil in canSow on the client.

canSow is used only in GM, on the server.

**Comment by joskuijpers** [comment]
Oh it won't work on client because it doesnt update max after the soilTemp event came in.

**Comment by joskuijpers** [comment]
Done, moved to server only.

Needs testing in MP now too.
