### ISSUE TITLE
Replanting crops still dies

### ISSUE THREAD

**Issue by davidhunt135** [RealismusModding/FS17_seasons#592]
I planted some corn and then realised that the soil temperature was too low. I then cultivated it back in and waited until the next day to reseed when the conditions were correct. Once I had waited for the crop to grow it still died as though I'd planted it at the wrong time. I planted in late spring with soil temperature @ 14 degrees.

Have I done something wrong or will seasons just detect that I had planted incorrectly to start with and not change state when I cultivate?

Thanks.

**Comment by reallogger** [comment]
Seasons will only check whether you have seeded and what the soil temperature at the turn of growth transitions. So going from late spring to early summer in your case. Seasons does not know the soil temperature exactly at the time you are planting. 

What was the soil temperature the last day in spring and are you using a GEO?

**Comment by davidhunt135** [comment]
The first time I seeded was mid spring 9 degrees. I then cultivated same day when I realised my mistake and waited until late spring to seed again when the soil was 14 degrees. It seems that the conditions used for growing where the ones from mid spring rather than when I reseeded in late spring. Not sure what you mean by GEO?

**Comment by davidhunt135** [comment]
I have just noticed #591 this could be the same issue.

**Comment by reallogger** [comment]
We will have to look into this. 

For later, if you plant too early it has not consequence. The seeds will germinate once the soil temperature increases above the germination temperature. The seeds die only if the soil temperature is below the germination temperature at the end of the scheduled planting time.

GEOs: there are so called GEO mods that change weather and growth.

**Comment by reallogger** [comment]
Unless the soil temperature dropped the last day in late spring this has to be different than #591

**Comment by davidhunt135** [comment]
No, I've not got any GEO. I remember that the soil temperature was 14 degrees but I can't be sure that it didn't drop before transitioning to early summer so its possible that its the same as #591 and that probably make the most sense.

**Comment by reallogger** [comment]
What season length do you use? And what map?

**Comment by davidhunt135** [comment]
the season is 3 days and the map is default Goldcrest Valley

**Comment by reallogger** [comment]
Unable to reproduce so think this has to be the same as #591
