### ISSUE TITLE
Snow admirer should look at actual snow, not at WM

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#593]
It looks odd when the snowmen appear before there is any on the ground.

**Comment by joskuijpers** [comment]
We will need some listener or alike to be notified when the height of the snow changes.

SnowHeightChanged I don't like per se. Could also call the weather change listener again in snow DMS finalizer?

**Comment by reallogger** [comment]
isn't this same as #382?

**Comment by joskuijpers** [comment]
No but if #382 is fixed then this is a nonissue

**Comment by joskuijpers** [comment]
Sometimes the visual snow is still there, but WM snow is already gone. issues.
So just use appliedSnow for the admirer.

Also, add an option to define the minimum snow level, defaulting to 1.

**Comment by joskuijpers** [comment]
This becomes harder every day: basing it on appliedSnowDepth is also hard because it is a server-side value not on the client.

**Comment by joskuijpers** [comment]
Added 'level' option, value is 1-8

**Comment by joskuijpers** [comment]
Now update visibility every updateTick. It already received updates (and the nightlight flicker also does such a thing so I don't worry about performance here).
On server / sp game it is visible using the applied snow height, otherwise falling back to WM snow.
