### ISSUE TITLE
Code that determines bad snowmask sizes is possibly incorrect

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#599]
Need to test with working and non-working maps.

**Comment by joskuijpers** [comment]
@baleBaron did you look at some maps about this?

**Comment by joskuijpers** [comment]
It is not incorrect. Our manual was incorrect.

So it seems the seasons density mask is almost always 2048x2048 while it should be 4096x4096, same size as fruits (to map 1:1 onto the fruits). Added a manual item about this.

Spread the word.

**Comment by Dzi4d3k** [comment]
And should be resized to 8192x8192 for 4x maps before making snow masked places to maintain 0.5m resolution.

**Comment by joskuijpers** [comment]
Yes, that is in the manual. And in the code.
