### ISSUE TITLE
[WM] Weather manipulation

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#6]
**Akuenzi:** Messing around with visual effects to show seasons - **Seb:** I see this as a low priority for now (FP: Low)

**Akuenzi:** Maybe it's impractical to have snow fall... but it might be possible to make things feel a bit more chilly by changing the background.  Maybe even the temperatures could be messed with to make them appear more accurate. **Seb:** Will need to dive into the game to see if we can manipulate the temperatures and rain probability. Higher priority than visual effects (FP: Medium)

This should probably be split out into two cards. One for the visual effects and one for weather manipulation (temperature + chance of rain).

**Comment by joskuijpers** [comment]
I found some nice variables in the environment (put them in globals.md). I think it is possible to make the nights longer in the winter. By default night falls at 8PM and ends around 6AM. We could make night fall in summer at 11PM and in winter at 4:30PM.

**Comment by theSeb1979** [comment]
Indeed, there are tables like day temperatures and night temperatures, but I currently don't know how the game engine populates them and what happens if you modify these values. Some prototyping will be required here.

**Comment by joskuijpers** [comment]
As it is all stateless (not saved on gamesave), I think we should make a couple of (mathematical) functions that determine the temperature, night start/end and amount of rain, with the season and day within season (thus day in year) as input.
Then on game start that data is updated into the g_currentMission table. And then every half a day/day that information is updated again.

**Comment by ian898** [comment]
I have been looking over everything that has been said you have made a solid start here, I think its just a matter of gaining full control over the FS17 weather system once we manage that I think things may become more clear as to what can be done with what exists and what we are going to have to work around there maybe also away to stop the weather updates from game all together if that was possible we could give game whatever values we wanted to.

**Comment by theSeb1979** [comment]
Splitting this out into features:

1. WeatherForecast
2. Weather manipulation based on season

**Comment by reallogger** [comment]
Here is my input on forecast. 

Last night I downloaded weather data from the UK metoffice. What I could do is to make a function that randomly samples the average temperature and amount of rain for each season. This will should then be followed by another sampling of the initial forecast. The sampling of the actual weather experienced during the ingame day should be dependent on the forecast, but not fully. In RL there are lower uncertainty around low pressures and high pressures, but larger uncertainty what is in between. This is easy to capture. 

When it comes to updating the forecast, I think the forecast needs to be saved to xml and loaded so the forecast does not change whether you quit the game and start again. Same with the seasonal average temperature and amount of rain as it can be used for updating the forecast. Another feature I think it would be nice to capture is when the forecast is updated at midnight ingame, the next forecast is dependent on the former. Meaning the forecast might change, especially many days ahead which is more uncertain. 

Let me know if you want some input on this. I can easily crunch the numbers to supply the functions.

**Comment by theSeb1979** [comment]
The intention is for the WeatherManager to manipulate the upcoming weather when the game loads and at intervals, since the game creates the day and night temps and weather conditions for the next 24 days, if I recall correctly.

**Comment by joskuijpers** [comment]
@reallogger Yes, that seems possible. (Not tested but as there is a start time and end time, why not?)

**Comment by reallogger** [comment]
That would be so great. If it does not affect performance this would be a nice feature I think. 

What I also is considering is short showers in the afternoon of hot days in the summer. The kind that is not forecasted. :)

Nice pictures on the forum btw.

**Comment by theSeb1979** [comment]
Ok, so some basic prototyping reveals that we can manipulate the weather by messing around with g_currentMission.environment.rains

Simple code below to make it rain on day 2. The game's forecast icon reacted accordingly late on day 1 and predicted the rain. I also increased the rain duration and it rained for nearly the whole day till late afternoon. 

`g_currentMission.environment.rains[1].startDay = 2;
    g_currentMission.environment.rains[1].duration = 60325364.074707;
    g_currentMission.environment.rains[1].rainTypeId = "rain";`

Still need to consider what the game engine will do this table and how often. However, I guess we can always make our changes at midnight and it should be fine.

**Comment by theSeb1979** [comment]
Discussion started in a closed issue. 

For reference [[WF] Improve BuildForecast](https://github.com/theSeb1979/FS17_seasons/issues/22)

**Comment by reallogger** [comment]
Think I am done with the algorithm that determines the temperature. Under you can see three different realisations done for the month of July. Generally the daily low temp follows the daily high, but not always. Cold summer on top, average summer and hot summer on the bottom. 
![image](https://cloud.githubusercontent.com/assets/15114342/20195822/56d35e54-a798-11e6-8c5f-4e483ce7d28e.png)
![image](https://cloud.githubusercontent.com/assets/15114342/20195835/5df9821c-a798-11e6-8401-e3d8827a24cb.png)
![image](https://cloud.githubusercontent.com/assets/15114342/20195913/9f5d487e-a798-11e6-8eca-dde84daad731.png)

**Comment by joskuijpers** [comment]
Looks good to me!

**Comment by theSeb1979** [comment]
Amazing stuff

**Comment by reallogger** [comment]
Thanks. Lot of numbers behind these figures, but I'll in the end reduce the complexity so the code will hopefully not be too long. 

I've moved onto precipitation now and will link this to the daiily high temperature. Generally high temperatures during the day is related to high pressures, where there is a higher chance for having sunny weather. Same with low temps during the day are more linked to low pressures and rain. 

For each season there will be a daily probability for having rain. If the temperature during that particular day is above the seasonal average, the probability for rain decreases and similar if the temperature is low. I've got average amounts of rain [mm] for each month and now just need to figure out an equation for determining the duration of the rain given rain occurs. The wanted effect is that it will rain more often during autumn and winter and if it rains the rain lasts longer. Based on actual precipitation models there is a logarithmic relationship between rain intensity and rain duration I need to figure out how to use. For the summer season specifically I will include that if the temperature is above the seasonal average (a typical warm day) and rain will occur, the rain comes in the afternoon, early evening. Like a thunderstorm. 

Also been thinking about sunshine. Amount of sunshine will also be linked to temperature so in summer warm days will have more clear skies than colder days (compared to seasonal average). During winter it is opposite. Clear days are colder than days with overcast. Not sure yet what to do with spring and autumn. 

**I have a question about snow.** The way I understand it, there is no falling snow in FS (not thinking about some maps that included snow as a foilageLayer). Would it be an idea to limit hail to days when it will rain and the temperature is below zero? It won't look like snow, but will look different. 

Here are some plots from warm,average and cold days in January. 
![image](https://cloud.githubusercontent.com/assets/15114342/20211681/dc81c84e-a7ff-11e6-862e-b2606aa1146e.png)
![image](https://cloud.githubusercontent.com/assets/15114342/20211700/ede18e1c-a7ff-11e6-8076-8d8facb009de.png)
![image](https://cloud.githubusercontent.com/assets/15114342/20211660/c89e5478-a7ff-11e6-88c2-5a65413ddcca.png)

**Comment by joskuijpers** [comment]
I think it might be best to use 'hail' as 'snow' and possibly change a shader for it. I don't think we can add our own weather type (will figure this out in an hour when I am in the train).

So yes, only hail when there is downfall and it is <0. (You could just program downfall true or false and ill make it hail/snow/rain)

**Comment by theSeb1979** [comment]
Yeah, agreed on the hail.

**Comment by reallogger** [comment]
Here is a python code which we can use to find the temperature during the day so the temperature can be displayed on the hud. I see now that updating the temperature every hour will be enough. 

    # calculating the diurnal temperature fluctuations
    # reallogger
    # 2016 11 12
    
    from math import cos,pow,pi
    
    #ASSUMPTIONS
    #low temp occurs at 0700
    #high temp occurs at 1500
    #night temperature is for the night before the current day as the low temp occurs in the morning
    
    weatherTemperaturePrev=21 #Has to store the day temperature from the previous day
    
    #dummy temperature tables - read from g_currentMission
    weatherTemperaturesNight=[10,12,12,11,10,9]
    weatherTemperaturesDay=[27,23,25,30,28,29]
    
    
    #dummy currentMinute and currentHour - read from g_currentMission
    currentHour = 17
    currentMinute = 0
    
    currentTime = currentHour*60 + currentMinute
    
    if currentTime < 420:
    	currentTemp = pow(cos(((currentTime + 540.)/960.)*pi/2),3)*(weatherTemperaturePrev-weatherTemperaturesNight[0])+weatherTemperaturesNight[0]
    elif currentTime > 900:
    	currentTemp = pow(cos(((currentTime - 900.)/960.)*pi/2),3)*(weatherTemperaturesDay[0]-weatherTemperaturesNight[1])+weatherTemperaturesNight[1]
    else:
    	currentTemp = pow(cos((1- (currentTime-420)/480.)*pi/2.),3) * (weatherTemperaturesDay[0]-weatherTemperaturesNight[0]) + weatherTemperaturesNight[0]
    	
    print(currentTemp)

**Comment by reallogger** [comment]
I've run into a possible problem and need some lua assistance. I basically need to know if it is possible in FS to draw a random sample from normal and lognormal distributions. This seems to require some additional package, which I have no idea if FS utilizes. [http://stackoverflow.com/questions/37240824/how-to-draw-samples-from-a-multivariate-gaussian-in-lua-torch](url)
If this is not possible I need to rethink quite a bit.

**Comment by joskuijpers** [comment]
Huh yeah well, no. There is no such thing in FS.

**Comment by reallogger** [comment]
Problem solved!! 

Here is the code for determining daily high and low temperatures. 

    # calculating temperatures based on season
    # based on historic weather data from UK
    # Inverse normal CDF algorithm based on A&S formula 26.2.23 - thanks to John D. Coook
    # reallogger
    # 2016 11 15
    
    from math import sqrt,log
    from random import random
    from numpy import zeros
    
    def ssTmax(ss): #sets the minimum, mode and maximum of the seasonal average maximum temperature. Simplification due to unphysical bounds. 
    	if ss == "winter":
    		return [5.0,8.6,10.7] #min, mode, max
    		
    	elif ss == "spring":
    		return [12.1, 14.2, 17.9] #min, mode, max
    		
    	elif ss == "summer":
    		return [19.4, 21.7, 26.0] #min, mode, max
    	
    	elif ss == "autumn":
    		return [14.0, 15.6, 17.3] #min, mode, max
    	
    def ssTriDist(m): #Outputs a random sample from a triangular distribution
    	pmode = (m[1]-m[0])/(m[2]-m[0])
    	p = random()
    	if p < pmode:
    		return sqrt(p*(m[2]-m[0])*(m[1]-m[0]))+m[0]
    	else:
    		return m[2]-sqrt((1-p)*(m[2]-m[0])*(m[2]-m[1]))
    
    def RationalApproximation(t): 
    	c = [2.515517, 0.802853, 0.010328]	
    	d = [1.432788, 0.189269, 0.001308]
    	return t - ((c[2]*t + c[1])*t + c[0]) / (((d[2]*t + d[1])*t + d[0])*t + 1.0)
    	
    def ssNormDist(mu,sigma): #Outputs a random sample from a normal distribution
    	p = random()
    	if p < 0.5:
    		return RationalApproximation( sqrt(-2.0*log(p)))*-sigma + mu
    	else:
    		return RationalApproximation( sqrt(-2.0*log(1-p)))*sigma + mu
    
    Tmax = ssTmax("winter")
    Tmaxmean = ssTriDist(Tmax) #This is the seasonal average and should be stored for each season. Not to be resampled each day.
    
    day = [1,2,3,4,5,6,7,8,9,10] #dummy array with day numbers. To be replaced. 
    
    weatherTemperaturesDay = zeros(len(day))
    weatherTemperaturesNight = zeros(len(day))
    
    for i in day:
    	weatherTemperaturesDay[i-1] = ssNormDist(Tmaxmean,2.5) #At midnight and a new day is to be generated, just use this call to get a new daily high temperature
    	weatherTemperaturesNight[i-1] = ssNormDist(0,2) + 0.75*weatherTemperaturesDay[i-1]-5 #At midnight and a new day is to be generated, just use this call to get a new daily low temperature
    	
    print weatherTemperaturesDay
    print weatherTemperaturesNight
