### ISSUE TITLE
Conveyors and snow

### ISSUE THREAD

**Issue by dieselfuelonly** [RealismusModding/FS17_seasons#610]
Conveyors can easily get clogged by snow.  It would be nice to have snow blacklisted from conveyors so it can't be picked up if possible.  Alternatively, perhaps it could at least melt off the conveyor when the snow layer melts away in spring.  Especially on a "chain" of conveyors one conveyor may have snow while others have a different material which can end in a nightmare trying to get that one little bit of snow unstuck.

**Comment by joskuijpers** [comment]
We might see if we can melt the snow.

**Comment by joskuijpers** [comment]
We are not going to fix this. You will need to turn the last one in the chain or turn off the first one when winter begins.
