### ISSUE TITLE
LUA Issue On WIP Map

### ISSUE THREAD

**Issue by rubberburner89** [RealismusModding/FS17_seasons#613]
So, last night I was getting ready to put the finishing touches of my map, and getting it ready for a second round of beta testing. Since the previous version I've added a shed so I wanted to put a snow mask it. Here's where things start getting frustrating. I reverted seasons info back so I could see my mask, but it wouldn't paint. I chaulked it up to I've had a few to many brews and I'll just paint it without being able to see the mask, go in game, and test that it worked.... Here's where things go bad!!! Go in game... .lua stack.

```
C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/resources/environment/snow_materialHolder.i3d (3.76) ms
C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/resources/replacementTextures/replacementTexturesMaterialHolder.i3d (145.63) ms
Warning (Script): Unknown entity id 0 in method 'getName'.
LUA call stack:
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (185) : getName
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (254) : findNodeByName
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (27) : loadTextureIdTable
  dataS/scripts/BaseMission.lua (547) : loadMap
  dataS/scripts/FSBaseMission.lua (1707) : loadMapFinished
Warning (Script): Unknown entity id 0 in method 'getNumOfChildren'.
LUA call stack:
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (189) : getNumOfChildren
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (254) : findNodeByName
  =C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua (27) : loadTextureIdTable
  dataS/scripts/BaseMission.lua (547) : loadMap
  dataS/scripts/FSBaseMission.lua (1707) : loadMapFinished
Error: Running LUA method 'loadMapFinished'.
C:/Users/Stephen Wheaton/Documents/My Games/FarmingSimulator2017/mods/FS17Contest_Seasons/src/environment/ssReplaceVisual.lua:189: attempt to perform arithmetic on a nil value
```

So at this point i said alright.... I screwed something up, I'll just revert back to a previous version from like an hour or two back.... I did, same stack. In fact, this .lua stack goes back like 3 or 4 days worth of versions.... I hadn't been testing with seasons in.

Anyways. Any help would be appreciated.

Thanks,

RB

P.S. Today I went back through my map01.i3d and re-did all of the seasons text. I now have my snow mask appearing again, however the .lua call stack still persists.

**Comment by theSeb1979** [comment]
What version are you using of our mod? Please provide the full log file.

**Comment by Dzi4d3k** [comment]
> `FS17Contest_Seasons`
I suggest to check with version 1.1:
http://farming-simulator.com/mod.php?lang=en&country=gb&mod_id=79288&title=fs2017

**Comment by rubberburner89** [comment]
It was pointed out to me on another forum that I was using an old version, so I upgraded to the most recent (as far as I know), and just created a fresh log... still there.
[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1311842/log.txt)

**Comment by rubberburner89** [comment]
During my clean-up of all unneccessary/duplicate files, I removed some shrubs that the seasons_textures.xml was looking for. Once I figured that out, easy fix. Sorry for having wasted your time, but thanks all for taking a look.
