### ISSUE TITLE
Buying a placeable throws ssReplaceVisual "attempting to index a nil value"

### ISSUE THREAD

**Issue by ian9018** [RealismusModding/FS17_seasons#614]
With OnTheHills v1.1, and Seasons v1.1 (both from ingame modhub), no other mods and dlc turned off when loading a new game

Attempting to place a placeable (pressure washer etc.) will place the model, but it cannot be interacted with and no money is taken. An error in the log is thrown stating...

Error: Running LUA method 'mouseEvent'.
C:/Users/ian90/Documents/my games/FarmingSimulator2017/mods/FS17_RM_Seasons/src/environment/ssReplaceVisual.lua:216: attempt to index a nil value

Trying to place another placeable (like a water tower) will put an entry in the log but doesn't appear at all on the map.

I've attached my [log.txt](https://github.com/RealismusModding/FS17_seasons/files/1311876/log.txt) abd uploaded a [YT video of the issue](https://www.youtube.com/watch?v=m_j5CdC4YZY) if thats your thing.

**Comment by joskuijpers** [comment]
This is an issue in OnTheHills and has been reported multiple times to the maker, but it does not seem to get updated.

There is an error in its texture replacement file.
