### ISSUE TITLE
WopSTR readings

### ISSUE THREAD

**Issue by alpha117** [RealismusModding/FS17_seasons#616]
Hi All

what do the numbers mean.
Example(from the top)
1249.66 , 289.58
51.1M
Grass
33%
33%

Looks good

Thanks

Clive

**Comment by reallogger** [comment]
- coordinates
- elevation
- crop type 
- growth (100% is harvestable)
- fertilization

**Comment by alpha117** [comment]
Thanks for the quick reply.
Elevation is relevant to crops in what way?

Will you be adding 'moister' content to crops?

This is very good

Cheers

**Comment by reallogger** [comment]
Elevation is only for information
cropMoisture will be added later together with some other features

**Comment by alpha117** [comment]
Thanks

Like it very much, cant wait for the next parts
