### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by alpha117** [RealismusModding/FS17_seasons#617]
Hi All,

not sure if this is of any help:

I:/FS_Maps/The West Coast/FS17_seasons_develop/src/misc/ssPedestrianSystem.lua:30: attempt to index field 'environment' (a nil value)

thanks

Clive

**Comment by baleBaron** [comment]
We are investigating this issue.
Thanks for the report.

What version of seasons are you running?

**Comment by alpha117** [comment]
The latest development version from here

**Comment by theSeb1979** [comment]
Can you provide your entire log file

**Comment by alpha117** [comment]
[log.zip](https://github.com/RealismusModding/FS17_seasons/files/1326597/log.zip)

**Comment by alpha117** [comment]
Can now also confirm that this latest version causes a CTD when exiting a game. Nothing in the event viewer.

Disable seasons and all is fine.  Going back to a version dated 22/09, see if that is OK.

**Comment by alpha117** [comment]
version of 22/09 also causes CTD; went back to version 12/09 all OK BUT no WOPSTR meter(DRAT)

could you upload a version after 12/09 but before 22/09, as I have not kept those(need WOPSTR back)...lol

thanks

**Comment by joskuijpers** [comment]
'CTD'?

**Comment by joskuijpers** [comment]
Fixed in 4988598

**Comment by alpha117** [comment]
crash To Desktop (CTD)

**Comment by alpha117** [comment]
Can confirm new version fixes issue. Clean exit and log is 'clean'

Many thanks
