### ISSUE TITLE
nil in line 565 of ssVehicle.lua

### ISSUE THREAD

**Issue by Mogli12** [RealismusModding/FS17_seasons#618]
Hi,

If a bought configuration does not exist anymore there will be an error in line 565 of ssVehicle.lua (https://github.com/RealismusModding/FS17_seasons/blob/develop/src/vehicles/ssVehicle.lua#L565). I propose to check if something is nil there.

Regards,
Stefan

**Comment by joskuijpers** [comment]
Great one! Thanks 😄  Does this happen often? I have seen the error before but thought to have fixed it with my nil check :s
