### ISSUE TITLE
Feeding Cows, does it reflect reality? 

### ISSUE THREAD

**Issue by SoloTwo** [RealismusModding/FS17_seasons#619]
Let me know if I'm just completely off base here, but, after finally playing for awhile, it really seems like the default feeding system for cows is devoid of realism.  I see no reason as to why I should need to feed both grass and silage separately on top of feeding the TMR.  Why would I be wasting time making TMR if I would have to just feed them even more, silage and grass?  Doesn't seem to make sense and defeats the purpose of TMR.  

Not to mention how if I feed only TMR I get a measly 30% productivity boost.  But hey I could just feed straight silage and get 50%?  Also, I noticed if I just mix silage and hay it still counts as Power food for whatever reason.  

I'm not a farmer in real life but in all the information I've consumed over the years I've never seen farmers mixing silage, hay, and straw, then feeding it, then proceeding to feed some raw silage, and then some raw hay.  

I know this is a problem with the default game, but I'm just wondering if Season's has any plan to address this, or if it's even possible to address it.  If it's out of the scope of the mod I'll try and see if something can be done with MR.  Perhaps I'm just completely in the wrong here though and have no idea what the hell I'm talking about. -_-

**Comment by reallogger** [comment]
@SoloTwo Not sure what you do, but when I make TMR with silage and hay (and straw if I've got some straw to spare) and feed this, I get an increase in both 'Power food' and 'Silage/Hay'. If the cows have straw and water and a clean barn I end up at 80% productivity. How are you able to feed so only the 'Power food' increases?

**Comment by SoloTwo** [comment]
Just for reference, I am using MR and MR Gameplay.  

Here is a screenshot of my current situation after just feeding.  [](https://imgur.com/qZgdLM3)

My TMR mix consisted of 3 silage bales, about 2 hay bales, and then one straw bale.  I then fed one individual bale of hay as well.  The fact that my silage in my TMR counts towards the amount of silage I have is nice, but it just seems like a bit of sloppy coding instead of just giving 100% or whatever productivity like in past games.  And then why doesn't it include my hay/grass from my TMR as well?  (Obviously, because I'm using the hay as grass mod)  

Now, after feeding about 9000 liters of TMR, my power food is now WELL over 3 days of total feed, and I will need to continue adding just straight silage otherwise I will just have infinite power food as I'm allowed to add more than the 3-day limit.  

So for every 3 days, I will need to feed about 5 bales of silage, 4 grass bales, and probably 2 bales of straw.  All for only 27 cows that produce less than a grand worth of milk income (7th day of Autumn).  It all seems a bit excessive and would be fixed if TMR gave you full production like in the past.  The whole point for a farmer to use TMR is to get the best productivity from their cattle.  I don't know of any dairy farms that take the time and effort to use TMR and then have to feed individual bales of hay and silage on top of the TMR.  

Well enough rambling, TLDR, I think the previous games where you got full productivity from TMR made sense and reflected reality.  As it currently stands the amount of food needed to reach 100% is unsustainable and not worth the effort.  80+ silage bales a year for only 27 cows.  :-/

Again I'm not saying this is a problem with Season's, but something that maybe you guys would address.  Though if everyone feels like the current system reflects reality I'm fine with that, hell, I don't even know if it's possible to change it.

**Comment by joskuijpers** [comment]
Are you using Seasons too? If so, what version?

**Comment by SoloTwo** [comment]
Yes, the latest version available on Modhub.  I'd love to use the dev version because it looks like you've all added so many great features but I'll wait till release so I can hopefully use with my save game. :)

Btw the screenshot is now added correctly in my above post.  And sorry for the rambling, not exactly one with words.

**Comment by reallogger** [comment]
Tested with vanilla and you are able to feed more than the 6 day limit of one fillType when filling TMR. When adding TMR, 62.5% goes to Silage,hay and 37.5% goes to Power food. This is the same with and without Seasons. 

What we do change in Seasons is the amount of feed needed. Annually you need 8400 liters per cow. So that is a little bit more than 2 vanilla bales per cow. With MR it is 3 bales (3000 liters per bale) and MR gameplay 4 bales (2000 liters per bale). But the same amount of material with and without MR and/or MR gameplay. 

That the current system does not reflect reality I think we can very much agree to. There are so many things with animals that should be improved in FS.

**Comment by reallogger** [comment]
Closing this issue as we have no plans to implement any change atm
