### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by Paul2510** [RealismusModding/FS17_seasons#621]
Hi! 

I have a error  when i start a Map
/mods/Seasons/src/vehicles/ssVehicle.lua:565: attempt to index a nil value
Error: Running LUA method 'update'.

LG

**Comment by joskuijpers** [comment]
When did you last update Seasons? Are you using the develop version from today?

**Comment by Paul2510** [comment]
I have the Version from today!

**Comment by joskuijpers** [comment]
Can you try with the version from 3 seconds ago?

**Comment by Paul2510** [comment]
Thanks! Its works with no Problems!

LG

**Comment by Paul2510** [comment]
Sorry! I have today this Problem
/mods/Seasons/src/misc/ssAnimals.lua:25: attempt to index a nil value

Thanks
LG

**Comment by joskuijpers** [comment]
Is this with the very latest version?

**Comment by Paul2510** [comment]
No the version form yesterday

**Comment by joskuijpers** [comment]
Can you use the version from just now?

**Comment by Paul2510** [comment]
This is the log from the latest version
/Seasons/src/misc/ssAnimals.lua:29: attempt to index a nil value

**Comment by joskuijpers** [comment]
Can you try with the very latest version? I did an update

**Comment by Paul2510** [comment]
Thanks! No problems!
