### ISSUE TITLE
Translations need updating for 1.2

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#622]
- [ ] Brazilian @mayhem17 
- [X] Hungarian @n0tr3adY (small translation)

That is all :)

**Comment by joskuijpers** [comment]
If the brazilian translations are not updated, I will have to remove them, or put english versions in there.

**Comment by Dzi4d3k** [comment]
I would suggest to put English in missing parts or even Google translate. Removing whole translation because of few sentences missing is not a good idea.

**Comment by joskuijpers** [comment]
Will do English. Not going to use google translate :) That is amateurish.

If you have seen S02E01 of Designated Survivor and know dutch, you also know why you should not use google translate for professional work.

**Comment by mayhem17** [comment]
BR tranlation updated. Ready to merge. Sorry for the delay, RL problems.

**Comment by joskuijpers** [comment]
Can you make a pull request?

**Comment by joskuijpers** [comment]
Thank you! I hope you will be able to resolve your RL problems :)
