### ISSUE TITLE
Growing corn

### ISSUE THREAD

**Issue by davidhunt135** [RealismusModding/FS17_seasons#624]
I have mentioned this before on here and I have tried 3 sowing seasons but I can't get corn to grow. I am playing on the default map season length 3 days. 

The most recent scenario I planted on 1st day of summer with soil temp at 16 degrees. I then waited until the last day of summer and the corn went from growing to harvested, soil temp still at 16 degrees.

I'm not sure what I'm doing wrong here?

**Comment by joskuijpers** [comment]
Can you send your logfile?

**Comment by joskuijpers** [comment]
Are you sure you look at the soiltemp, not airtemp? Because this works for everyone.

**Comment by davidhunt135** [comment]
[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1339794/log.txt)

I've attached my log file. I wasn't sure first time but the two times since I have been careful to plant at the right time

**Comment by reallogger** [comment]
Can you send us you careerSavegame.xml file also?

**Comment by davidhunt135** [comment]
The most recent? i.e the one which was saved after the corn changed to a harvested state?

**Comment by joskuijpers** [comment]
No the one before that

**Comment by davidhunt135** [comment]
[Savegames.zip](https://github.com/RealismusModding/FS17_seasons/files/1340341/Savegames.zip)

I've included all of the backups from before planting corn through to the current one. Named as the savegame backup so date and time included

**Comment by joskuijpers** [comment]
Thank you, that is very useful.

It seems maize did not germinate in GT4 while it should have. soiltemp was 13 degrees at the time. 
We are looking into it.

**Comment by joskuijpers** [comment]
Hello David.

We found the issue and a fix.
Could you try the savegame from `savegame1_backup2017-09-27_17-51` with the very latest version from github? Just plant maize and see if it grows.

**Comment by davidhunt135** [comment]
I will try later today and let you know how it goes. Thanks

**Comment by davidhunt135** [comment]
Looks good. Corn has grown this time. Thanks
