### ISSUE TITLE
New Fruits

### ISSUE THREAD

**Issue by Paul2510** [RealismusModding/FS17_seasons#626]
I have on my map additional fruits (oat rye) which only mature in the winter! how can I change this?
LG

**Comment by theSeb1979** [comment]
Additional fruits grow just like barley. If your additional fruits don't grow like barley, then something is wrong with how you set them up. You can change the growth by creating your  own growth file for the map. Instructions are in the online manual on our website.

**Comment by Dzi4d3k** [comment]
@Paul2510 did you come to any solution, as I saw almost similar issue, and I'm looking for any clues.

**Comment by Paul2510** [comment]
My Problem is the Map! The problem I have unfortunately not yet found!
