### ISSUE TITLE
Grass bales disappear overnight

### ISSUE THREAD

**Issue by escetic** [RealismusModding/FS17_seasons#629]
It's mid spring, using the default Seasons mod on the Goldcrest map.  I create some round grass bales, I carefully stack them in a closed building (not the sell point) along with my hay and straw square bales and a pile of silage.  I add a few grass bales to the feed zone for my cattle.  Next day I return to the building to fetch some more grass bales, they're gone.  The hay, straw and silage remain intact.  This could be an issue with the building, which is a mod, but I doubt it.

According to Seaons documentation grass will slowly disappear but so long as it's baled it will stay, right?

**Comment by reallogger** [comment]
Are you sure they disappeared the midnight after they were created?

From the manual:
Grass bales will gradually rot and disappear after two days, unless they are wrapped so that they become silage bales.

**Comment by escetic** [comment]
Pretty sure, but if this is expected behaviour then ok.  There might have been a delay from the time I made the bales to the time I collected and stored them.   I know grass is not essential for the cattle but I have this idea in my head, untested, that feeding them everything and keeping all the bars green will increase manure production, which is what I need.

Thanks for the great mod, btw. :)

**Comment by reallogger** [comment]
Thanks. 

Think only straw affects manure production though.

**Comment by escetic** [comment]
One thing, I think if grass disappears after two days it almost makes it not worth it to collect grass at all, even in summer.

**Comment by Willykeen** [comment]
This is where the hay as grass mod comes in handy 👍

**Comment by joskuijpers** [comment]
Do not collect grass. Give a bit to the animals and make silage or hay of the rest of it.
