### ISSUE TITLE
Error in local file regarding growth

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#630]
Error: Running LUA method 'update'.
D:/My Games/FarmingSimulator2017/mods/FS17_RM_Seasons/src/growth/ssGrowthManager.lua:534: attempt to index a nil value

**Comment by theSeb1979** [comment]
There is no line 534 in growth manger. This error is based on a VERY old version of the mod

**Comment by joskuijpers** [comment]
Not very old, the currently released one.

Also: additinional fruits and MP.

**Comment by joskuijpers** [comment]
Can't reproduce
