### ISSUE TITLE
ssAnimals Error

### ISSUE THREAD

**Issue by Paul2510** [RealismusModding/FS17_seasons#631]
Hi I have an Error in the log! I hop you can help me! When the error come the Game crash!
C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/Seasons/src/misc/ssAnimals.lua:346: attempt to compare number with nil
Error: Running LUA method 'update'.

LG

**Comment by theSeb1979** [comment]
Please include full error log. What version are you using?

**Comment by Paul2510** [comment]
its the newest Version

**Comment by Paul2510** [comment]
[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1384891/log.txt)

**Comment by reallogger** [comment]
@Paul2510 Can you try with the latest from develop?

**Comment by Paul2510** [comment]
Hi! I test it and its a little error 
C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/Seasons/src/misc/ssAnimals.lua:154: attempt to index field 'animalDesc' (a nil value)
Error: Running LUA method 'update'.

**Comment by reallogger** [comment]
I am not able to reproduce the error. This is on the Lösshügelland right? Tested with v 4.1.1 of the map.

**Comment by Paul2510** [comment]
Ok! Many Thanks! This is a Great Mod!

**Comment by reallogger** [comment]
Thanks. Would be interesting to know why you get that error though. I've bought cows, pigs and sheep and been running for several days in the game without any errors thrown. I will close the comment. Reopen and post more info if it still does not work
