### ISSUE TITLE
Errors with Hof Bergmann Reloaded

### ISSUE THREAD

**Issue by normada** [RealismusModding/FS17_seasons#632]
Hello all,

the latest developer version of seasons might have problems with the Map Hof Bergmann Reloaded, or vice versa.
The problem occurs during saving and later on when trying to load a savegame.
It might have something to do with the additional animals coming from that map.

Thanks
Ron
[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1385404/log.txt)

**Comment by joskuijpers** [comment]
Holy shitcrap, how many mods can you have in that folder? :P

```
Warning (LUA): 'setXMLFloat': Argument 2 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/normada/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/misc/ssAnimals.lua (50) : setXMLFloat
  =C:/Users/normada/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/loader.lua (214) : save
  dataS/scripts/utils/Utils.lua (1859) : newFunc
  dataS/scripts/gui/CareerScreen.lua (784) : saveToXML
  =[C] (4294967295)
  dataS/scripts/gui/CareerScreen.lua (909) : saveWriteSavegameStart
  dataS/scripts/missions/mission00.lua (391) : saveSavegame
  dataS/scripts/gui/InGameMenu.lua (1004) : saveSavegame
  dataS/scripts/gui/elements/Gui.lua (306) : update
  dataS/scripts/main.lua (1872) : update
```

**Comment by normada** [comment]
Never had any problems with that many mods.
Anyway thx for your attention and your support.

Ron

**Comment by reallogger** [comment]
@normada Can you try with the latest from develop?

**Comment by normada** [comment]
Just tried the latest from develop, didn´t work. Disabled all mods except the seasons mod.

Ron

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1388698/log.txt)

**Comment by reallogger** [comment]
@normada Can you try now?

**Comment by normada** [comment]
Made quick testing and it works. Further testing tomorrow.

**Comment by reallogger** [comment]
Thanks. I'll close this for now. Reopen it if you still encounter errors.

**Comment by normada** [comment]
Found after 1st night on this map with seasons another error with ssAnimals.lua.
I used skip night to foward to next morning.

Ron

[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1405153/log.txt)

**Comment by joskuijpers** [comment]
Please get me a proper, original link to that map, Hof Bergmann

**Comment by normada** [comment]
http://uploaded.net/file/ww795ae7
That map has been released some days ago.
Their german forum is on www.modding-welt.com.
Map runs well with the official seasons release.

Again, thx for taking care.
Ron

**Comment by joskuijpers** [comment]
That download is _very_ slow.

I do think, that if you want to play Seasons, you will need to find another map. This map just has all kinds of magic incompatible with Seasons.

**Comment by normada** [comment]
Another link from modhub.us
http://www.modhub.us/farming-simulator-2017-mods/hof-bergman-reloaded-v1-0-0-2/

That map is desingned to work with seasons, but with the official seasons release. But you and your team made alot of improvements in the dev. versions in the meantime. That´s why i play only the dev. version.

Ron

**Comment by reallogger** [comment]
@normada Try the latest version. It is difficult to safeguard against all the strange things embedded into this map.

**Comment by joskuijpers** [comment]
I am closing this issue. Any other issues you have with this map + Seasons related to animals, is a problem with the map and you should report them to the makers of the map.

The issues never seem to end, because the mapmakers did some hacking and unofficial stuff that we just can't support.

**Comment by joskuijpers** [comment]
By the way, it is the same for Stappenbach.

**Comment by Dzi4d3k** [comment]
That's becoming worrisome, as modifications to FS17 evolve and the more customs things are the more incompatibilities arise. 
Maybe it would be good to provide kind of Seasons' API for these authors who are willing to add custom functionalities to maps. I know that's it is thought task, but it is just an idea, because otherwise users will have to choose between great maps and great mods like Seasons.

**Comment by joskuijpers** [comment]
If you looked into the scripts that cause issues, you would know it is fixable, if they did it 'correctly':

2 problems.
1) A non-husbandry object is added to the husbandries list. We, like the game itself, do assumptions about what is inside that list. We expect it to be a fully functioning husbandry. Now that can be faked, as the script tries to do, but it should be faked in a good way.
That means, it needs to add all properties a normal husbandry has, with values that make sense for the fake one. This is not done.
Also, the fake husbandry is not loaded early enough. This is easily fixable by making it an onCreate object and loading it in the map using an invisible node with user attribute onCreate on it (just like an actual husbandry).

If those two things are done, it is much like a husbandry and it will probably work just fine.

Note that you can't go and insert random things into the fillTypes table either, or other tables. :)

**Comment by Dzi4d3k** [comment]
Very true, however not all modders have such good knowledge and skill as you do, that costs in equivalent of issues. Seems that community still need lot of guidance from Giants how mods have to be done. Unfortunately, that won't happen anytime soon, so that's why I had idea about 'API'. I know that you can't teach others. Best Practices part of Seasons' manual is doing the job, but could be extended with example about animals. Just an idea :)
