### ISSUE TITLE
Grass Disappears

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#64]
grass foliage layer disappears when loading saved game after adding mod to mods folder

**Comment by theSeb1979** [comment]
Please provide more info. What day is in the game? Actually, could you paste the contents of the savegame.xml?

**Comment by lindbejb** [comment]
ok, I understand that but the grass foliage over the painted grass terrain, no field terrain, was gone, and never came back.  I love the potential this mod has, keep up the great work.

**Comment by theSeb1979** [comment]
A lot of new changes were added to the growth manager in the last few days, so it needs a lot of testing, which I will be doing next week :)

**Comment by lindbejb** [comment]
amazing, also, would it be possible to have the script use terrain terrain and foliage textures during the winter to have a snow appearance?

**Comment by theSeb1979** [comment]
The issues in growth manager should be fixed now hopefully.
