### ISSUE TITLE
Put the vehicle repair inside the direct sell dialog

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#650]
When the vehicle has outstanding repair costs, disallow either selling or configuring. Replace the button with a repair button.

**Comment by Friendlyx** [comment]
how are the repair costs determind anyways. I can't believe a tractor has a yearly operating cost of 13000€. thats what game wants from me now.

**Comment by joskuijpers** [comment]
Did you repair the vehicle at all? What vehicle is it?

**Comment by Friendlyx** [comment]
its a IH 1455XL did repair it before when it was necessary. I think then the change to ver.1.2 came and now after the rest of the time I have these high cost. the tractor has 170h on clock. I might cheat money and try it after another period again.

**Comment by joskuijpers** [comment]
It is time to buy a new tractor. The age dominates the cost now.

**Comment by Friendlyx** [comment]
I don't think this is real, I have two Tractors of that type and no money for repairs. both tractors take 40000€ for a year maint and then there is my old combine. No way this is real(ismus). Please make some options there in next update aswell. this really destroys my game experience and for all other things i really like Seasons.

**Comment by joskuijpers** [comment]
There is this thing called ‘gameification’. We don’t expect people to play a single game for 40 game years, and thus we adjust the real data we use.
