### ISSUE TITLE
realism idea

### ISSUE THREAD

**Issue by jcuts33** [RealismusModding/FS17_seasons#657]
idea 1.
do something with crop contracting. The way I do in real life. I can call and contract "X" number of liters at "Y" sell point for delivery in certain month. If I do not provide enough liters to fill the contract I get charged a large fine.
So say I like the price today for soybeans but don't have any in the bins and some growing. 
I can say I want to contract 40,000 liters of soybeans to wright agribusiness for fall delivery.
or contract 100,000 liters of corn to Gomez ridge acres for spring delivery.  Once I haul the amount contracted i get paid that days price for the extra. 

idea 2 
make land improvement option. make it so that you can "tile" your field for water management reasons, thus bringing the quality of the field up. But after you purchase tile for a field it goes back to required plow state, just like in real life you have to do deep tillage after installing tile. Make it worth 10%-20% crop yield impact.

**Comment by joskuijpers** [comment]
Idea 2 we will not do, but 1 we will consider :)
