### ISSUE TITLE
Giants Engine don't work anymore

### ISSUE THREAD

**Issue by BlackWolve** [RealismusModding/FS17_seasons#658]
Hi, today Giants released the patch 1.5.1
It look like the seassons mod won't working with that.
Here is the log file 
[log.txt](https://github.com/RealismusModding/FS17_seasons/files/1438010/log.txt)

Hope you can identify the issue with that :)

Greetings
BlackWolve

**Comment by joskuijpers** [comment]
I think that is an issue with the game itself. Or the map is not compatible with 1.5.1. What map do you use?

**Comment by BlackWolve** [comment]
I'm using the Hof Bergmann by Farmer Andy in the actually version 1.0.0.2. This issue is scince the patch 1.5.1 of today. I think there will come more of these reports to you xD

**Comment by debejerry** [comment]
I'm running Stappenbach 17 on my Dedi Server with seasons enable after patch 1.5.1 and it runs fine.
@BlackWolve  the only advice may be the classical one: you should clean up mods folder first and then enable them step by step to see whats cousing issues.

**Comment by joskuijpers** [comment]
Also, go to Farmer Andy with this. Apparently his map is broken. Not our mod
