### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#66]
Be nice to have more equipment sales in the spring and great demands more frequent or higher prices in the winter

**Comment by theSeb1979** [comment]
I like the idea of higher prices / more great demands in the winter

for sales... well... you usually get discounts in real life on equipment when it's out of season 
so best time to buy a combine is in the winter
best time to buy a sprayer is in the summer or winter and so forth

Idea will be discussed within the team.

**Comment by lindbejb** [comment]
for sales i was think more from a tax point of view.  Most make large purchases prior to the end of their fiscal year to lower their net income.  Since that demands on when they actually assigned the first of their fiscal year, most people associate this with April for taxable events.

**Comment by joskuijpers** [comment]
This would be a fit for a possible future mod, not Seasons :) Thanks!
