### ISSUE TITLE
Night time cloudy sky replacement texture

### ISSUE THREAD

**Issue by JoeRoss12** [RealismusModding/FS17_seasons#662]
While the seasons mod is the most awesome mod ever in FS17, the one thing that bothers me is that whenever it rains during the night, the night sky goes from a starry night to a bright cloudy sky which clashes with the dark objects and ground.
It would be very cool if you could implement a replacement sky texture just like the way you did the default tree textures. 
Just a thought......that would be soo awesome!!

**Comment by Dzi4d3k** [comment]
Unfortunately this is limitation of game engine hardcoded in it by Giants and sadly seems that Realismus Modding can't do anything with this.
Please verify in:
https://github.com/RealismusModding/FS17_seasons/issues/190
