### ISSUE TITLE
Make 'morning' time configurable

### ISSUE THREAD

**Issue by fdanapfel** [RealismusModding/FS17_seasons#663]
With the latest version it is possible to choose between 'morning' and 'dawn' when using the 'Skip night' function. 'morning' seems to be hard-coded to 6:00.

Would there be a possibility to make the 'morning time configurable, e. g. that I can say morning should be 7:00 instead of 6:00?

**Comment by joskuijpers** [comment]
We will not be adding this as it is very opinionated. I chose 6AM because that is around the time many farmers get out of bed (at least around here).

**Comment by fdanapfel** [comment]
Hmm, that's exactly why I suggest to make it configurable/chooseable, because everybody has its own opinion on what time morning is :)

6AM is far too early for me.

**Comment by joskuijpers** [comment]
Sadly, everyone has its own opinion on everything, and if we would make everything configurable it becomes a very big mess. So this is a no. Note that in Seasons 1.1, it always skipped to 6:00.

**Comment by fdanapfel** [comment]
OK, I'm not happy but I can live with that last explanation.

**Comment by joskuijpers** [comment]
If you want you can just change the code. Src/ssSkipNight.lua, on line 52 it says 6*60, turn it into 7*60 or 8*60 for 7AM or 8AM
