### ISSUE TITLE
Test behaviour of measurement tool on a single tree

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#666]
Plant a single tree and then use the tool. What is the distance between it and the next?

**Comment by joskuijpers** [comment]
![image](https://user-images.githubusercontent.com/5017040/32680551-82bdf9e6-c66b-11e7-85c3-e141264109d3.png)
does not break but shows nearest as 9.6m.

**Comment by joskuijpers** [comment]
Seems very convoluted to get rid of it, so just going to keep it light this.

**Comment by Dzi4d3k** [comment]
Looks like it take starting minimum nearest distance from:
https://github.com/RealismusModding/FS17_seasons/blob/be8edc8ab8858260e98247e60e434886b85cea4d/src/misc/ssTreeManager.lua#L13
and calculates:
sqrt((9.5*9.5)+1) = sqrt (91,25) = 9,5524865872714000895841478762483 =~9,6
here:
https://github.com/RealismusModding/FS17_seasons/blob/be8edc8ab8858260e98247e60e434886b85cea4d/src/misc/ssTreeManager.lua#L82

**Comment by joskuijpers** [comment]
Yep :)
