### ISSUE TITLE
Afternoon sky texture comes way too early in the moring!!

### ISSUE THREAD

**Issue by JoeRoss12** [RealismusModding/FS17_seasons#667]
Whenever morning comes, the texture, which is a nice pretty one...one that I would like to view longer, lasts for only about half to one game hour! And then it turns to the afternoon texture AT 6:00 IN THE MORNING.
Any fix or adjustment to this??

**Comment by joskuijpers** [comment]
Afternoon texture at 6AM? That doesnt sound right. maybe you mean the day texture?

The time is different for each GEO, and it is correct.
