### ISSUE TITLE
Animals

### ISSUE THREAD

**Issue by Nielsen362** [RealismusModding/FS17_seasons#669]
Hi 
Is there any way to fix this problem so we can have others animal types in our map, i get this error
FarmingSimulator2017/mods/FS17_seasons_develop/src/misc/ssAnimals.lua:327: attempt to compare number with nil

thanks in advance

**Comment by joskuijpers** [comment]
Hello,

What mod version is this? Also, what map is this?

**Comment by Nielsen362** [comment]
Dev version from 31.10 and my one map

**Comment by Nielsen362** [comment]
[log101117.txt](https://github.com/RealismusModding/FS17_seasons/files/1462822/log101117.txt)
here is my log

**Comment by Nielsen362** [comment]
yes sorry, i use the script from another map
[regNewAnimals.txt](https://github.com/RealismusModding/FS17_seasons/files/1462845/regNewAnimals.txt

**Comment by joskuijpers** [comment]
Euh yes that will not work. It fakes a Husbandry that has barely any info in it that real husbandries have. You will need to add all attributes available in a Husbandry with true-ish values.

**Comment by Nielsen362** [comment]
Sad i have no idea about making that, i dont know were to start :-)
