### ISSUE TITLE
night/day change

### ISSUE THREAD

**Issue by Friendlyx** [RealismusModding/FS17_seasons#671]
Hi, I tried the new version on Modhub i am in summer and it gets already very bright at around 2am and this happens with a big cut there is no smooth transition. is this wanted or a fault?

**Comment by joskuijpers** [comment]
Alright, we will look into it. Is this every night? Is it going to rain or get cloudy?

**Comment by Friendlyx** [comment]
it was an early summer to mid summer transition and a mid summer day to mid summer day change in all sunny weather.

**Comment by reallogger** [comment]
fixed with 4ab735e
