### ISSUE TITLE
sugercane

### ISSUE THREAD

**Issue by Willykeen** [RealismusModding/FS17_seasons#676]
is there growth for sugarcane in latest dev version? 
or will it grow like barley? i see in the calender it states it needs to be 12 degrees to plant, but has no growth data.

**Comment by reallogger** [comment]
Seasons default growth and weather is not supporting sugarcane as it is too cold for sugarcane to grow. But in a few hours a GEO specifically made for the Platinum DLC will be released. Look for updates on the Giants modhub.

**Comment by Willykeen** [comment]
Cheers!
ive just edited the growth file and taken sugarcane off the default fruit
list. so it just works like barley atm. :)

**Comment by joskuijpers** [comment]
You can download the Paraguay GEO at https://farming-simulator.com/mod.php?mod_id=94824 <https://farming-simulator.com/mod.php?mod_id=94824>

**Comment by Willykeen** [comment]
Just did, thanks guys! :)
