### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by Dzi4d3k** [RealismusModding/FS17_seasons#677]
https://www.fs-uk.com/forum/index.php?topic=199557.msg1298342#msg1298342
vs
https://github.com/RealismusModding/FS17_seasons/blob/240e6eaa1da7dc26c1953b1a2d9550de9b6be8e3/translations/translation_br.xml#L142

Empty lines should fill with English?

**Comment by joskuijpers** [comment]
:( Empty lines do not fill with english. Missing lines fill with MISSING_TRANSLATION maybe.

**Comment by joskuijpers** [comment]
Fixed for next version :)
