### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by alpha117** [RealismusModding/FS17_seasons#688]
Hi All

Seen this in log, and MAP Crashes. Not sure if this is relevant or even know what it means.
Thought I would see what you guys thought

[Seasons] Loading GEO mod 'FS17_RM_GEO_USMidwest'
[Seasons] ssGrowthManagerData: Additional growth data found - loading: I:/FS_Maps/BeaverCreek/FS17_RM_GEO_USMidwest/data/seasons_growth.xml
Error: TipUtil.registerDensityMapHeightType max. number of height types already registered.

Thanks

**Comment by joskuijpers** [comment]
Remove one of the extra fruits from you map, or at least its heaps.

**Comment by alpha117** [comment]
Thanks

Hmm, way beyond me, I'm afraid

**Comment by joskuijpers** [comment]
Tell the map maker ;)

**Comment by alpha117** [comment]
Just have, quick answer from him  'No', oh well no worries

**Comment by joskuijpers** [comment]
Can you send the modDesc.xml of that map?

**Comment by alpha117** [comment]
[modDesc.zip](https://github.com/RealismusModding/FS17_seasons/files/1523879/modDesc.zip)

Here it is

**Comment by alpha117** [comment]
Jos,

 

Did you get the xml ?

**Comment by joskuijpers** [comment]
Try this

[modDesc.xml.zip](https://github.com/RealismusModding/FS17_seasons/files/1525188/modDesc.xml.zip)

**Comment by alpha117** [comment]
Morning Jos

 

Same error I’m afraid. It’s when you use this MOD (attached)

**Comment by joskuijpers** [comment]
You can't use attachments like that via email.
