### ISSUE TITLE
Error log in mod season trouble

### ISSUE THREAD

**Issue by criss20ster** [RealismusModding/FS17_seasons#692]
I have this trouble in mod season in map. i have thsi communicate log 

Error: Running LUA method 'mouseEvent'.
dataS/scripts/BaseMission.lua(365) : attempt to index a nil value
Error: Running LUA method 'update'.
F:/ModyFS17/mods/FS17_RM_Seasons/src/misc/ssPedestrianSystem.lua:18: attempt to index field 'environment' (a nil value)

**Comment by joskuijpers** [comment]
What map?

**Comment by criss20ster** [comment]
NorgeCrest Valley 17 v2.6 / Seasons & ChoppedStraw & animierte Tiertränken

**Comment by joskuijpers** [comment]
Well, there is something weird. This error would also have existed without Seasons.

When exactly does it happen?

**Comment by joskuijpers** [comment]
And can you send a link to the download?

**Comment by criss20ster** [comment]
How to save the game and want to get out of the zero reaction game. Giant error appears

http://uploaded.net/file/31s92z4v

**Comment by criss20ster** [comment]
And tell me how I can privately contact you or where to drink because I have a private matter

**Comment by theSeb1979** [comment]
Closed
