### ISSUE TITLE
Sensible console defaults

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#709]
Consider different defaults on console due to different play style.

- shorter starting season length
- WF on as default

**Comment by joskuijpers** [comment]
Added the WF.

I am divided on the season length: it might be confusing if PC has a different default than console. Have to hear what people say.
If we would do it, the vote seems to go to 6ds.

**Comment by joskuijpers** [comment]
Any thoughts on this? @reallogger @baleBaron

**Comment by reallogger** [comment]
My thought 15 min ago was to just close the issue. Players have learned now and have not heard complaints on any of these.

**Comment by joskuijpers** [comment]
👌
