### ISSUE TITLE
Remove stacks of crops when not stored under roof

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#71]
reallogger [10:41 PM]  
Can't remove root crops - like due to limited possibility to affect heaps or you mean it will break gameplay?

theseb [10:42 PM]  
it will break gameplay
all root crops are now tipped into sheds and they are just a heap
so I think they need to be left alone
mrbear , ahh ok.
so remove all grass windrows and straw if 2 layers or less
why only 2 layers or less?
so people can have straw stacks?
I guess not everybody can afford the hay/straw storage barn
so maybe not all grass windrows then
I think your first idea about grass/dry grass/ straw < 2 layers is the correct way to go 
otherwise people will be forced to bale, which will break game play

reallogger [10:49 PM]  
my vote goes for keeping drygrass and straw that is kept inside. Grass that is just kept in a heap should be affected after a certain period. Same with root crops after 1 year. I don't think it will break gameplay. For straw and drygrass that is kept outside nothing should happen until it rains I think.

theseb [10:50 PM]  
you see that introduces a whole load of complications.
if we implement this now, then we will break gameplay
because then people won’t be able to bale / forage if it rains in the spring/summer/autumn
because we will be trying to remove the windrows
so there are two discussions here I think
one for windrows and one for stacks

reallogger [10:51 PM]  
not if the check is done when the season changes

theseb [10:52 PM]  
well, I think the trouble is that if we start impacting the windrows at the winter, then people will be asking why do the windrows not get impacted during other times
for example, I would like to implement something in the future which makes dry grass turn back into grass windrow if it rains
that forces you to think when you ted and bale when you want hay
because if it rains, you will have to ted again
that would be a cool feature

reallogger [10:55 PM]  
yes agree. But as FS magically makes drygrass when using a tedder there is no waiting for the grass to dry. So until we can turn drygrass back to grass I think removing (or even reducing it like we do with snow) is a good approximation
Root crops could only be affected first day of autumn

theseb [10:56 PM]  
I don’t see why root crops should be affected at all?

reallogger [10:56 PM]  
Since if it is lying around it will be from last years harvest

**Comment by joskuijpers** [comment]
So how is this going?

**Comment by theSeb1979** [comment]
V2

**Comment by joskuijpers** [comment]
What is this about? Do we still want this?

**Comment by Dzi4d3k** [comment]
Abbandoned?

**Comment by joskuijpers** [comment]
Other ideas
