### ISSUE TITLE
Error Log using seasons

### ISSUE THREAD

**Issue by winston9587** [RealismusModding/FS17_seasons#711]
[Seasons] Warning: Density map size of fruit 'wheat' is not the same as terrain
data/vehicles/steerable/lizard/lizardPickupTT.i3d (25.81) ms
[Seasons] Warning: Density map size of fruit 'barley' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'rape' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'sunflower' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'soybean' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'maize' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'potato' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'sugarBeet' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'oilseedRadish' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'poplar' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'grass' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'dryGrass' is not the same as terrain

i am getting this error in my 4x map i added seasons to seasons work but cant figure out how to get rid of these warnings. could someone please help.

**Comment by joskuijpers** [comment]
Hello,

Is this Seasons 1.3? And is this your own map?

What is the file dimension of your fruit layers? They seem to be the wrong size for a 4x map.

Do you have stripes in your growth?

**Comment by winston9587** [comment]
it is version 1.2.1.0 of seasons and the map is the missouri map i converted from fs13 to fs15 and then fs17. i am not sure what you mean about the dimensions of the fruit layers and i did not notice any strips in the growth. sorry the seasons is still new to me.

**Comment by joskuijpers** [comment]
First of all, don't forget to update to 1.3.

Second, then just ignore the warnings. You probably forgot to increase the size of your fruit GDMs. If you don't know what I mean you can ask on forums like www.fs-uk.com :)

**Comment by winston9587** [comment]
ok i know about the gdm can i use one from a 4x map that is already working with seasons ? and i will remember to get the new version of seasons tks.

**Comment by joskuijpers** [comment]
Yes that will most likely work. You might need to clear it out in the editor though.

Don't forget to update your game to 1.5.3 as well. 1.5.3 requires seasons 1.3, and vice versa.

**Comment by winston9587** [comment]
ok i tried several even the fruit gdm from pleasant valley converting it to png then opening the map in ge and re saving it to make a new gdm but keep getting the same errors. other then that the map is error free. the png is 4096x4096

**Comment by joskuijpers** [comment]
did you check pleasant vallley did not have those warnings first?
