### ISSUE TITLE
GEO MOD blocked??

### ISSUE THREAD

**Issue by alpha117** [RealismusModding/FS17_seasons#715]
Morning all

Can you confirm that the GEO's are blocked in the Development version
If it is no problems.
thanks

**Comment by joskuijpers** [comment]
What do you mean, blocked?

**Comment by alpha117** [comment]
Hi Jos

Do the GEO's work OK with the development version?

**Comment by joskuijpers** [comment]
I will confirm later today

**Comment by joskuijpers** [comment]
Which one of the GEO mods do you have issue with?

**Comment by alpha117** [comment]
I'm fine I think. It has been mentioned in the FS-UK forum  that they do not work with the development version

So, thought I would ask the guy that knows :-)

Thanks

**Comment by alpha117** [comment]
Sorted by Rahkiin

https://www.fs-uk.com/forum/index.php?topic=199557.msg1302232#new


Thanks
