### ISSUE TITLE
Crop Moisture

### ISSUE THREAD

**Issue by alpha117** [RealismusModding/FS17_seasons#716]
_**Treshing can only be done when moisture content of the crop is sufficiently low. After rain the crop needs time and sunny weather to dry. Moist summer nights can also occur.**_

Low; is this defined as a number (Wopster meter)?

_**'Disallow threshing when crops are wet of moisture'**_
Is this defined as a number (Wopster meter)?

Also, not quiet 'good' English. Perhaps change it to:
Disallow threshing when crop are excessively wet
Or
Disable threshing when crops have excessive moisture

Then you would have to define 'excessive' with a number eg 16%

So you could also tag the number to the end:
EG:
Disallow threshing when crops have excessive moisture (16%)

Just thoughts

Thanks

**Comment by joskuijpers** [comment]
< 25% allows threshing.

**Comment by joskuijpers** [comment]
3851107
