### ISSUE TITLE
Seasons 1.3 problem

### ISSUE THREAD

**Issue by marvetto** [RealismusModding/FS17_seasons#720]
Game patch 1.5.3.errori in log Seasons moddescription version not valid.i correct the right number but now when i entering the game,i see the map but  its so dark.i download the mod from  official mod hub

**Comment by joskuijpers** [comment]
Are you using 1.5.3? Make sure you do. Also make sure you use Seasons 1.3.

**Comment by marvetto** [comment]
Sorry......my game patch is 1.5.1.....Its not compatible with seasons 1.3?

**Comment by joskuijpers** [comment]
No it is not. Please update.

See the release notes https://www.realismusmodding.com/mods/seasons/manual/release_notes.html
