### ISSUE TITLE
Maintenance not possible

### ISSUE THREAD

**Issue by Friendlyx** [RealismusModding/FS17_seasons#724]
I waited to the end of the days of the maint. period and then after the night to the day the maint was neccessary the game took the maint amount of money from my account and the F1 window still says maint required. Reapair in shop is not possible ( button greyed out). After the next night again money gone and still no way to repair it. With the tractor not overdue I can repair it as described in the seasons manual.

please fix it.

**Comment by joskuijpers** [comment]
If you are on PC, can you send your savegame?

**Comment by Friendlyx** [comment]
yes can do

**Comment by Friendlyx** [comment]
any news?

**Comment by Friendlyx** [comment]
Now my combine came to the repair intervall and i can repair it but I don't know why you charge me 24642€ on the day it is repair day and ever further day aswell and still want 12297€ for repair? Isn't it bad enough that the engine fails from time to time when no money for repair?

**Comment by joskuijpers** [comment]
We are looking into any possible issues.

Having a failing engine is the result of not repairing. So you need to repair. They are together what makes the system, they complement each other. Removing either breaks it.

**Comment by reallogger** [comment]
The issue with this tractor is that it has an age of 201 days and has 189 hours on it. So it is time to replace it with a newer model. 

I see in the savegame that many of the vehicles have age more than 200 days. Is this an old savegame from vanilla where you did not start fresh with Seasons?

**Comment by reallogger** [comment]
Fixed with f90bab0
