### ISSUE TITLE
Not repair

### ISSUE THREAD

**Issue by Paul2510** [RealismusModding/FS17_seasons#725]
Hi! I have the problem i cant rapair  tractors!

**Comment by joskuijpers** [comment]
Hello,

Can you please explain which machines? Did you try driving them to the shop and opening the Direct Sell / Configure / Repair dialog?

Are you on PC or console? What Seasons version are you using?

**Comment by Paul2510** [comment]
Sorry! z.B. NH Fleet FBM fendt700! I tried it in the shop and at the workshop! PC!

**Comment by Paul2510** [comment]
Yes i driving to shop and opening the Direct Sell / Configure / Repair dialog but there is no repair! its pc version
![bild1](https://user-images.githubusercontent.com/10115244/34322338-a52db2ca-e824-11e7-91b6-b014f378e7f2.png)
![bild2](https://user-images.githubusercontent.com/10115244/34322339-a56376b2-e824-11e7-9168-9e2277f340a2.png)

**Comment by DaveBrune** [comment]
I have the same issue, except it's not all tractors just some of them.  If I go back to the previous version of Season's it works fine.  Also, this is on the PC and using tractors that came with the game, no modded tractors.

**Comment by reallogger** [comment]
This is an issue when the repair cost becomes more than 1.5 times the sell price of the tractors. So happens only at tractors with very high hours.

**Comment by DaveBrune** [comment]
Odd because I have one tractor with more hours that I can repair, but the one I can't has less hours.  Makes no sense.

**Comment by joskuijpers** [comment]
Makes perfect sense, because the algorithm also uses age, and original price, and HP into account.

**Comment by Paul2510** [comment]
I understand the Problem when the vehicle have to many OperatingTime  they can`t repair ! Sorry for may english!
