### ISSUE TITLE
silage-bale-fermenting (creative-mesh)not compatible with seasons?

### ISSUE THREAD

**Issue by cabmac** [RealismusModding/FS17_seasons#727]
Hi, seems, that fermenting silage-bales is not compatible with the straw-addon-bale. It turns directly in silage...is there any solucion with that?

BG, Claudio

**Comment by baleBaron** [comment]
Thank you for your report.

What bales are you talking about here? Is it the bales created by the Krone Comprima or the Big Pack HDPII? If it's the Comprima bale, which bale size was it?

This should work as I am very sure we tested this, but we may have to do it again.

**Comment by cabmac** [comment]
hi, it was the Comprima, size 1.30mtrs, grassbales wrapped with McHale 991 LBER ( [http://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=95001&title=fs2017](url) ) ...the bales were converted in silage directly...

[url=http://www.imagehub.de/display-i4818bzpygj.html][img]http://www.imagehub.de/thumb-i4818bzpygj.png[/img][/url][url=http://www.imagehub.de/display-i4819bekn0x.html][img]http://www.imagehub.de/thumb-i4819bekn0x.png[/img][/url][url=http://www.imagehub.de/display-i4820bskh34.html][img]http://www.imagehub.de/thumb-i4820bskh34.png[/img][/url]

**Comment by baleBaron** [comment]
Thanks, very good information.

The issue appears to be with the bale wrapper. As it does not use the standard base game baleWrapper specialization, seasons will not recognize it.

The author of this mod will need to update his mod to include some sort of seasons support to solve this. If he contacts us on slack we can help him out.

**Comment by cabmac** [comment]
ah,ok, thank you...:)
