### ISSUE TITLE
lost much grass in trailer

### ISSUE THREAD

**Issue by Sheldon311** [RealismusModding/FS17_seasons#728]
I am always lost grass in the trailer. Even if I start mowing at 23:00, everything is gone at 24:00. That's unrealistic! you should not lose grass in the trailer. And certainly not so much it can not be that half is gone.
Change that please !!!

**Comment by baleBaron** [comment]
The idea is that at midnight (24:00) time jumps ahead (is fast forwarded). 
If you are playing with 9 days per season for example, the year will progress about 10 days each midnight.

If you think about it in this way it does not seem unreal anymore?

**Comment by Sheldon311** [comment]
But that is unrealistic! And it's not fun!
Please make it so that I can turn it off!!! Otherwise it is not fun to play with the mod! (that just destroys everything)

**Comment by reallogger** [comment]
It is not unrealistic that wet grass rots quickly. There are also some game limitations we have to work with. Grass rotting might be tuned in a later version, but will not be turned off. Thus closing the comment.

Will create a new issue for your problem with the menu.
