### ISSUE TITLE
Skipnight FFWD getting stuck

### ISSUE THREAD

**Issue by baleBaron** [RealismusModding/FS17_seasons#729]
> I have FS17 on PS4 and I have noticed a bug when I am playing seasons mod on Estancia Lapacho. When I get to the point of being able to "Skip Night", I do it and the game advances through the night. The problem is, one of two things always happens. One is it will not leave the "skipping" mode and I will get an hour glass figure while it just continually advances through days and won't stop. The other thing that happens is that the "skipping" mode will stop and the hour glass will go away but then my game is stuck on 3000 game speed and It goes through a day in about 8 seconds and won't let me stop it or change it in the menu as none of the buttons work. Super annoying and I need help!!

**Comment by Gonimy-Vetrom** [comment]
I have this happening on the PC. 
But I did not write about it, because this is a problem of the high speed of time that the mod adds. But in the game there is no such speed.

**Comment by joskuijpers** [comment]
All I currently found was 78c001836f2ac48bcadb1ee59d84261eb32115cd

As nightEnd is bound to be 12:00 or below, when it was 12:00 it would not stop skipping night on that day. It ought to stop sometime though...

**Comment by Friendlyx** [comment]
I had this today too, was a midsummer day I started skip night at around 9pm and then a day by day passed by without any stop. no errors in log.

**Comment by joskuijpers** [comment]
Thank you, this is actually helpful. It means it is random, which rules out everything non-random.

**Comment by joskuijpers** [comment]
It seems it does not actually get stuck, but just takes very long to hide the dialog. That is what I could reproduce, at least.

Seems that is not what is described by the player though...

**Comment by Friendlyx** [comment]
I had this aswell, that it takes very long to finish a night skip but thats not what happened yesterday. time flew by it was bright dark bright dark and so on. So I guess it was skipping days and nights.

**Comment by joskuijpers** [comment]
And this was on PC? @Friendlyx

**Comment by Friendlyx** [comment]
it was on PC, yes

**Comment by joskuijpers** [comment]
Did you use any GEO mods? Any other fast-forward mods?

**Comment by Willykeen** [comment]
I had this issue today, i used the ffwd mod to pass about 3 hours and then
skipped night at 10. Passed through 5 days and then stopped, it also showed
5 days had progressed in the seasons calander too.
I will be on again tonight. So i will grab screen shots as well as send a
log.

**Comment by Friendlyx** [comment]
yes geo mod is installed but no other fast fowd mod.

**Comment by joskuijpers** [comment]
Which GEO mod?

**Comment by Friendlyx** [comment]
it was the western germany geo mod -> I modified some temperatures to get it more cold in winter but thats it. so basically the same as the one on modhub. Still only happend once

**Comment by Friendlyx** [comment]
never happened to me again since last post

**Comment by theSeb1979** [comment]
Not seen for a while. Assume fixed
