### ISSUE TITLE
clock/date hud does not overlay correctly

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#73]
With changing amount of money the clock moves right/left. The clock/date overlay does not follow.

**Comment by theSeb1979** [comment]
On a new game the clock does not overlay properly

![fsscreen_2016_12_15_16_11_52](https://cloud.githubusercontent.com/assets/23258759/21231839/9693cee8-c2e1-11e6-89b8-2f4bde76a211.png)

**Comment by reallogger** [comment]
Fixed with https://github.com/RealismusModding/FS17_seasons/commit/4cc52578e5eecb375b1c52c6e85f1ba84ede1e81
