### ISSUE TITLE
Fine tuning season' text

### ISSUE THREAD

**Issue by turbostar190** [RealismusModding/FS17_seasons#730]
Is it possible to scale a bit less the season's text so it doens't overflow on side lines with italian language?

![fsscreen_2018_01_02_14_41_20](https://user-images.githubusercontent.com/24813315/34531212-e24c94b0-f0b1-11e7-9f3a-7b15b76abeac.png)
![fsscreen_2018_01_02_14_43_29](https://user-images.githubusercontent.com/24813315/34531215-e4c7d916-f0b1-11e7-8568-f0cd22f0a891.png)

**Comment by joskuijpers** [comment]
Hmmm. Is there a way to write that Italian text in a shorter way? The game does not have support for autoscaling text and it would be a bit of a performance issue to implement correctly.

**Comment by turbostar190** [comment]
Not properly, it would be like writing "Early Spri." or "Lat. Spri." so it wouldn't be nice to see and so efficient remove only one or two letters adding a dot. I'm the first to say no to the autoscaling integration but I would propose to reduce a few pixels text size for all languages in that window.

**Comment by turbostar190** [comment]
Something like these at [line 268 of WF](https://github.com/RealismusModding/FS17_seasons/blob/develop/src/environment/ssWeatherForecast.lua#L268) ?
```lua
if g_languageSuffix == "_it" then
	renderText(clockX, g_currentMission.timeBgOverlay.y + 2 * self.marginY, self.textSize * 1.4, clockText)
else
	renderText(clockX, g_currentMission.timeBgOverlay.y + 2 * self.marginY, self.textSize * 1.5, clockText)
end
```
or maybe even better
```lua
if ((g_languageSuffix == "_it") and ((tostring(ssUtil.fullSeasonName(g_seasons.environment:transitionAtDay(forecast[1].day))) == ssLang.getText("SS_SEASON_FULL_NAME_1")) or (tostring(ssUtil.fullSeasonName(g_seasons.environment:transitionAtDay(forecast[1].day))) == ssLang.getText("SS_SEASON_FULL_NAME_3")))) then
	renderText(clockX, g_currentMission.timeBgOverlay.y + 2 * self.marginY, self.textSize * 1.4, clockText)
else
	renderText(clockX, g_currentMission.timeBgOverlay.y + 2 * self.marginY, self.textSize * 1.5, clockText)
end

```

**Comment by theSeb1979** [comment]
Super low priority. Unlikely to be fixed.
