### ISSUE TITLE
Growth issues

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#732]
Since version 1.3 there has been several issues with growth. Two problems:
- crops more or less randomly becomes harvestable 1 or more transitions too early
- winter crops fail to germinate and turns to harvested in the beginning of spring

See following topics:
- ~~~https://www.fs-uk.com/forum/index.php?topic=199557.msg1303816#msg1303816~~~
> I guess I am not understanding the growth right or something. I thought that grass grew at every transition

Isn't this just someone not understanding grass?

- ~~~https://forum.giants-software.com/viewtopic.php?f=893&t=112321&start=1920#p958218~~~
> -Base Seasons mod only-
> Planted corn (and soy) at start of summer (Day2)
> Whole corn crop died before end of summer
> 
> The only thing I can think of is ground temp dropped too low?
> Soybean runs at same temp, it survived.

- https://forum.giants-software.com/viewtopic.php?f=893&t=112321&p=957420#p957218
Calendar changes over reloads

- ~~~https://forum.giants-software.com/viewtopic.php?f=893&t=112321&p=957420#p957156~~~
> I planted wheat, barley and canola on spring day 1. I am currently on summer day 2 and all of my crops are ready to be harvested and I have been able to successfully harvest them.

**Comment by joskuijpers** [comment]
Okay. for this I need a way to reproduce it. After that I can do debugging.

Any suggestions?

**Comment by joskuijpers** [comment]
More possible issues:

https://forum.giants-software.com/viewtopic.php?f=893&t=112321&start=2010#p960511

If all of them are using SkipNight, the problem could be in there as well.

**Comment by joskuijpers** [comment]
Calendar has been fixed.

**Comment by reallogger** [comment]
Still one fix to be made by moving normalGrowth to after extraGrowth in GM. I propose to move L226-L229 to after current L235

**Comment by theSeb1979** [comment]
Fine. I can do this tonight then

**Comment by joskuijpers** [comment]
Will this break any existing GEOs? Or fix them? Does this need an update for GEOs on the PC side?

**Comment by theSeb1979** [comment]
It will not break any existing stuff but it will fix some of the weird issues that are occasionally reported with certain geos. I foresee no changes required to any geos but will check them as well this week.

**Comment by reallogger** [comment]
Won't break anything. It is just changing the order of how growth is applied. It will fix one small thing in the Midwest GEO and make the two new GEOs (Southern Australia and East Canada) work as they should.

**Comment by joskuijpers** [comment]
Can we release the two new GEOs in a way that works with the current (unchanged) model, for console?

**Comment by reallogger** [comment]
They won't break anything, but some crops will mature quicker than planned. I can assess the consequence and then we can make a decision based on that.

**Comment by joskuijpers** [comment]
Okay. What we could do is have a different version for console with changes so it is 'better', if needed.

**Comment by joskuijpers** [comment]
If the new GEOs can't work on 1.3, make sure to increment the simpleVersion with 1 in package.json and also update the seasons version in the GEO modDesc.xml. Then the GEO will not run on 1.3, but 1.3.1 only.

**Comment by theSeb1979** [comment]
This can be closed now
