### ISSUE TITLE
Repair not possible

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#733]
Repair is now not possible if the repairCost is more than 1.5 times the sellPrice. Need to consider whether this should be tuned/changed.

see also #724

**Comment by Friendlyx** [comment]
As you already know, I am not a fan of this feature. I would like some options for that to adjust it personally.

**Comment by joskuijpers** [comment]
We will not be adding options for this, but we are looking into permanent fixes.

**Comment by joskuijpers** [comment]
@reallogger I suggest we do not override the sell button anymore, but the customise/configure button instead. Then you need to repair to customise, but then we don't need to decide between selling or repairing.

Sadly I can't add a 4th button

**Comment by reallogger** [comment]
Alternative would be to go back to using key combo for repair as before 1.3

**Comment by joskuijpers** [comment]
Yes but there the detection of the vehicle was shoddy, and we need it to be reliable especially on consoles.

**Comment by reallogger** [comment]
I believe the problems with detection of the vehicle was since we required a smaller distance between the trigger and the vehicle node before?

**Comment by joskuijpers** [comment]
Not sure. I increased it in 1.2 but there were still issues. Now it is the issue of GIANTS.

Also, the way the game detects the vehicle is not fps hungry. I would prefer to keep it like we have it now: inside the sell dialog.

**Comment by Friendlyx** [comment]
isn't it possible to make a maintenace menu in the seasons menue "alt s" ?

**Comment by joskuijpers** [comment]
No because that makes it only harder to select your vehicle, and is more disconnected from the vehicle itself. Also it is no fun.

**Comment by Friendlyx** [comment]
ok didn't know that it is harder to select vehicle

**Comment by reallogger** [comment]
Keeping it at the sell button, but repair is now always possible, even when repair cost is much higher than sell price. 

Fixed in f90bab0
