### ISSUE TITLE
Non-owned non-leased vehicles need repair but can't be repaired

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#734]
Apparently they have propertyState="0"

- 0 = not owned
- 1 = owned
- 2 = leased

**Comment by reallogger** [comment]
So only do repair if propertyState="1"?

**Comment by joskuijpers** [comment]
I guess so yes.

If only maintenance costs are applied when it is 1, then all we need to do is hide the text in the F1 menu, and not do the motor failure

**Comment by turbostar190** [comment]
Little correction:

- 1 = owned
- 2 = leased
- Any other number = not owned

**Comment by joskuijpers** [comment]
This might work in practice, but the game defines 0 as not owned, so we will stick to that. Will check for `~= owned`

**Comment by joskuijpers** [comment]
This needs a bit of more testing
