### ISSUE TITLE
Maintenance Costs 

### ISSUE THREAD

**Issue by dominiczeth** [RealismusModding/FS17_seasons#741]
Yesterday i noticed really high Maintenance Costs from my Horsch Evo 12m (Horsch DLC) Sowing machine. Costs where over 6000€! per day. It is 46 Days old and was used for 25h. That's way too high, even my big Harvester has costs under 500€ per day. I noticed high Costs also on the Lemken Gigant 10 (500€ per day but only 4H used).
So it seems there "could" be a problem with Implements. Trailers looked good i think. I use the most recent Dev version though. Don't know if it's a problem in the Modhub Version. 

How is the Maintenance cost calculated? It seems to use the base price, is that right? Tell me if you need more information about this issue.

**Comment by agp8x** [comment]
You think that's bad? How about 23299€ per day for a rather new Stara Estrela 32, or 74174€ per day for a Rostselmash RSM 161?
(Fresh install, MR 1.1.1.4; Seasons from Modhub)
![fsscreen_2018_01_22_08_45_47](https://user-images.githubusercontent.com/1840171/35591366-01d9a710-060a-11e8-9b9a-4fec559155f0.png)
![fsscreen_2018_01_22_08_46_28](https://user-images.githubusercontent.com/1840171/35591367-01f70f76-060a-11e8-9621-3a5b395ed12d.png)

**Comment by joskuijpers** [comment]
Please send us your savegame.

@reallogger

**Comment by reallogger** [comment]
What version of Seasons is this? Latest on modhub or develop?

**Comment by agp8x** [comment]
I was using 1.3.0.0 of Seasons. (As I stated, the current Modhub version;))
With the develop-branch the maintenance seems reasonable again. (537€/749€ for my two examples; just took a quick look inte the garage)

**Comment by reallogger** [comment]
Yes sorry, I was a bit quick there about the versions. 

Good that it is now reasonable with the latest version. 

@dominiczeth : your issue is related to end of life for that seeder. Maintenance becomes very expensive after 25 hours on planters.

**Comment by dominiczeth** [comment]
25h isn't really much though. I've big fields so I only need two years for that.

**Comment by bronney** [comment]
Hey RM! thanks for a fantastic mod :)  I do have 2 questions:
1. Do the red numbers under the Vehicle Overview screen mean "end of life"?  Time to sell reminder?  My Lely Juno maintenance was 18,000.  I sold them before I click save, phew..
2. My 2600 Suer weight shows a red $3 maintenance when the cost per day should be $0?  Does weights have "end of life"?

I am playing with the current modhub version.

**Comment by reallogger** [comment]
High maintenance costs should be fixed with f4c9685.

End of life is now corresponding to <lifetime> in the repairFactors.xml

@bronney:
1. In latest modhub version we don't control the colour of the numbers. In develop it will show red when repair is required.
2. In latest develop maintenance for weights are now zero. Same for anything else that has dailyUpkeep 0 in the vehicle.xml.
