### ISSUE TITLE
Goweil LT Master opening bale hack.

### ISSUE THREAD

**Issue by bronney** [RealismusModding/FS17_seasons#742]
Dear RM,

I edited 1 line each in 2 LUA to bring the open bale function back to the LT Master with seasons.  I am guessing they are put in to prevent accidental opening of "fermenting" silage?  So far it doesn't seem to affect any aspect of my games I am wondering why they put those lines in in the first place and aggro so many of us who uses both mods.  The fermenting is fixed as far as the last time I tested.

I basically changed if g_season == nil to ~= nil.  I realize this will break the func for anyone not running seasons but I am not taking out that nested if atm.  What was the reason they implement this you think?

The lines I edited is below:
balesInfos.lua - Line 51 - if g_seasons ~= nil then

`function BaleInfos:draw()`
`    if g_seasons ~= nil then`
`        if self.textBaleInfos ~= nil and g_currentMission.player.lastFoundBale ~= nil and g_currentMission.player.lastFoundBale.nodeId ~= 0 and g_currentMission.player.currentToolId == 0 then`
`            local x, y, z = getWorldTranslation(g_currentMission.player.lastFoundBale.nodeId);`
`            BaleInfos.renderTxtBale(x, y, z, self.textBaleInfos, getCorrectTextSize(self.fontSize), 0);`
`        end`
`    end`
`end`

baleEviscerator.lua - Line 33 - if not g_currentMission.missionDynamicInfo.isMultiplayer and g_seasons ~= nil then

`function BaleEviscerator:update(dt)`
`    if not g_currentMission.missionDynamicInfo.isMultiplayer and g_seasons ~= nil then`
`        self.baleObject = nil;`
`        self.eviHud:setIsVisible(false, true);`
`        if g_currentMission.player ~= nil and g_currentMission.controlledVehicle == nil and g_currentMission.player.lastFoundBale ~= nil and g_currentMission.player.currentToolId == 0 then`
`            self.baleObject = g_currentMission.player.lastFoundBale;`
`            self.eviHud:setIsVisible(true, true);`
`        end`
`        if self.baleObject ~= nil then`
`            g_currentMission:addHelpButtonText(g_i18n:getText("input_EVIBALE"), InputBinding.TOGGLE_COVER, nil, GS_PRIO_VERY_HIGH);`
`            if InputBinding.hasEvent(InputBinding.TOGGLE_COVER) then`
`                BaleEvisceratorEvent:sendEvent(self.baleObject);`
`                self:evisceratesBale(self.baleObject, true);`
`            end`
`        end`
`    end`
`end`

**Comment by joskuijpers** [comment]
You should send this to Tykonket.

**Comment by bronney** [comment]
Thanks dude I fired him a message.

https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/issues/73
