### ISSUE TITLE
Issues with smaller maps

### ISSUE THREAD

**Issue by HeavyShid** [RealismusModding/FS17_seasons#745]
Good evening,

I found an issue with maps that are smaller than the original ones, so 1/4 maps instead of normal-sized maps. It occured when I tried to play with seasons on the "Schleswig-Holstein" map: (https://forbidden-mods.de/wcf/filebase/file/3851-schleswigholstein/). 
The terrain attribute "unitsPerPixel" was changed from 2 to 1 to achieve the smaller terrain with better resolution than bigger ones. Emil Drefers wrote on the giants developer site that this is a possible way to scale a map. Another way is to scale down the _dem heightmap, but these results are not as accurate as in the first way. 

Now the problem itself: 
-Seasons can't create snow layers. It doesn't work with the console or even in winter with normal falling snow. 
-You cannot manipulate the growth of fruits. When loading the game it is possible that it resets the growth, but ingame while playing you can't change the growth state through the console. If you save and reload the game the growth change appears. 

I tested it on the Schleswig map and also on Lossberg and the original map as SampleModMap. I tested  both ways of getting a smaller terrain and both do not work. I also tested to change the value of unitsPerPixel to 4, to get a 4x map and it worked with seasons. Snow was showing up and the growth was manipulateable. 

I don't know if there is just a "update" function where you try to cover the whole map and it is restricted on minimum 2x2 km, but because it affects the snow and the growth there must be something like that that's messing up everything. 

I would like to play with seasons, even on smaller maps. I hope you can find something about it. 
Thansk in advance.

**Comment by theSeb1979** [comment]
Sorry, but this is unlikely to be fixed.
