### ISSUE TITLE
oil radish growth

### ISSUE THREAD

**Issue by Friendlyx** [RealismusModding/FS17_seasons#747]
planted oil radish in autum to protect fields in winter and get nice green fertilizer in spring but the oil radish does not fertilize the field. maybe this is a seasons issue.

**Comment by theSeb1979** [comment]
Can you provide more info on what other mods you are using. I’ve used oil seed radish quite a lot and never had a problem with it not fertilising fields.

**Comment by Friendlyx** [comment]
did you plant it in autum and tried to fertile the fields after winter(in spring). When I plant it and use it as soon as it is ready for fertilizing it works but not if it is fully grown before winter and used after winter.

**Comment by Friendlyx** [comment]
today planted oil seed on 2nd autum day. I have 9 day season. lets see what happens after the winter when plowing.

**Comment by Friendlyx** [comment]
today its spring again and the oil seed is beeing plowed in but its not fertilizing. not with plow and not with the grubber. there must be something wrong with plant death in winter. the palnts are not shown dead but they do not work.

**Comment by Friendlyx** [comment]
sorry after some rows with the plow it revealed the dark blue on the map. So plowing works.

**Comment by theSeb1979** [comment]
There is no issue. I have tested it.
