### ISSUE TITLE
Instable change of seasons for vehicles

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#749]
https://forum.giants-software.com/viewtopic.php?p=973601#p973933

**Comment by reallogger** [comment]
There are two different bugs

I see two ways to fix these:
1. L433 in ssVehicle should use currentDay from g_currentMission not g_seasons + shift ssLastRepairDay for the change in season length
2. Make daysUntilRepair relate to currentDay in g_seasons consistently
