### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by duffstone** [RealismusModding/FS17_seasons#752]
Truly a low priority request,  but would there be any way to work the following in at some point?

1)  have an option to return growth management back to the Giants Engine defaults.
2)  with the above option, have a new growth.xml that controls when crops wither for winter (offseason).

so far the biggest issue with seasons is the huge amount of downtime waiting for seasonal transitions when running smaller farms. if you give growth control back to giants so that crops go back to growing by days, not transitions, then have seasons wither and stunt crops over a winter / off season period,  you'll solve this downtime issue and prevent folk from having to fast forward / skip nights / change timescales.    However, by controlling (and forcing) crops to wither / go back to growth stage 2 during an off season period, you still maintain that realistic downtime season.

so for example, by Giants default, you start with modest equipment and a small hold of land.  with this setup, even with 3 day seasons played on 15x you'll have your fields plowed, fertilized and seeded to max levels in a day or two, with at least two more transitions (depending upon current season) to wait.    While there are many things you can do to fill this time, none are able to fill ALL that time, even in concert.   Tons of people are fast forwarding, skipping nights, and starting with large farms to try and combat this plethora of downtime.   However, if you just returned to the Giants standard of growing by default time scales, and limit your downtime to winter months, you better balance the desired Realism with Gameplay.

It's really that balance that I'm proposing. if you can think of a better idea that's fantastic. but seasons is sacrificing realism for the sake of realism which nets a distinct loss of gameplay in the simulation.   let's try to keep the realism, without limiting our gameplay. :-)

-Duff

**Comment by joskuijpers** [comment]
Hi,

Thanks for your input.

This is however not the way we are trying to look into the downtime issue. Re-enabling the default growth breaks the whole game, actually.

Make sure you don’t play at 1x but at 5x or 30x.


Regards,

Jos
