### ISSUE TITLE
Ground temperature in v2.0

### ISSUE THREAD

**Issue by Fracking** [RealismusModding/FS17_seasons#753]
Hi,

I started a new save to test the (awsome) new features of seasons v2.0 (v2.0 is not working with my existing save game.). Now I´ve noticed that the ground temperature doesn´t rise. It remains at 4°C (starting condition) even in early summer with temperatures at like 20°C in late spring. Here is my [log](https://gist.github.com/Fracking/921c6685ac3340e6935508c9d98d52be). Is there an issue on my end?

Best regards,

Fracking

**Comment by joskuijpers** [comment]
v2.0 is very much in development and far from working.
