### ISSUE TITLE
Oats

### ISSUE THREAD

**Issue by tomatoamong** [RealismusModding/FS17_seasons#757]
Hired work wont harvest Oats even though it is time to Harvest according to the Calendar. Please see picture. https://imgur.com/a/RpLwq

**Comment by theSeb1979** [comment]
The calendar shows the planting and harvesting windows. It then depends on when you actually planted and when they germinated. It does not magically goes to harvestable at the beginning of the harvestable window, which would be the ideal case (planted when it was first sowable and germination temperatures were favourable) The oats aren’t actually ready to harvest. 

What is the map? Often additional fruits are not set up correctly sadly by the map maker.

**Comment by theSeb1979** [comment]
Oops. Wrong button.

**Comment by tomatoamong** [comment]
You are right the oats are still growing. The map is Dondiego map

**Comment by theSeb1979** [comment]
I looked into this map. Unfortunately the additional fruits have not been set up correctly, therefore the oats (and all other additional fruits) will never become harvestable. You need to unzip the mod, open modDesc.xml and look for maxHarvestingGrowthState. There will be 7 instances. 

Change maxHarvestingGrowthState="7" to maxHarvestingGrowthState="6"

Save the file and zip up the mod again. Then the additional fruits will work properly.

**Comment by tomatoamong** [comment]
Thanks for your help. I will try that.

**Comment by tomatoamong** [comment]
I am now having a simular problem with Rye. Do you have a fix for this ?

**Comment by theSeb1979** [comment]
It’s the exact same fix as before.
