### ISSUE TITLE
seasonChanged event triggered incorrectly on day 2 in a new game regardless of daysInSeason

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#76]
there is a bug in the seasonChanged event
it gets triggered at the end of the first day on a new save game

this bugs out the intro display since it announces that it's spring
but on day 2 we are already in spring

thus the very first spring intro message should be announced just after the game loads initially. maybe check for savegame == nil

then resume normal event checking and getting current season to be able to announce the next spring

**Comment by joskuijpers** [comment]
Very simple reason:

SeasonChanged is generated on the first dayChanged when lastSeason != currentSeason. The first dayChanged event is after the first day :) Changing

**Comment by joskuijpers** [comment]
I changed some code, and now the seasonChanged and growthStageChanged are also triggered at the very start of a new game.

**Comment by joskuijpers** [comment]
@theSeb1979 you need to retest the initial new-game startup stuff. When the game starts, the growthStageChanged() with state 1 is called. You could even use that probably

**Comment by theSeb1979** [comment]
I have never needed growthstagechanged to be called initially. It complicates things needlessly. Is there any other code this needs? Weather manager?

With this change I am pretty sure that GM is going to try grow things incorrectly.

**Comment by joskuijpers** [comment]
Well, this is now how it should be :P It now tells the game that it has become state 1 (early spring) when it actually becomes early spring (start of the game). Its code is intertwined with seasonChanged
