### ISSUE TITLE
Issues when starting a new game on either Goldcrest Valley or Sosnovka with both Seasons and Straw Harvest

### ISSUE THREAD

**Issue by knuuud** [RealismusModding/FS17_seasons#760]
This issue appears on the two standard maps of the game only, but it is getting annoying having to choose between Seasons and Straw Harvest.

Log sais:
 C:/Users/knuta/OneDrive/Documents/My Games/FarmingSimulator2017/pdlc/strawHarvestAddon/palletSellPoint/palletSellPoint.i3d (170.60) ms
Error: Running LUA method 'loadMapFinished'.
H:/Dropbox/FarmingSimulator/Dedi17/FS17_RM_Seasons/src/environment/ssReplaceVisual.lua:231: attempt to index field 'loadedPlaceableDefaults' (a nil value)

Is there any easy fix for this to use both these addons?

**Comment by stijnwop** [comment]
Its happens because the straw add-on loads a placeable earlier then the vanilla game does.

It's known and should be fixed in the next update.

**Comment by stijnwop** [comment]
Fixed with a594f80.
