### ISSUE TITLE
Platinum Edition Estancia Lapacho new game sugar cane instantly goes to 'harvested' when planted

### ISSUE THREAD

**Issue by marcbaas** [RealismusModding/FS17_seasons#761]
I've tried this on multiple occasions, but whenever I install Seasons, then start a new game and plant sugar canes, they instantly go to 'harvested' state, even though it can be sown all year through and the ground temperature is over the minimum required temperature.

Could this be a bug by any chance?

**Comment by theSeb1979** [comment]
Are you using the Paraguay geo mod? Instantly goes to harvested? That isn't even possible with how the mod works. What exactly do you mean by instantly?

**Comment by eraaspr** [comment]
I noticed the same thing. But the sugarcane field starts to grow after the next growth stage. Worse is about the other crops, like wheat and canola. These fields have been seeded twice but after next growth stage they show up as harvested like the fields on the map that I don't own and are seeded other than sugarbeets. I use the Paraguay add on for seasons mod and it doesn't work for me.

**Comment by theSeb1979** [comment]
Then you are seeding at the wrong time if wheat is going to harvested.

**Comment by eraaspr** [comment]
Even tried unchecking almost every other mod before starting the game. The only mods I had was courseplay and drivecontrol. Someone else trying out the seasons mod with the Paraguay add on?

**Comment by eraaspr** [comment]
ok, will check more careful when I'm seeding to see what's what. Thanks for reply.
