### ISSUE TITLE
Grass Rotting

### ISSUE THREAD

**Issue by adamp1986** [RealismusModding/FS17_seasons#766]
Hi, I love your mod, but I feel there is one area where it makes my game play difficult. Coming from a farming background it is very uncommon that grass would be foraged or baled the same day as mowing.

I feel that it would be better to have the rotting feature set to each seasonal change and not each night, in my oppinion playing on a 9 day season (as I do) 3 days should give me plenty of time to play realisitically, where I would mow all my grass one day and then windrow and then harvest the next day without any loss in quantity.

This is the only fault I have with your mod, everything else is excelletn and makes gameplay much more realistic, which is what I am looking for!

I look forward to hearing your oppinion.

Thanks

Adam

**Comment by Friendlyx** [comment]
agree

**Comment by jesterlol** [comment]
agree
