### ISSUE TITLE
Not an issue but looking for information

### ISSUE THREAD

**Issue by n4396t** [RealismusModding/FS17_seasons#767]
Hi, I'm looking for how high the scale goes for the germination temperature.  I'm editing the growth.xml file to a Geo for a map that has cotton.  The germ temp for sugarcane is set to 12 which translates to 54 deg F in the game.  In the area where the map is located cotton needs a soil temp of 60 deg F for germination so I set the germ temp to 14 and the temp in the game actually went from the 54 set at 12 to 52 set at 14.  Is 12 as high as the scale goes?

**Comment by joskuijpers** [comment]
This is not a scale.

The numbers you put in the file are degrees Celcius. Everything is in Celcius. It might be best to play in Celcius too.
