### ISSUE TITLE
Straw / Hay rotting

### ISSUE THREAD

**Issue by moep0710** [RealismusModding/FS17_seasons#769]
It would be awesome if baled straw or hay would not go away. Instead there should be a process like the fermenting process, leaving a manure bale.
Same for dropped straw/hay.

**Comment by joskuijpers** [comment]
We have considered this quite a while ago and decided against it. It clutters the map and makes it harder to work with as well: the only way to pick up manure is with a shovel. On top of that, we can't automatically remove manure otherwise manure pits would empty
