### ISSUE TITLE
Hide Huds

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#77]
It would be nice to have all huds disappear either with in mod functions or to work with hud hider.  Currently only the the weather forecast seems to be removed with hud hider.

**Comment by joskuijpers** [comment]
Can you give a link to 'hud hider' ?

**Comment by lindbejb** [comment]
https://www.modhoster.com/mods/hud-hider-17-by-clod

**Comment by Dzi4d3k** [comment]
I think that hud hiding from Game Extension mod is better as it is capable of hiding mods related huds :)

**Comment by lindbejb** [comment]
link?

**Comment by reallogger** [comment]
Yes we are aware of this issue. 

Link to game extension:
http://modcentral.co.uk/resources/game-extension.102/
