### ISSUE TITLE
[economy] Reduce worker wages

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#8]
Need to consider the effect this will have on the game's economy. If a player cannot sow and harvest all in one day and with the addition of long crop growth cycles, this will make the game unplayable without cheating in my opinion. I have tried figuring out how to reduce the AI worker wages and I cannot do it. It's all in AIVehicle specialization. 

self.pricePerMS = Utils.getNoNil(getXMLFloat(self.xmlFile, "vehicle.ai.pricePerHour"), 2000)/60/60/1000;

https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=1546#load21532

Normally you would overwrite that, but I have no idea how to do this in Lua/FS and I am not sure if it's possible. It may not be, since there are no mods that do it. I have spent time trying to figure this out and I am none the wiser.

**Comment by joskuijpers** [comment]
I had an idea (currently not near a computer and wont be for a while): maybe we can override the global getXMLFloat function:
(This might nog work if getXmlFloat is a native function, not sure)

```lua
local gfOriginal = getXMLFloat;
function newGetXmlFloat(file, prop)
    if prop == "vehicle.ai.pricePerHour" then
         return 100.0
    end

    return gfOriginal(file, prop)--fallback
end
getXMLFloat = newGetXmlFloat
```

**Comment by joskuijpers** [comment]
Actually, seb, I think this might work (unless there is another environment but then still I might know a way). Could you try this out? Put it in the ssSeasonsMod, and use 1 for wage and turn on a hired worker :)

**Comment by joskuijpers** [comment]
Yeah that was almost the way to do it. Just had to put it in the 0th environment. So I hcke dit together and now we can change the wages.
Only a matter of defining what it should be.

**Comment by theSeb1979** [comment]
Not had a chance to look at code today. What was that note I got via email about overwriting? That looked interesting, but I don't see the comment here

**Comment by joskuijpers** [comment]
See ssEconomy, i fixed the wages.

**Comment by theSeb1979** [comment]
That's really good. Amazing.

**Comment by joskuijpers** [comment]
Aa in we still have to determine what the wages will be. But i tried it with 100000 and I paid 200 euros per second for a hired worker :p so it worked

**Comment by theSeb1979** [comment]
How about real average annual farm work salary but base it on 4 x season length in days? So 4x10 is 40.  365/40 days x the average annual farm worker wage. Not sure what it is, but can look up real salary data.

 Then divide that by 365 to get a daily wage, then again by 9 to get an hour wage.  Since we are compressing a year into 40 days, it makes sense to me?
