### ISSUE TITLE
Reproduction rate very big

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [RealismusModding/FS17_seasons#81]
1st day of spring. I had somewhere 150 pigs.
3th day of spring. Now I have >500 pigs. Reproduction rate every 3 min.
This is normal?
It looks like a cheat. For 3 days I gained 7 million.

**Comment by joskuijpers** [comment]
Wow I'll look into this.

The animals will only reproduce in sprig though: not in any other season.
Did you change the number of days in a season?

**Comment by Gonimy-Vetrom** [comment]
> Did you change the number of days in a season?
No. 10 day.
I only adapted an existing savegame, to get to the beginning of spring.

**Comment by joskuijpers** [comment]
Okay I will look at it. Officially we dont support existing savegames.
I am not sure if the high amount of offspring might be related to the change of the ganeday

**Comment by reallogger** [comment]
I have not been able to reproduce this error.

**Comment by Gonimy-Vetrom** [comment]
For example, I started a new game.
I bought 160 pigs on the first day. Save your game.
Fill in all the feeders in the file vehicles.xml block <onCreateLoadedObject saveId = "Animals_pig".
Rewind time. And the result
![fsscreen_2017_01_06_11_47_13](https://cloud.githubusercontent.com/assets/8200153/21714446/a6735ec8-d407-11e6-9073-3376b4d74503.png)
![fsscreen_2017_01_06_11_47_16](https://cloud.githubusercontent.com/assets/8200153/21714447/a67565e2-d407-11e6-8d7c-96bb7af3eb35.png)

**Comment by Gonimy-Vetrom** [comment]
Temporarily, for myself, I changed the parameter in the file animals.xml <birthRate>0.66666667</ birthRate> on <birthRate>0.25</ birthRate>. Now reproduction rate every 20 min.

**Comment by reallogger** [comment]
Should be resolved by 9de8db4
