### ISSUE TITLE
Tips on the screen

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [RealismusModding/FS17_seasons#84]
After saving the game lost crops (cropsThatCanGrow), which can be planted.
It took 2 hours in game.
"Crops that will grow in next transtition if planted now: "
![crops](https://cloud.githubusercontent.com/assets/8200153/21621371/5966df5e-d201-11e6-8998-cb3519ec2206.PNG)

**Comment by reallogger** [comment]
Yes, this happens as the temperature in the soil is below 5 degrees. If you proceed a day or two and the temperature rises you will again see that crops can be sowed.

**Comment by Gonimy-Vetrom** [comment]
At 6 am it was warmer? I do not remember.

**Comment by reallogger** [comment]
Yes for a new savegame the initial soil temperature is set to 6 degrees. But since it is quite cold in the beginning of spring things like this might happen. We might tune this at some point. 

Can you join us on slack? https://realismusmodding.slack.com/messages/general/

**Comment by Gonimy-Vetrom** [comment]
I'm not a programmer. From me is the use?

**Comment by reallogger** [comment]
Only easier for us get information about issues like this. I have some further questions..

**Comment by Gonimy-Vetrom** [comment]
All right. JOIN.

**Comment by reallogger** [comment]
Started to use the mod on an existing savegame so difficult to tell if it was a bug or as intended. Not being able to sow when the soil temperature is below 5 degrees is correct, but the air (and soil) should be warmer by mid spring. But due to existing savegame the comment is closed.
