### ISSUE TITLE
GM gives error for non-standard crop

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#85]
`[Seasons] GrowthManager enabled - growthStateChanged to: 6
[Seasons] Fruit not found in default table: oat
Error: Running LUA method 'update'.
C:/Users/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/ssGrowthManager.lua:199: attempt to index a nil value`

**Comment by reallogger** [comment]
Hot-fix is to change "default" with "barley" on line 137 in ssGrowthManager.lua.

**Comment by theSeb1979** [comment]
Hotfix implemented. Need to think about proper solution though.
