### ISSUE TITLE
Suggestion for winter

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#86]
I was wondering if during winter a new fruit type/layer could be added like image below:

[https://scontent.fbed1-2.fna.fbcdn.net/v/t31.0-8/15844414_1777990809191808_2965174424507202599_o.jpg?oh=14e642ad6f8b7d5ea6f384e5a7ad8b52&oe=58D60189]

Not sure if this could be done or if the layer would have to be physically added to map folder and script refers to that.  I know a lot of people would be happy to actually use the snow removal equipment they have made and not just pretend haha.

Thanks

**Comment by joskuijpers** [comment]
This is what we have already: you can move snow in the winter ;)

**Comment by lindbejb** [comment]
very cool, i guess you have made a lot of changes since i last had this installed

**Comment by reallogger** [comment]
Is it you picture (and mod) lindbejb or do you know where it comes from?

**Comment by lindbejb** [comment]
https://www.facebook.com/Eurogaming-1540347932956098/?hc_ref=PAGES_TIMELINE
