### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#87]
Just installed in mods folder and get a log error

`C:/Users/Joe/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/ssWeatherManager.lua:589: attempt to index a nil value`

**Comment by reallogger** [comment]
Is it for a new savegame or did you include it in an existing savegame?

**Comment by lindbejb** [comment]
C:/Users/Joe/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/src/ssWeatherManager.lua:604: attempt to index a nil value

**Comment by lindbejb** [comment]
saved game

**Comment by reallogger** [comment]
We don't support using the mod on an existing savegame, but I'll make a fix for this one. Will probably upload later tonight.

**Comment by reallogger** [comment]
Should be fixed now with 19aa397
