### ISSUE TITLE
Hud Hiding

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#89]
![fsscreen_2017_01_08_08_54_00](https://cloud.githubusercontent.com/assets/24486785/21751700/2c100ada-d580-11e6-8e31-ebc8947b514c.png)

I switched from Hid Hider mod to Game Extension, yet there is the lettering shown in picture that remain.  Would be nice for screen shot purposes to have this be hidden with other huds as well.  Thanks for you hard work!

**Comment by Gonimy-Vetrom** [comment]
I use the key " NUM /".

**Comment by joskuijpers** [comment]
That is debug text. It will soon be removed.

**Comment by joskuijpers** [comment]
Oh and it should also work with Hud Hider. One of the keys, i think 1 or 0.
