### ISSUE TITLE
[economy] Reduce daily maintenance costs

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#9]
Sticking with the theme of economy and the impact of this mod, we should aim to reduce vehicle daily maintenance costs. The repairVehicles mod is an excellent example of what can be done. Ideally, in my opinion, there should be no daily maintenance cost, only a service every x amount of hours.

**Comment by joskuijpers** [comment]
'hours' being operating hours?

**Comment by theSeb1979** [comment]
Yes, indeed.

**Comment by joskuijpers** [comment]
I am looking at Giants code.

What I want is to see the value that we can change, like with workers.
What I otherwise think is possible is to change (or fake) the vehicle age. If we know what the formula is for calculting the daily costs based on the age, we can change the age before midnight so that it represents the value we want (depending on operatingHours)

**Comment by joskuijpers** [comment]
I found the daily upkeep function. Might be able to override just that function. (Vehicle.getDailyUpkeep)

**Comment by reallogger** [comment]
@joskuijpers You just posted before I managed to hit the Comment button... 

Forgive me if you know this already, but is this related to ValueDailyUpKeep

getSpecValueDailyUpKeep is the one you are looking for I think.

**Comment by joskuijpers** [comment]
Okay I know I can fix this :p it will be maybe tomorrow or otherwise monday though.

**Comment by joskuijpers** [comment]
I am thinking about making dirt cost money? So that if you keep your stuff clean the maintenance costs don't go up so quickly? (Or lowers te cost per day/whatever). Makes the oressure washer an actual usable tool.

**Comment by reallogger** [comment]
I think that is a very good idea. You could simply have a cost times the dirtValue and add it as a multiplier like ageMultiplier and operatingTimeMultiplier in hte DailyUpKeep. Even just using dirtValue +1 would work I think. So with "fully" dirty the cost would be twice compared to as if it is clean.

**Comment by joskuijpers** [comment]
Using `getfenv(0)` I can get access to the Vehicle class and overwrite the getDailyUpkeep method 😄  that is how I will fix this

**Comment by theSeb1979** [comment]
Returns the current environment in use by the function. f can be a Lua function or a number that specifies the function at that stack level: Level 1 is the function calling getfenv. If the given function is not a Lua function, or if f is 0, getfenv returns the global environment. The default for f is 1.

Ahh, got it now. You can disregard my question in the other issue.
