### ISSUE TITLE
Dedicated Server Fails to Load

### ISSUE THREAD

**Issue by lindbejb** [RealismusModding/FS17_seasons#90]
In the modDesc it stats it is MP compatible, yet it fails to load on a dedicated server.
![screenshot 2017-01-08 10 55 59](https://cloud.githubusercontent.com/assets/24486785/21752652/39fd9372-d591-11e6-8491-0fc59d4e79c8.png)

No errors in log though.

**Comment by joskuijpers** [comment]
We are still working on it.

Even though the modDesc says it supports MP, the mod has not been released yet :)

Thanks for testing though!

**Comment by lindbejb** [comment]
ok, begining to modeling a snow plow now hahah

**Comment by joskuijpers** [comment]
This should be resolved

**Comment by Dzi4d3k** [comment]
These where only warnings, and I can confirm that there is no warnings now.
